### ISSUE TITLE
Cassandra fails with static VM's

### ISSUE THREAD

**Issue by GitVail** [GoogleCloudPlatform/PerfKitBenchmarker#1060]
I pre-installed for cassandra_stress and cassandra_ycsb on a local machine, which I then tested with the static_vm_file method. The json file listed the machine's IP 6 times. 
They both fail with the message "Failed to start Cassandra cluster".  Logs attached
[cassandra_stress_pkb.log.txt](https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/files/378526/cassandra_stress_pkb.log.txt)
[cassandra_ycsb_pkb.log.txt](https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/files/378525/cassandra_ycsb_pkb.log.txt)

**Comment by voellm** [comment]
Where you able to run Cassandra  stress without PKB?  It looks like there is some setup still missing...  This is from the error logs you shared.

JMX is not enabled to receive remote connections. Please see cassandra-env.sh for more info.
ERROR 13:12:30 Error starting local jmx server: 
java.rmi.server.ExportException: Port already in use: 7199; nested exception is: 
	java.net.BindException: Address already in use
	at sun.rmi.transport.tcp.TCPTransport.listen(TCPTransport.java:340) ~[na:1.7.0_101]
	at sun.rmi.transport.tcp.TCPTransport.exportObject(TCPTransport.java:248) ~[na:1.7.0_101]
	at sun.rmi.transport.tcp.TCPEndpoint.exportObject(TCPEndpoint.java:411) ~[na:1.7.0_101]
	at sun.rmi.transport.LiveRef.exportObject(LiveRef.java:147) ~[na:1.7.0_101]
	at sun.rmi.server.UnicastServerRef.exportObject(UnicastServerRef.java:211) ~[na:1.7.0_101]
	at sun.rmi.registry.RegistryImpl.setup(RegistryImpl.java:123) ~[na:1.7.0_101]
	at sun.rmi.registry.RegistryImpl.<init>(RegistryImpl.java:99) ~[na:1.7.0_101]
	at java.rmi.registry.LocateRegistry.createRegistry(LocateRegistry.java:239) ~[na:1.7.0_101]
	at org.apache.cassandra.service.CassandraDaemon.maybeInitJmx(CassandraDaemon.java:100) [apache-cassandra-2.1.15.jar:2.1.15]

**Comment by yuyantingzero** [comment]
@GitVail if i understand you correctly, you are using a single local machine and pretend having multiple servers, clients?

All cassandra servers listen on same ports, configs shown in perfkitbenchmarker/data/cassandra/.
In your case, only the first copy of cassandra server will be able to start, the remainings will fail due to "address already in use".

If you only have 1 physical machine as cassandra server, you can add --num_vms=1.

Multiple clients running on same machine should be fine, but probably not necessary. Both benchmarks can increase thread count.

**Comment by yuyantingzero** [comment]
@GitVail Let me know if you still need help. Closing it now, feel free to reopen
