### ISSUE TITLE
hbase_ycsb‘ result of overall Throughput is zero

### ISSUE THREAD

**Issue by xiahaihong** [GoogleCloudPlatform/PerfKitBenchmarker#1121]
After I ran about 10 hours `--benchmarks=hbase_ycsb`
 I got invalid result  with zero , but no error

`-------------------------PerfKitBenchmarker Results Summary-------------------------
HBASE_YCSB:
  columnfamily="cf" hbase_cluster_size="2" hbase_zookeeper_nodes="1" insertproportion="0" operation="overall" operationcount="1000" readallfields="true" requestdistribution="zipfian" result_type="combined" scanproportion="0" workload="com.yahoo.ycsb.workloads.CoreWorkload" ycsb_client_vms="1"
  overall RunTime                  531780.000000 ms                             (clientbuffering="true" clients="1" command_line="unknown" readproportion="0.5" recordcount="1000000" stage="load" threads="1" threads_per_client_vm="1" updateproportion="0.5" workload_name="workloada")
  overall Throughput                    0.000000 ops/sec                        (clientbuffering="true" clients="1" command_line="unknown" readproportion="0.5" recordcount="1000000" stage="load" threads="1" threads_per_client_vm="1" updateproportion="0.5" workload_name="workloada")
  overall RunTime                16981574.000000 ms                             (clientbuffering="false" clients="32" command_line="Command line: -db com.yahoo.ycsb.db.HBaseClient10 -threads 32 -P /tmp/pkb/workloada -p clientbuffering=false -p columnfamily=cf -p recordcount=1000000 -p maxexecutiontime=1800 -p operationcount=1000000 -p measurementtype=histogram -t" readproportion="0.5" stage="run" threads_per_client_vm="32" updateproportion="0.5" workload_index="0" workload_name="workloada")
  overall Throughput                    0.000000 ops/sec                        (clientbuffering="false" clients="32" command_line="Command line: -db com.yahoo.ycsb.db.HBaseClient10 -threads 32 -P /tmp/pkb/workloada -p clientbuffering=false -p columnfamily=cf -p recordcount=1000000 -p maxexecutiontime=1800 -p operationcount=1000000 -p measurementtype=histogram -t" readproportion="0.5" stage="run" threads_per_client_vm="32" updateproportion="0.5" workload_index="0" workload_name="workloada")
  overall RunTime                16983579.000000 ms                             (clientbuffering="false" clients="32" command_line="Command line: -db com.yahoo.ycsb.db.HBaseClient10 -threads 32 -P /tmp/pkb/workloadb -p clientbuffering=false -p columnfamily=cf -p recordcount=1000000 -p maxexecutiontime=1800 -p operationcount=1000000 -p measurementtype=histogram -t" readproportion="0.95" stage="run" threads_per_client_vm="32" updateproportion="0.05" workload_index="1" workload_name="workloadb")
  overall Throughput                    0.000000 ops/sec                        (clientbuffering="false" clients="32" command_line="Command line: -db com.yahoo.ycsb.db.HBaseClient10 -threads 32 -P /tmp/pkb/workloadb -p clientbuffering=false -p columnfamily=cf -p recordcount=1000000 -p maxexecutiontime=1800 -p operationcount=1000000 -p measurementtype=histogram -t" readproportion="0.95" stage="run" threads_per_client_vm="32" updateproportion="0.05" workload_index="1" workload_name="workloadb")
  End to End Runtime                35031.747399 seconds`

**Comment by hildrum** [comment]
You have the pkb.log file?

**Comment by xiahaihong** [comment]
as attached, @hildrum 
[pkb.log.txt](https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/files/496961/pkb.log.txt)

**Comment by hildrum** [comment]
Looks like the root problem is this:
`com.google.protobuf.ServiceException: java.net.UnknownHostException: unknown host: iZ2ze0yn32hnb353731ldiZ`

Could it be something with the hostname not being well-formed?

**Comment by xiahaihong** [comment]
I found that iZ2ze0yn32hnb353731ldiZ received SHUTDOWN msg before, and is that normal when run hbase test?
```
18298 16/09/21 21:53:14 INFO common.Storage: Storage directory /scratch/hadoop/dfs/name has been successfully formatted.
18299 16/09/21 21:53:14 INFO namenode.NNStorageRetentionManager: Going to retain 1 images with txid >= 0
18300 16/09/21 21:53:14 INFO util.ExitUtil: Exiting with status 0
18301 16/09/21 21:53:14 INFO namenode.NameNode: SHUTDOWN_MSG:
18302 /************************************************************
18303 SHUTDOWN_MSG: Shutting down NameNode at iZ2ze0yn32hnb353731ldiZ/10.0.0.3
18304 ************************************************************/
```

**Comment by xiahaihong** [comment]
I think hadoop need 3 vms at least
but in perfkit code, it use 2 vms by default, is that right ?
```
def GetConfig(user_config):
  config = configs.LoadConfig(BENCHMARK_CONFIG, user_config, BENCHMARK_NAME)
  num_vms = max(FLAGS.num_vms, 2)
  if FLAGS['num_vms'].present and FLAGS.num_vms < 2:
    raise ValueError('hbase_ycsb requires at least 2 HBase VMs.')
  if FLAGS['ycsb_client_vms'].present:
    config['vm_groups']['clients']['vm_count'] = FLAGS.ycsb_client_vms
  if FLAGS['num_vms'].present:
    config['vm_groups']['workers']['vm_count'] = num_vms - 1
  return config
```

**Comment by xiahaihong** [comment]
```
2016-09-29 13:29:26,727 438dd778 MainThread hbase_ycsb(1/1) INFO     Ran ssh -A -p 22 ubuntu@139.196.96.246 -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /tmp/perfkitbenchmarker/runs/438dd778/perfkitbenchmarker_keyfile /tmp/pkb/hbase/bin/hbase shell /tmp/pkb/hbase/create-ycsb-table.hbaseshell. Got return code (0).
STDOUT:
ERROR: org.apache.hadoop.hbase.PleaseHoldException: Master is initializing
        at org.apache.hadoop.hbase.master.HMaster.checkInitialized(HMaster.java:2240)
        at org.apache.hadoop.hbase.master.HMaster.checkNamespaceManagerReady(HMaster.java:2245)
        at org.apache.hadoop.hbase.master.HMaster.ensureNamespaceExists(HMaster.java:2438)
        at org.apache.hadoop.hbase.master.HMaster.createTable(HMaster.java:1460)
        at org.apache.hadoop.hbase.master.MasterRpcServices.createTable(MasterRpcServices.java:429)
        at org.apache.hadoop.hbase.protobuf.generated.MasterProtos$MasterService$2.callBlockingMethod(MasterProtos.java:52195)
        at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2127)
        at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:107)
        at org.apache.hadoop.hbase.ipc.RpcExecutor.consumerLoop(RpcExecutor.java:133)
        at org.apache.hadoop.hbase.ipc.RpcExecutor$1.run(RpcExecutor.java:108)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by xiahaihong** [comment]
I have found the reason.
I have to edit the /etc/hosts file manualy, to prepare the "ip hostname"  for hadoop vms

**Comment by hildrum** [comment]
The namenode shutdown message is normal.

I confirmed that with GCP, there's no need to edit the `/etc/hosts` file.  I'm pretty sure that's true on AWS and Azure as well.

**Comment by xiahaihong** [comment]
OK。thanks。

**Comment by hildrum** [comment]
It'd be nice to make a change to the benchmark or to the rackspace provider so that no manual changes are necessary to /etc/hosts, but I don't think we have the resources to do that.
