### ISSUE TITLE
Error during benchmark iperf

### ISSUE THREAD

**Issue by ksasi** [GoogleCloudPlatform/PerfKitBenchmarker#120]
Receiving the following error while running PerfKitBenchmarker iperf.Please advise on the resolution

ubuntu@ip-172-30-0-134:~/GPerfKitB/PerfKitBenchmarker$ clear
ubuntu@ip-172-30-0-134:~/GPerfKitB/PerfKitBenchmarker$ ./pkb.py --cloud=AWS --benchmarks=iperf --machine_type=t1.micro
2015-02-16 05:11:09,800 INFO     Verbose logging to: /tmp/perfkitbenchmarker/run_569a6928/pkb.log
2015-02-16 05:11:09,910 INFO     Preparing benchmark iperf
2015-02-16 05:11:09,911 INFO     Running: aws ec2 create-vpc --region=us-east-1 --cidr-block=10.0.0.0/16
2015-02-16 05:11:10,426 ERROR    Error during benchmark iperf
Traceback (most recent call last):
  File "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 228, in RunBenchmark
    benchmark_specification.Prepare()
  File "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 185, in Prepare
    vm_util.RunThreaded(self.PrepareNetwork, prepare_args)
  File "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 249, in RunThreaded
    '\n'.join([stacktrace for stacktrace in exceptions]))
ThreadException: The following exceptions occurred during threaded execution: Traceback (most recent call last):
  File "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 236, in RunThreaded
    thread.join(1000)  # Set timeout so that join is interruptable.
  File "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 179, in join
    raise errors.VmUtil.ThreadException(self.exception)
ThreadException: Exception occured in thread 139723530974976:
Traceback (most recent call last):
  File "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 166, in run
    self.RunWithExceptions()
  File "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 173, in RunWithExceptions
    super(ThreadWithExceptions, self).run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 202, in PrepareNetwork
    network.Create()
  File "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/aws/aws_network.py", line 339, in Create
    self.vpc.Create()
  File "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/resource.py", line 113, in Create
    self._CreateResource()
  File "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 306, in WrappedFunction
    return f(*args, **kwargs)
  File "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/resource.py", line 87, in _CreateResource
    self._Create()
  File "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/aws/aws_network.py", line 104, in _Create
    response = json.loads(stdout)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

2015-02-16 05:11:10,428 INFO     Running: aws ec2 --region=us-east-1 delete-key-pair --key-name=perfkit-key-569a6928
Traceback (most recent call last):
  File "./pkb.py", line 21, in <module>
    sys.exit(Main())
  File "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 358, in Main
    return RunBenchmarks()
  File "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 324, in RunBenchmarks
    RunBenchmark(benchmark, collector)
  File "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 228, in RunBenchmark
    benchmark_specification.Prepare()
  File "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 185, in Prepare
    vm_util.RunThreaded(self.PrepareNetwork, prepare_args)
  File "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 249, in RunThreaded
    '\n'.join([stacktrace for stacktrace in exceptions]))
perfkitbenchmarker.errors.ThreadException: The following exceptions occurred during threaded execution: Traceback (most recent call last):
  File "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 236, in RunThreaded
    thread.join(1000)  # Set timeout so that join is interruptable.
  File "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 179, in join
    raise errors.VmUtil.ThreadException(self.exception)
ThreadException: Exception occured in thread 139723530974976:
Traceback (most recent call last):
  File "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 166, in run
    self.RunWithExceptions()
  File "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 173, in RunWithExceptions
    super(ThreadWithExceptions, self).run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 202, in PrepareNetwork
    network.Create()
  File "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/aws/aws_network.py", line 339, in Create
    self.vpc.Create()
  File "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/resource.py", line 113, in Create
    self._CreateResource()
  File "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 306, in WrappedFunction
    return f(*args, **kwargs)
  File "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/resource.py", line 87, in _CreateResource
    self._Create()
  File "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/aws/aws_network.py", line 104, in _Create
    response = json.loads(stdout)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by voellm** [comment]
One of the things that PKB does is to print each command it is running.  In
this case it looks like an aws command is failing.

What do you get when you run this by its self?  Its the first failing
command I see in the log.

aws ec2 create-vpc --region=us-east-1 --cidr-block=10.0.0.0/16

Also what version of the aws command line tool are you running?

**Comment by ksasi** [comment]
The aws command seem to be working fine. Below is the o/p

ubuntu@ip-172-30-0-134:~$ aws ec2 create-vpc --region=us-east-1 --cidr-block=10.0.0.0/16
VPC     10.0.0.0/16     dopt-74a6ba16   default pending vpc-b3e49cd6
ubuntu@ip-172-30-0-134:~$

The version of aws cli is 

aws-cli/1.7.8 Python/2.7.6 Linux/3.13.0-36-generic

**Comment by cmccoy** [comment]
Could you look at the output in `/tmp/perfkitbenchmarker/run_569a6928/pkb.log` as well? There should be a log entry showing that command's stderr and stdout.

**Comment by voellm** [comment]
Sasikanth - Did you have a chance to get this working?  What was the error
in the log?

Thanks - Tony

On Mon, Feb 16, 2015 at 7:53 AM, Connor McCoy <notifications@github.com>
wrote:

> Could you look at the output in
> /tmp/perfkitbenchmarker/run_569a6928/pkb.log as well? There should be a
> log entry showing that command's stderr and stdout.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/120#issuecomment-74528898>
> .
>



-- 
Anthony F. Voellm (aka Tony)
Google Voice:  (650) 516-7382
<https://www.google.com/voice/b/0?pli=1#phones>
Blog: http://perfguy.blogspot.com/

**Comment by ksasi** [comment]
Hi,

Below is the output of the log file



ubuntu@ip-172-30-0-134:/tmp/perfkitbenchmarker/run_569a6928$ more pkb.log
2015-02-16 05:11:09,910 publisher.py:394 DEBUG    Using publishers: [<LogPublisher logger=<logging.RootLogger object at 0x7f13eca45950> level=20>, <PrettyPrintStreamPub
lisher stream=<open file '<stdout>', mode 'w' at 0x7f13ee509150>>, <NewlineDelimitedJSONPublisher file_path="/tmp/perfkitbenchmarker/run_569a6928/perfkitbenchmarker_res
ults.json" mode="wb">]
2015-02-16 05:11:09,910 pkb.py:226 INFO     Preparing benchmark iperf
2015-02-16 05:11:09,911 vm_util.py:335 INFO     Running: aws ec2 create-vpc --region=us-east-1 --cidr-block=10.0.0.0/16
2015-02-16 05:11:10,408 vm_util.py:349 DEBUG    Ran aws ec2 create-vpc --region=us-east-1 --cidr-block=10.0.0.0/16. Got return code (0). STDOUT: VPC    10.0.0.0/16
dopt-74a6ba16   default pending vpc-74b0c811
STDERR:
2015-02-16 05:11:10,426 pkb.py:256 ERROR    Error during benchmark iperf
Traceback (most recent call last):
  File "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 228, in RunBenchmark
    benchmark_specification.Prepare()
  File "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 185, in Prepare
    vm_util.RunThreaded(self.PrepareNetwork, prepare_args)
  File "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 249, in RunThreaded
    '\n'.join([stacktrace for stacktrace in exceptions]))
ThreadException: The following exceptions occurred during threaded execution: Traceback (most recent call last):
  File "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 236, in RunThreaded
    thread.join(1000)  # Set timeout so that join is interruptable.
  File "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 179, in join
    raise errors.VmUtil.ThreadException(self.exception)
ThreadException: Exception occured in thread 139723530974976:
Traceback (most recent call last):
  File "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 166, in run
    self.RunWithExceptions()
  File "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 173, in RunWithExceptions
    super(ThreadWithExceptions, self).run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 202, in PrepareNetwork
    network.Create()
  File "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/aws/aws_network.py", line 339, in Create
    self.vpc.Create()
  File "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/resource.py", line 113, in Create
    self._CreateResource()
  File "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 306, in WrappedFunction
    return f(*args, **kwargs)
  File "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/resource.py", line 87, in _CreateResource
    self._Create()
  File "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/aws/aws_network.py", line 104, in _Create
    response = json.loads(stdout)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded


2015-02-16 05:11:10,428 vm_util.py:335 INFO     Running: aws ec2 --region=us-east-1 delete-key-pair --key-name=perfkit-key-569a6928
2015-02-16 05:11:10,734 vm_util.py:349 DEBUG    Ran aws ec2 --region=us-east-1 delete-key-pair --key-name=perfkit-key-569a6928. Got return code (0). STDOUT: STDERR:
ubuntu@ip-172-30-0-134:/tmp/perfkitbenchmarker/run_569a6928$

**Comment by voellm** [comment]
Thanks for working with on this.  It's pretty odd.

So we can repro please try to give as much detail about your environment as
you can.  Will also add collection of this type of into future logs so we
dont have to ask.

What are you running on?  Mac/Linux/CYGWIN/Other?
What shell? Bash?
What version of Python?
Anything else you think is relevant.



On Tue, Feb 17, 2015 at 6:01 AM, Sasikanth <notifications@github.com> wrote:

> Hi,
>
> Below is the output of the log file
>
> ubuntu@ip-172-30-0-134:/tmp/perfkitbenchmarker/run_569a6928$ more pkb.log
> 2015-02-16 05:11:09,910 publisher.py:394 DEBUG Using publishers: [
> level=20>, lisher stream=', mode 'w' at 0x7f13ee509150>>, ]
> 2015-02-16 05:11:09,910 pkb.py:226 INFO Preparing benchmark iperf
> 2015-02-16 05:11:09,911 vm_util.py:335 INFO Running: aws ec2 create-vpc
> --region=us-east-1 --cidr-block=10.0.0.0/16
> 2015-02-16 05:11:10,408 vm_util.py:349 DEBUG Ran aws ec2 create-vpc
> --region=us-east-1 --cidr-block=10.0.0.0/16. Got return code (0). STDOUT:
> VPC 10.0.0.0/16
> dopt-74a6ba16 default pending vpc-74b0c811
> STDERR:
> 2015-02-16 05:11:10,426 pkb.py:256 ERROR Error during benchmark iperf
>
> Traceback (most recent call last):
> File
> "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line
> 228, in RunBenchmark
> benchmark_specification.Prepare()
> File
> "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py",
> line 185, in Prepare
> vm_util.RunThreaded(self.PrepareNetwork, prepare_args)
> File
> "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py",
> line 249, in RunThreaded
> '\n'.join([stacktrace for stacktrace in exceptions]))
> ThreadException: The following exceptions occurred during threaded
> execution: Traceback (most recent call last):
> File
> "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py",
> line 236, in RunThreaded
> thread.join(1000) # Set timeout so that join is interruptable.
> File
> "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py",
> line 179, in join
> raise errors.VmUtil.ThreadException(self.exception)
> ThreadException: Exception occured in thread 139723530974976:
> Traceback (most recent call last):
> File
> "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py",
> line 166, in run
> self.RunWithExceptions()
> File
> "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py",
> line 173, in RunWithExceptions
> super(ThreadWithExceptions, self).run()
> File "/usr/lib/python2.7/threading.py", line 763, in run
> self.
>
>
>
>
>
>
>
>
>
>
>
>
> *target(self.__args, *self.__kwargs) File
> "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py",
> line 202, in PrepareNetwork network.Create() File
> "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/aws/aws_network.py",
> line 339, in Create self.vpc.Create() File
> "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/resource.py",
> line 113, in Create self._CreateResource() File
> "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py",
> line 306, in WrappedFunction return f(args, *kwargs) File
> "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/resource.py",
> line 87, in _CreateResource self._Create() File
> "/home/ubuntu/GPerfKitB/PerfKitBenchmarker/perfkitbenchmarker/aws/aws_network.py",
> line 104, in _Create response = json.loads(stdout) File
> "/usr/lib/python2.7/json/__init*.py", line 338, in loads
> return _default_decoder.decode(s)
> File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
> obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
> raise ValueError("No JSON object could be decoded")
> ValueError: No JSON object could be decoded
>
> 2015-02-16 05:11:10,428 vm_util.py:335 INFO Running: aws ec2
> --region=us-east-1 delete-key-pair --key-name=perfkit-key-569a6928
> 2015-02-16 05:11:10,734 vm_util.py:349 DEBUG Ran aws ec2
> --region=us-east-1 delete-key-pair --key-name=perfkit-key-569a6928. Got
> return code (0). STDOUT: STDERR:
> ubuntu@ip-172-30-0-134:/tmp/perfkitbenchmarker/run_569a6928$
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/120#issuecomment-74671479>
> .
>



-- 
Anthony F. Voellm (aka Tony)
Google Voice:  (650) 516-7382
<https://www.google.com/voice/b/0?pli=1#phones>
Blog: http://perfguy.blogspot.com/

**Comment by cmccoy** [comment]
Do you by any chance have an output format specified in `~/.aws/config`, or the environment variable `AWS_DEFAULT_OUTPUT` set?  If so, this may be related to #121.

**Comment by ksasi** [comment]
This appears to be related to #121 . The output format seems to be text in ~/.aws/config as shown below

ubuntu@ip-172-30-0-134:~$ more ~/.aws/config
[default]
output = text
region = us-east-1

I have changed the output=text to output=json and now this seems to be running fine. Thanks for the guidance and suggestions.

**Comment by cmccoy** [comment]
Glad to hear it, and thanks for reporting this!

Closing this; we'll track output overrides in #121.
