### ISSUE TITLE
OpenStack subnet info issue

### ISSUE THREAD

**Issue by vladiskuz** [GoogleCloudPlatform/PerfKitBenchmarker#1248]
I've installed Devstack with 2 nodes - first all-in-one installation, second compute node installation.
Openstack version:
```
$ nova-manage version
14.0.0
```
I have the following networks:
```
$ neutron net-list
+--------------------------------------+---------+----------------------------------------------------------+
| id                                   | name    | subnets                                                  |
+--------------------------------------+---------+----------------------------------------------------------+
| da04d56f-d51d-4d55-b816-a9d3f6e8f54f | private | 6809dbb9-0bb8-46bc-9bf0-b4bd9c7ac897 10.0.0.0/24         |
|                                      |         | 90f8868b-c967-497e-bbb1-f4dd5ef847ca fd7b:720e:cae8::/64 |
| e01e1f87-f5fa-4734-9595-a97517072b28 | public  | 2cc03feb-7428-4a1d-a5d4-c4443d4bda77 2001:db8::/64       |
|                                      |         | 44a151d9-c807-44ce-aada-731dda7c22b3 172.24.4.0/24       |
+--------------------------------------+---------+----------------------------------------------------------+
```
And the following subnets:
```
$ neutron subnet-list
+--------------------------------------+---------------------+---------------------+-------------------------------------------------------------------------------+
| id                                   | name                | cidr                | allocation_pools                                                              |
+--------------------------------------+---------------------+---------------------+-------------------------------------------------------------------------------+
| 2cc03feb-7428-4a1d-a5d4-c4443d4bda77 | ipv6-public-subnet  | 2001:db8::/64       | {"start": "2001:db8::1", "end": "2001:db8::1"}                                |
|                                      |                     |                     | {"start": "2001:db8::3", "end": "2001:db8::ffff:ffff:ffff:ffff"}              |
| 44a151d9-c807-44ce-aada-731dda7c22b3 | public-subnet       | 172.24.4.0/24       | {"start": "172.24.4.2", "end": "172.24.4.254"}                                |
| 6809dbb9-0bb8-46bc-9bf0-b4bd9c7ac897 | private-subnet      | 10.0.0.0/24         | {"start": "10.0.0.2", "end": "10.0.0.254"}                                    |
| 90f8868b-c967-497e-bbb1-f4dd5ef847ca | ipv6-private-subnet | fd7b:720e:cae8::/64 | {"start": "fd7b:720e:cae8::2", "end": "fd7b:720e:cae8:0:ffff:ffff:ffff:ffff"} |
+--------------------------------------+---------------------+---------------------+-------------------------------------------------------------------------------+
```
And I trying to run:
```
./pkb.py --cloud=OpenStack --machine_type=m1.medium --openstack_network=private --benchmarks=ping --image=cirros-0.3.4-x86_64-uec
```

And I've faced with a problem:
```
2016-12-13 16:17:26,235 ec18c1e2 MainThread INFO     Verbose logging to: /tmp/perfkitbenchmarker/runs/ec18c1e2/pkb.log
2016-12-13 16:17:26,236 ec18c1e2 MainThread INFO     PerfKitBenchmarker version: v1.9.0-78-ge00c40b
2016-12-13 16:17:26,237 ec18c1e2 MainThread INFO     Flag values:
--machine_type=m1.medium
--openstack_network=private
--image=cirros-0.3.4-x86_64-uec
--cloud=OpenStack
--benchmarks=ping
2016-12-13 16:17:26,644 ec18c1e2 MainThread WARNING  The key "flags" was not in the default config, but was in user overrides. This may indicate a typo.
2016-12-13 16:17:26,847 ec18c1e2 MainThread ping(1/1) INFO     Provisioning resources for benchmark ping
2016-12-13 16:17:26,851 ec18c1e2 Thread-2 ping(1/1) INFO     Testing OpenStack CLI command is installed and working
2016-12-13 16:17:26,852 ec18c1e2 Thread-2 ping(1/1) INFO     Running: openstack image list --format json
2016-12-13 16:17:28,012 ec18c1e2 Thread-2 ping(1/1) INFO     Validating prerequisites.
2016-12-13 16:17:28,014 ec18c1e2 Thread-2 ping(1/1) INFO     Running: openstack image show cirros-0.3.4-x86_64-uec --format json
2016-12-13 16:17:29,073 ec18c1e2 Thread-2 ping(1/1) INFO     Running: openstack flavor show m1.medium --format json
2016-12-13 16:17:30,426 ec18c1e2 Thread-2 ping(1/1) INFO     Running: openstack network show private --format json
2016-12-13 16:17:31,514 ec18c1e2 Thread-2 ping(1/1) INFO     Prerequisites validated.
2016-12-13 16:17:31,514 ec18c1e2 Thread-2 ping(1/1) INFO     Running: openstack security group show perfkit_sc_group --format json
2016-12-13 16:17:32,583 ec18c1e2 Thread-2 ping(1/1) INFO     Running: openstack keypair create perfkit_key_ec18c1e2 --format json --public-key /tmp/perfkitbenchmarker/runs/ec18c1e2/perfkitbenchmarker_keyfi
le.pub
2016-12-13 16:17:33,578 ec18c1e2 Thread-2 ping(1/1) INFO     Running: openstack network show private --format json
2016-12-13 16:17:33,583 ec18c1e2 Thread-3 ping(1/1) INFO     Running: openstack network show private --format json
2016-12-13 16:17:34,763 ec18c1e2 Thread-3 ping(1/1) INFO     Running: openstack subnet show 6809dbb9-0bb8-46bc-9bf0-b4bd9c7ac897, 90f8868b-c967-497e-bbb1-f4dd5ef847ca --format json
2016-12-13 16:17:34,816 ec18c1e2 Thread-2 ping(1/1) INFO     Running: openstack subnet show 6809dbb9-0bb8-46bc-9bf0-b4bd9c7ac897, 90f8868b-c967-497e-bbb1-f4dd5ef847ca --format json
2016-12-13 16:17:35,891 ec18c1e2 Thread-3 ping(1/1) INFO     Ran openstack subnet show 6809dbb9-0bb8-46bc-9bf0-b4bd9c7ac897, 90f8868b-c967-497e-bbb1-f4dd5ef847ca --format json. Got return code (1).
STDOUT: 
STDERR: ResourceNotFound: No Subnet found for 6809dbb9-0bb8-46bc-9bf0-b4bd9c7ac897, 90f8868b-c967-497e-bbb1-f4dd5ef847ca

2016-12-13 16:17:35,892 ec18c1e2 MainThread ping(1/1) ERROR    Exception occurred while calling PrepareVm(<BaseVirtualMachine [ip=None, internal_ip=None]>):
Traceback (most recent call last):
  File "/home/user1/PerfKitBenchmarker/perfkitbenchmarker/background_tasks.py", line 235, in Run
    self.return_value = self.target(*self.args, **self.kwargs)
  File "/home/user1/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 389, in PrepareVm
    vm.Create()
  File "/home/user1/PerfKitBenchmarker/perfkitbenchmarker/resource.py", line 160, in Create
    self._CreateDependencies()
  File "/home/user1/PerfKitBenchmarker/perfkitbenchmarker/providers/openstack/os_virtual_machine.py", line 97, in _CreateDependencies
    source_range = self._GetInternalNetworkCIDR()
  File "/home/user1/PerfKitBenchmarker/perfkitbenchmarker/providers/openstack/os_virtual_machine.py", line 365, in _GetInternalNetworkCIDR
    subnet_dict = json.loads(stdout)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

I think the problem lies in the fact that the command `openstack subnet show 6809dbb9-0bb8-46bc-9bf0-b4bd9c7ac897, 90f8868b-c967-497e-bbb1-f4dd5ef847ca --format json` pass 2 subnets in one time. Is it a problem in PerfKitBenchmarker or is it missconfiguration?

**Comment by meteorfox** [comment]
Thanks for reporting. I think this is definitely a bug. In your use-case, each network has multiple subnets, 1 for IPv4 and another for IPv6 addresses, the current implementation makes the wrong assumption that a network only has 1 subnet.

I'll work on a patch to fix this.

As a workaround, if you can, you could remove the IPv6 subnets and I expect that it would work.

**Comment by meteorfox** [comment]
Also, unrelated to this issue, but you will need to use another image instead of CirrOS, at the moment we only support Debian or RHEL based Linux (e.g. basically distros using APT or RPM packages), at least for the OpenStack provider implementation, and AFAIK CirrOS does not include any package manager which means PerfKit Benchmarker won't be able to install the dependencies required to execute the benchmarks.
