### ISSUE TITLE
allow scratch space to be an aribtirary directory

### ISSUE THREAD

**Issue by cburroughs** [GoogleCloudPlatform/PerfKitBenchmarker#127]
It would be useful to be able to run PerfKitBenchmarker on VMs/containers/physical-servers where there isn't a dedicated mount point for the scratch space, or where creating a mountpoint per service is not supported.

Currenlty trying to run fio with `"scratch_disk_mountpoints": "/tmp/google-pkb"` results in```
Traceback (most recent call last):
  File "./pkb.py", line 21, in <module>
    sys.exit(Main())
  File "/home/csb/prog/github/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 358, in Main
    return RunBenchmarks()
  File "/home/csb/prog/github/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 324, in RunBenchmarks
    RunBenchmark(benchmark, collector)
  File "/home/csb/prog/github/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 229, in RunBenchmark
    benchmark.Prepare(benchmark_specification)
  File "/home/csb/prog/github/PerfKitBenchmarker/perfkitbenchmarker/benchmarks/fio_benchmark.py", line 65, in Prepare
    disk_size_kb = vm.GetDeviceSizeFromPath(vm.GetScratchDir())
  File "/home/csb/prog/github/PerfKitBenchmarker/perfkitbenchmarker/virtual_machine.py", line 405, in GetDeviceSizeFromPath
    return int(stdout)
ValueError: invalid literal for int() with base 10: '210411904 16419404 '
```

While omitting results in the only marginally more helpful error message:
```
Traceback (most recent call last):
  File "./pkb.py", line 21, in <module>
    sys.exit(Main())
  File "/home/csb/prog/github/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 358, in Main
    return RunBenchmarks()
  File "/home/csb/prog/github/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 324, in RunBenchmarks
    RunBenchmark(benchmark, collector)
  File "/home/csb/prog/github/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 229, in RunBenchmark
    benchmark.Prepare(benchmark_specification)
  File "/home/csb/prog/github/PerfKitBenchmarker/perfkitbenchmarker/benchmarks/fio_benchmark.py", line 65, in Prepare
    disk_size_kb = vm.GetDeviceSizeFromPath(vm.GetScratchDir())
  File "/home/csb/prog/github/PerfKitBenchmarker/perfkitbenchmarker/static_virtual_machine.py", line 91, in GetScratchDir
    scratch_dir = self.scratch_disk_mountpoints[disk_num]
IndexError: list index out of range
```

**Comment by voellm** [comment]
Sounds like a good flag option to have.  Marking it as a feature and needing help.  If someone wants to pick it up we can assign them and proceed on how best to do it.

**Comment by voellm** [comment]
Connor - Did I see you fix this?

**Comment by cmccoy** [comment]
No, still open.  I fixed a hard-coded path in the fio benchmark.

**Comment by cmccoy** [comment]
This is done, but the documentation was not clear and no error was thrown if the user provides a string to `static_disk_mountpoints`. #166 addresses the documentation error and adds an error on an invalid static VM  file.

**Comment by cmccoy** [comment]
Documentation updated by #166. Closing.
