### ISSUE TITLE
Kubernetes provider does not work.

### ISSUE THREAD

**Issue by tedhtchang** [GoogleCloudPlatform/PerfKitBenchmarker#1293]
I don't think the Kubernetes provider works. Here is the problem.
I ran:
`./pkb.py --kubectl=/home/ubuntu/kubectl --kubeconfig=/home/ubuntu/admin.conf --cloud=Kubernetes --benchmarks=cluster_boot --kubernetes_nodes=192.168.56.104,192.168.56.107 --image=ubuntu_ssh --log_level=debug  --username=ubuntu`

It hangs here for 300s and quits:
```
2017-02-15 18:20:35,904 a25ba62b Thread-2 cluster_boot(1/1) INFO     Running: /home/ubuntu/kubectl --kubeconfig=/home/ubuntu/admin.conf create -f -

2017-02-15 18:25:35,922 a25ba62b Thread-4 ERROR    IssueCommand timed out after 300 seconds. Killing command "/home/ubuntu/kubectl --kubeconfig=/home/ubuntu/admin.conf create -f -".
2017-02-15 18:25:35,923 a25ba62b Thread-2 cluster_boot(1/1) INFO     Ran /home/ubuntu/kubectl --kubeconfig=/home/ubuntu/admin.conf create -f -. Got return code (-9).
STDOUT:
STDERR:
2017-02-15 18:25:35,924 a25ba62b MainThread cluster_boot(1/1) ERROR    Exception occurred while calling PrepareVm(<BaseVirtualMachine [ip=None, internal_ip=None]>):
Traceback (most recent call last):
  File "/home/ubuntu/PerfKitBenchmarker/perfkitbenchmarker/background_tasks.py", line 235, in Run
    self.return_value = self.target(*self.args, **self.kwargs)
  File "/home/ubuntu/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 405, in PrepareVm
    vm.Create()
  File "/home/ubuntu/PerfKitBenchmarker/perfkitbenchmarker/resource.py", line 160, in Create
    self._CreateDependencies()
  File "/home/ubuntu/PerfKitBenchmarker/perfkitbenchmarker/providers/kubernetes/kubernetes_virtual_machine.py", line 57, in _CreateDependencies
    self._CreateSecret()
  File "/home/ubuntu/PerfKitBenchmarker/perfkitbenchmarker/providers/kubernetes/kubernetes_virtual_machine.py", line 237, in _CreateSecret
    raise Exception("Creating secret failed: %s" % output[STDERR])
```

The "input" parameter in [kubernetes_virtual_machine.py](https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/2009a4bad90b3ede982f6ca76097c1a9ae979f58/perfkitbenchmarker/providers/kubernetes/kubernetes_virtual_machine.py#L235) is never used in the method [here](https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/2009a4bad90b3ede982f6ca76097c1a9ae979f58/perfkitbenchmarker/vm_util.py#L258-L320); hence "/home/ubuntu/kubectl --kubeconfig=/home/ubuntu/admin.conf create -f -" sits there waiting for input.

**Comment by bvliu** [comment]
Please see https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/1990.
