### ISSUE TITLE
support for running fio on AWS EC2 I3 instance type

### ISSUE THREAD

**Issue by ispringer** [GoogleCloudPlatform/PerfKitBenchmarker#1307]
Amazon recently added the new I3 instance type (https://aws.amazon.com/about-aws/whats-new/2017/02/now-available-amazon-ec2-i3-instances-next-generation-storage-optimized-high-i-o-instances/). I tried running PKB with the fio benchmark on an I3 instance as follows:

```
./pkb.py --cloud=AWS --data_disk_type=local --os_type=rhel -image=ami-0b33d91d --zones=us-east-1 --machine_type=i3.2xlarge --benchmarks=fio --fio_jobfile ~/fio.job
```

It failed with the following errors:

```
2017-03-06 15:19:53,407 c2407cb6 MainThread fio(1/1) ERROR    Exception occurred while calling PrepareVm(54.211.122.76):
Traceback (most recent call last):
  File "/Users/ips/Code/PerfKitBenchmarker/perfkitbenchmarker/background_tasks.py", line 235, in Run
    self.return_value = self.target(*self.args, **self.kwargs)
  File "/Users/ips/Code/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 400, in PrepareVm
    vm.CreateScratchDisk(disk_spec)
  File "/Users/ips/Code/PerfKitBenchmarker/perfkitbenchmarker/providers/aws/aws_virtual_machine.py", line 506, in CreateScratchDisk
    raise errors.Error('Not enough local disks.')
Error: Not enough local disks.

2017-03-06 15:19:53,411 c2407cb6 MainThread fio(1/1) ERROR    Error during benchmark fio
Traceback (most recent call last):
  File "/Users/ips/Code/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 480, in RunBenchmark
    DoProvisionPhase(spec, detailed_timer)
  File "/Users/ips/Code/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 360, in DoProvisionPhase
    spec.Provision()
  File "/Users/ips/Code/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 303, in Provision
    vm_util.RunThreaded(self.PrepareVm, self.vms)
  File "/Users/ips/Code/PerfKitBenchmarker/perfkitbenchmarker/background_tasks.py", line 621, in RunThreaded
    max_concurrency=max_concurrent_threads)
  File "/Users/ips/Code/PerfKitBenchmarker/perfkitbenchmarker/background_tasks.py", line 565, in RunParallelThreads
    errors.VmUtil.ThreadException)
  File "/Users/ips/Code/PerfKitBenchmarker/perfkitbenchmarker/background_tasks.py", line 540, in _RunParallelTasks
    '{0}{1}'.format(os.linesep, os.linesep.join(error_strings)))
ThreadException: The following exceptions occurred during parallel execution:
Exception occurred while calling PrepareVm(54.211.122.76):
Traceback (most recent call last):
  File "/Users/ips/Code/PerfKitBenchmarker/perfkitbenchmarker/background_tasks.py", line 235, in Run
    self.return_value = self.target(*self.args, **self.kwargs)
  File "/Users/ips/Code/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 400, in PrepareVm
    vm.CreateScratchDisk(disk_spec)
  File "/Users/ips/Code/PerfKitBenchmarker/perfkitbenchmarker/providers/aws/aws_virtual_machine.py", line 506, in CreateScratchDisk
    raise errors.Error('Not enough local disks.')
Error: Not enough local disks.
```

I see there is an aws-i3 branch already, but it's identical to master. Can I3 support be easily added, or is a significant effort? I am willing to help out with the work but would need some pointers on where to start.

**Comment by yuyantingzero** [comment]
i am still cleaning up my branch. Currently, running i3 with pkb have following issues:
1. i3 only works with ubuntu 1604+ (and newer images on other OS). Default image Pkb uses is 1404. 1604 is likely to fail on various benchmarks, including fio.
2. i3 uses nvme driver. All device path is similar to /dev/nvme[0-8]n1, currently pkb hardcoded aws device path.
3. Due to above reasons, some fio flag doesn't work very well.
4. pkb try to find most recent ami. Seems breaking on ubuntu1604 in some regions. I am passing in --image flag specifically during my tests.

I can push my branch. But not sure if that will work on redhat.

**Comment by yuyantingzero** [comment]
pushed i3 hacks, the error you are seeing is likely due to https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/aws-i3/perfkitbenchmarker/providers/aws/aws_virtual_machine.py#L62

**Comment by ispringer** [comment]
Thanks! I will try out your branch. I am ok with running the benchmark on Ubuntu. 

Yes, adding { 'i3.2xlarge': 1 } to NUM_LOCAL_VOLUMES got me past the "Not enough local disks." error, but then I hit this error, presumably due to the different device naming for nvme:

```
umount: /mnt: not mounted
mke2fs 1.42.12 (29-Aug-2014)
The file /dev/xvdb does not exist and no size was specified.

2017-03-06 19:41:34,378 e36d8a26 Thread-20 fio(1/1) ERROR    Got exception running FormatDisk: Got non-zero return code (1) executing [[ -d /mnt ]] && sudo umount /mnt; sudo mke2fs -F -E lazy_itable_init=0,discard -O ^has_journal -t ext4 -b 4096 /dev/xvdb
Full command: ssh -A -p 22 ec2-user@54.145.170.214 -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /var/folders/sb/x5xtldgj105dx2lqv8qvw55r0000gn/T/perfkitbenchmarker/runs/e36d8a26/perfkitbenchmarker_keyfile [[ -d /mnt ]] && sudo umount /mnt; sudo mke2fs -F -E lazy_itable_init=0,discard -O ^has_journal -t ext4 -b 4096 /dev/xvdb
```

**Comment by yuyantingzero** [comment]
--image=ami-f4cc1de2 --zones=us-east-1a
images are region specific

**Comment by yuyantingzero** [comment]
for larger instances, e.g. i3.16xlarge:
add --num_striped_disks=8

**Comment by ispringer** [comment]
Thanks for the --num_striped_disks tip.

I got it working! I used:

```
--zones=us-east-1 --os_type=debian -image=ami-e600d1f0 
```

(latest Ubuntu)
 
Any idea what the iodepth to use in fio.job for maximum performance? I'm measuring parallel random read IOPS and parallel random write IOPS. I'm currently using iodepth=64. With that, I got the following results for i3.2xlarge:

read: 290K
write: 48K

This is blazing fast, so it's hard to complain, but still it's coming in quite a bit under the 412.5K read IOPS that Amazon is advertising.

**Comment by yuyantingzero** [comment]
for random read, you will need to use numjobs in fio.job, since it is likely to be thread-bound on high iodepth.

**Comment by yuyantingzero** [comment]
https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/1308

**Comment by yuyantingzero** [comment]
closing, please reopen if necessary
