### ISSUE TITLE
blazemark benchmark needs to handle numbers in exponent format 

### ISSUE THREAD

**Issue by dlott** [GoogleCloudPlatform/PerfKitBenchmarker#1309]
Sample parse error:  see `3.03424e-08`

```
2017-03-08 08:58:10,035 9d3470a0 MainThread blazemark(1/1) ERROR    Error during benchmark blazemark
Traceback (most recent call last):
  File "/tmp/pkb-test-cRpILI/perfkitbenchmarker/pkb.py", line 486, in RunBenchmark
    DoRunPhase(spec, collector, detailed_timer)
  File "/tmp/pkb-test-cRpILI/perfkitbenchmarker/pkb.py", line 402, in DoRunPhase
    samples = spec.BenchmarkRun(spec)
  File "/tmp/pkb-test-cRpILI/perfkitbenchmarker/linux_benchmarks/blazemark_benchmark.py", line 94, in Run
    results.extend(blazemark.RunTest(vm, test))
  File "/tmp/pkb-test-cRpILI/perfkitbenchmarker/linux_packages/blazemark.py", line 187, in RunTest
    return _ParseResult(out, test)
  File "/tmp/pkb-test-cRpILI/perfkitbenchmarker/linux_packages/blazemark.py", line 153, in _ParseResult
    matches = regex_util.ExtractAllMatches(THROUGHPUT_HEADER_REGEX, out)
  File "/tmp/pkb-test-cRpILI/perfkitbenchmarker/regex_util.py", line 100, in ExtractAllMatches
    regex, text))
NoMatchError: No match for pattern "(\w+[\w\- ]+\w+)\s*(\([0-9.]+% filled\))*\s*\[([\w/]+)\]:([0-9\s.]+)" in "
 Dense Matrix Inversion:
   Blaze (Seconds):
     3           3.03424e-08
     4           5.56256e-08
     5           1.25857e-07
     6           2.84748e-07
     10          8.45703e-06
     50          0.000520367
     100         0.00447695
     500         0.504488
     1000        3.98441
     2000        31.9121
   N=3, steps=65533975
     Blaze       = 1        (1.98846)
   N=4, steps=35425014
     Blaze       = 1        (1.97054)
   N=5, steps=15941983
     Blaze       = 1        (2.00642)
   N=6, steps=7041132
     Blaze       = 1        (2.00495)
   N=10, steps=227871
     Blaze       = 1        (1.92711)
   N=50, steps=3771
     Blaze       = 1        (1.9623)
   N=100, steps=439
     Blaze       = 1        (1.96538)
   N=500, steps=3
     Blaze       = 1        (1.51346)
   N=1000, steps=1
     Blaze       = 1        (3.98441)
   N=2000, steps=1
     Blaze       = 1        (31.9121)
"
```

**Comment by yuyantingzero** [comment]
https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/1311

**Comment by dlott** [comment]
Fixed per above.
