### ISSUE TITLE
AttributeError: 'module' object has no attribute 'register_validator'

### ISSUE THREAD

**Issue by joelio** [GoogleCloudPlatform/PerfKitBenchmarker#1331]
Started failing recently, for all tests I run (fio, iperf, mongo etc)

```
Traceback (most recent call last):
  File "./pkb.py", line 19, in <module>
    from perfkitbenchmarker.pkb import Main
  File "/var/lib/jenkins/workspace/testing.perfkitbenchmarker.fio.ceph/perfkitbenchmarker/pkb.py", line 70, in <module>
    from perfkitbenchmarker import benchmark_sets
  File "/var/lib/jenkins/workspace/testing.perfkitbenchmarker.fio.ceph/perfkitbenchmarker/benchmark_sets.py", line 22, in <module>
    from perfkitbenchmarker import linux_benchmarks
  File "/var/lib/jenkins/workspace/testing.perfkitbenchmarker.fio.ceph/perfkitbenchmarker/linux_benchmarks/__init__.py", line 26, in <module>
    BENCHMARKS = _LoadBenchmarks()
  File "/var/lib/jenkins/workspace/testing.perfkitbenchmarker.fio.ceph/perfkitbenchmarker/linux_benchmarks/__init__.py", line 24, in _LoadBenchmarks
    return list(import_util.LoadModulesForPath(__path__, __name__))
  File "/var/lib/jenkins/workspace/testing.perfkitbenchmarker.fio.ceph/perfkitbenchmarker/import_util.py", line 43, in LoadModulesForPath
    yield importlib.import_module(prefix + modname)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/lib/jenkins/workspace/testing.perfkitbenchmarker.fio.ceph/perfkitbenchmarker/linux_benchmarks/netperf_benchmark.py", line 67, in <module>
    flags.register_validator(
AttributeError: 'module' object has no attribute 'register_validator'
```

**Comment by tedsta** [comment]
You need to update gflags. We switched to 3.1.1 in this PR https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/1322

Sorry about that!

**Comment by joelio** [comment]
Ah, ok, no worries, thanks for the heads up! :)

**Comment by joelio** [comment]
Fanstastic, a simple `pip install -r requirements.txt` was all it needed, Ill make sure to check that next time. Thanks again!
