### ISSUE TITLE
Cassandra_stress issue on Azure

### ISSUE THREAD

**Issue by owenrog** [GoogleCloudPlatform/PerfKitBenchmarker#148]
I've been unable to successfully complete a cassandra stress benchmark on Azure, D1 and D2 instances in US West. Traceback which caused execution to stop follows below, but have also received following errors in console output. 
1. 2015-03-05 15:55:41,682 ERROR    Got exception running _CreateResource: Creation of DebianBasedAzureVirtualMachine failed.
2. The following packages have unmet dependencies: openjdk-7-jdk : Depends: openjdk-7-jre (= 7u75-2.5.4-1~trusty1) but it is not going to be installed, Recommends: libxt-dev but it is not installable

Have also experienced similar problems running copy_throughput and hadoop (I've seen other thread related to this). I'm not a developer, so not sure if this is me making a mistake, or an issue?

Traceback (most recent call last):
  File "./pkb.py", line 21, in <module>
    sys.exit(Main())
  File "/Users/owen/Downloads/PerfKitBenchmarker-0.10.1/perfkitbenchmarker/pkb.py", line 358, in Main
    return RunBenchmarks()
  File "/Users/owen/Downloads/PerfKitBenchmarker-0.10.1/perfkitbenchmarker/pkb.py", line 324, in RunBenchmarks
    RunBenchmark(benchmark, collector)
  File "/Users/owen/Downloads/PerfKitBenchmarker-0.10.1/perfkitbenchmarker/pkb.py", line 238, in RunBenchmark
    samples = benchmark.Run(benchmark_specification)
  File "/Users/owen/Downloads/PerfKitBenchmarker-0.10.1/perfkitbenchmarker/benchmarks/cassandra_stress_benchmark.py", line 492, in Run
    RunCassandraStressTest(benchmark_spec)
  File "/Users/owen/Downloads/PerfKitBenchmarker-0.10.1/perfkitbenchmarker/benchmarks/cassandra_stress_benchmark.py", line 427, in RunCassandraStressTest
    benchmark_spec.vm_dict[LOADER_NODE])
  File "/Users/owen/Downloads/PerfKitBenchmarker-0.10.1/perfkitbenchmarker/vm_util.py", line 249, in RunThreaded
    '\n'.join([stacktrace for stacktrace in exceptions]))
perfkitbenchmarker.errors.ThreadException: The following exceptions occurred during threaded execution: Traceback (most recent call last):
  File "/Users/owen/Downloads/PerfKitBenchmarker-0.10.1/perfkitbenchmarker/vm_util.py", line 236, in RunThreaded
    thread.join(1000)  # Set timeout so that join is interruptable.
  File "/Users/owen/Downloads/PerfKitBenchmarker-0.10.1/perfkitbenchmarker/vm_util.py", line 179, in join
    raise errors.VmUtil.ThreadException(self.exception)
ThreadException: Exception occured in thread 4426715136:
Traceback (most recent call last):
  File "/Users/owen/Downloads/PerfKitBenchmarker-0.10.1/perfkitbenchmarker/vm_util.py", line 166, in run
    self.RunWithExceptions()
  File "/Users/owen/Downloads/PerfKitBenchmarker-0.10.1/perfkitbenchmarker/vm_util.py", line 173, in RunWithExceptions
    super(ThreadWithExceptions, self).run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/owen/Downloads/PerfKitBenchmarker-0.10.1/perfkitbenchmarker/benchmarks/cassandra_stress_benchmark.py", line 337, in WaitLoaderForFinishing
    % vm_util.GetTempDir())
RunError: cassandra-stress tool failed, check /tmp/perfkitbenchmarker/run_4c2d682d/ for details.

**Comment by yuyantingzero** [comment]
@owenrog , thanks for reporting the problem,
1) This is error happened before ever running cassandra-stress benchmark in resource creation stage, which might cause by timeout or not enough quota.
2) A similar issue to #82 , which occurs on some of the vms, but not all of them. Looks like something wrong with their image or resource repository, but update the image doesn't fix the problem.
3) This is due to data nodes running out of heap space or not able to process all concurrent writes. You may want to decrease num_cassandra_stress_threads or num_keys a bit. The default values are good for Default machine type A1, but might need adjusting with other machine types.

**Comment by owenrog** [comment]
Thanks @yuyantingzero, reducing threads to 25 has solved problem on Azure D1 and D2.
