### ISSUE TITLE
Running pkb.py fails due to gpu_clock_speeds flag.

### ISSUE THREAD

**Issue by lgajowy** [GoogleCloudPlatform/PerfKitBenchmarker#1572]
Encountered the following issue when running pkb.py from the latest master: 

```
Traceback (most recent call last):
  File "./perfkitbenchmarker/pkb.py", line 19, in <module>
    from perfkitbenchmarker.pkb import Main
  File "/Users/lukasz/Projects/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 73, in <module>
    from perfkitbenchmarker import benchmark_sets
  File "/Users/lukasz/Projects/PerfKitBenchmarker/perfkitbenchmarker/benchmark_sets.py", line 22, in <module>
    from perfkitbenchmarker import linux_benchmarks
  File "/Users/lukasz/Projects/PerfKitBenchmarker/perfkitbenchmarker/linux_benchmarks/__init__.py", line 26, in <module>
    BENCHMARKS = _LoadBenchmarks()
  File "/Users/lukasz/Projects/PerfKitBenchmarker/perfkitbenchmarker/linux_benchmarks/__init__.py", line 24, in _LoadBenchmarks
    return list(import_util.LoadModulesForPath(__path__, __name__))
  File "/Users/lukasz/Projects/PerfKitBenchmarker/perfkitbenchmarker/import_util.py", line 43, in LoadModulesForPath
    yield importlib.import_module(prefix + modname)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/lukasz/Projects/PerfKitBenchmarker/perfkitbenchmarker/linux_benchmarks/aerospike_benchmark.py", line 32, in <module>
    from perfkitbenchmarker.linux_packages import aerospike_server
  File "/Users/lukasz/Projects/PerfKitBenchmarker/perfkitbenchmarker/linux_packages/__init__.py", line 53, in <module>
    PACKAGES = _LoadPackages()
  File "/Users/lukasz/Projects/PerfKitBenchmarker/perfkitbenchmarker/linux_packages/__init__.py", line 48, in _LoadPackages
    import_util.LoadModulesForPath(__path__, __name__)])
  File "/Users/lukasz/Projects/PerfKitBenchmarker/perfkitbenchmarker/import_util.py", line 43, in LoadModulesForPath
    yield importlib.import_module(prefix + modname)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/lukasz/Projects/PerfKitBenchmarker/perfkitbenchmarker/linux_packages/cuda_toolkit_8.py", line 55, in <module>
  File "/Users/lukasz/Projects/PerfKitBenchmarker/perfkitbenchmarker/flag_util.py", line 223, in DEFINE_integerlist
    flags.DEFINE(parser, name, default, help, flag_values, serializer, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/absl/flags/_defines.py", line 82, in DEFINE
    flag_values, module_name)
  File "/usr/local/lib/python2.7/site-packages/absl/flags/_defines.py", line 104, in DEFINE_flag
    fv[flag.name] = flag
  File "/usr/local/lib/python2.7/site-packages/absl/flags/_flagvalues.py", line 428, in __setitem__
    raise _exceptions.DuplicateFlagError.from_flag(name, self)
absl.flags._exceptions.DuplicateFlagError: The flag 'gpu_clock_speeds' is defined twice. First from perfkitbenchmarker.flag_util, Second from perfkitbenchmarker.flag_util.  Description from first occurrence: desired gpu clock speeds in the form [memory clock, graphics clock]
```

Steps to reproduce:
- Run pkb.py in the project directory: `./pkb.py` (with or without flags/arguments)

**Comment by lgajowy** [comment]
Deleting all `*.pyc` files form `perfkitbenchmarker` directory resolved the issue but I am not sure if this is the right solution in this case.

**Comment by dlott** [comment]
I think it's because the file containing that flag was renamed (see https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/commit/c5f95c28852d4be2f1035872bf682aef60963c95#diff-3e29c3220173367c53234c8d27be75c6).  Deleting the old .pyc file is an appropriate solution in this case.  Please re-open this issue if the problem persists.
