### ISSUE TITLE
RetryableDeletionError: Deletion of AwsManagedRelationalDb failed

### ISSUE THREAD

**Issue by todywang** [GoogleCloudPlatform/PerfKitBenchmarker#1620]
When i run "sysbench"benchmark,  the test failed

Traceback (most recent call last):
  File "/home/ec2-user/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 758, in RunBenchmarkTask
    RunBenchmark(spec, collector)
  File "/home/ec2-user/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 676, in RunBenchmark
    spec.Delete()
  File "/home/ec2-user/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 455, in Delete
    self.managed_relational_db.Delete()
  File "/home/ec2-user/PerfKitBenchmarker/perfkitbenchmarker/resource.py", line 249, in Delete
    self._DeleteResource()
  File "/home/ec2-user/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 249, in WrappedFunction
    return f(*args, **kwargs)
  File "/home/ec2-user/PerfKitBenchmarker/perfkitbenchmarker/resource.py", line 211, in _DeleteResource
    'Deletion of %s failed.' % type(self).__name__)
RetryableDeletionError: Deletion of AwsManagedRelationalDb failed.

**Comment by todywang** [comment]
run command " ./pkb.py --cloud=AWS --benchmarks="sysbench"  --zones=us-west-1c  --os_type=rhel  --machine_type=m5.xlarge  --es_uri=es_uri"
