### ISSUE TITLE
os type is not found

### ISSUE THREAD

**Issue by liyjperfkit** [GoogleCloudPlatform/PerfKitBenchmarker#165]
HI:
   I have a machine that the os type is centos 6.6,but it's  WARNING when ./pkb.py --benchmarks=fio  --static_vm_file=test.json  --ip_addresses=EXTERNAL.Please tell me how to set the parameter of os type,thanks!!
following:
2015-03-12 18:14:14,449 INFO     Verbose logging to: /tmp/perfkitbenchmarker/run_1729c44d/pkb.log
2015-03-12 18:14:14,506 WARNING  Could not find os type for VM. Defaulting to debian.
2015-03-12 18:14:14,507 INFO     Preparing benchmark fio
2015-03-12 18:14:14,508 INFO     VM: 192.168.11.64
2015-03-12 18:14:14,508 INFO     Waiting for boot completion.
2015-03-12 18:14:14,508 INFO     Running: /usr/bin/ssh -A -p 22 root@192.168.11.64 -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /root/.ssh/authorized_keys hostname

**Comment by akrzos** [comment]
Make sure you specify the os_type in the static json file.

Add ```"os_type": "rhel"``` to your json file.

**Comment by voellm** [comment]
All set?  Can we close this issue?

**Comment by liyjperfkit** [comment]
this is my json file, the following:
[
 {"ip_address": "192.168.11.64",
  "user_name": "root",
  "keyfile_path": "/root/.ssh/authorized_keys",
  "zone": "liyj"
  "os_type": "rhel"}
]
It's error when ./pkb.py --benchmarks=ping  --static_vm_file=test.json  --ip_addresses=EXTERNAL,the following:
[root@compute PerfKitBenchmarker-0.11.1]# ./pkb.py --benchmarks=ping  --static_vm_file=test.json  --ip_addresses=EXTERNAL
2015-03-13 09:52:28,349 INFO     Verbose logging to: /tmp/perfkitbenchmarker/run_8bcaf6ec/pkb.log
Traceback (most recent call last):
  File "./pkb.py", line 21, in <module>
    sys.exit(Main())
  File "/root/PerfKitBenchmarker-0.11.1/perfkitbenchmarker/pkb.py", line 358, in Main
    return RunBenchmarks()
  File "/root/PerfKitBenchmarker-0.11.1/perfkitbenchmarker/pkb.py", line 305, in RunBenchmarks
    fp)
  File "/root/PerfKitBenchmarker-0.11.1/perfkitbenchmarker/static_virtual_machine.py", line 125, in ReadStaticVirtualMachineFile
    vm_arr = json.load(file_obj)
  File "/usr/lib64/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 381, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 6 column 3 (char 125)

**Comment by voellm** [comment]
you are missing a comma on the second to last row.

**Comment by liyjperfkit** [comment]
OK ,thank you very much
