### ISSUE TITLE
object_storage_service benchmark fails on AWS due to "which gsutil" returning non-zero

### ISSUE THREAD

**Issue by lyoungblood** [GoogleCloudPlatform/PerfKitBenchmarker#1672]
### How to reproduce

Execute the following command with v1.13.0 of PerfKitBenchmarker:

```./pkb.py --cloud=AWS --zones=us-west-2a --benchmarks=object_storage_service --machine_type=c5.18xlarge```

### What happens

Receive the following error output:
```
2018-05-04 01:14:55,737 5661e0c3 Thread-46 object_storage_service(1/1) INFO     Ran ssh -A -p 22 ubuntu@54.186.54.108 -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /tmp/perfkitbenchmarker/runs/5661e0c3/perfkitbenchmarker_keyfile -t -t bash -l -c "which gsutil". Got return code (1).
STDOUT: 
STDERR: Warning: Permanently added '54.186.54.108' (ECDSA) to the list of known hosts.
Connection to 54.186.54.108 closed.

2018-05-04 01:14:55,754 5661e0c3 MainThread object_storage_service(1/1) ERROR    Exception occurred while calling <lambda>(54.186.54.108):
Traceback (most recent call last):
  File "/home/ubuntu/PerfKitBenchmarker-1.13.0/perfkitbenchmarker/background_tasks.py", line 235, in Run
    self.return_value = self.target(*self.args, **self.kwargs)
  File "/home/ubuntu/PerfKitBenchmarker-1.13.0/perfkitbenchmarker/linux_benchmarks/object_storage_service_benchmark.py", line 1265, in <lambda>
    vm_util.RunThreaded(lambda vm: PrepareVM(vm, service), vms)
  File "/home/ubuntu/PerfKitBenchmarker-1.13.0/perfkitbenchmarker/linux_benchmarks/object_storage_service_benchmark.py", line 1211, in PrepareVM
    service.PrepareVM(vm)
  File "/home/ubuntu/PerfKitBenchmarker-1.13.0/perfkitbenchmarker/providers/gcp/gcs.py", line 103, in PrepareVM
    vm.gsutil_path, _ = vm.RemoteCommand('which gsutil', login_shell=True)
  File "/home/ubuntu/PerfKitBenchmarker-1.13.0/perfkitbenchmarker/linux_virtual_machine.py", line 454, in RemoteCommand
    suppress_warning, timeout)[:2]
  File "/home/ubuntu/PerfKitBenchmarker-1.13.0/perfkitbenchmarker/linux_virtual_machine.py", line 445, in RemoteCommandWithReturnCode
    suppress_warning, timeout)
  File "/home/ubuntu/PerfKitBenchmarker-1.13.0/perfkitbenchmarker/linux_virtual_machine.py", line 516, in RemoteHostCommandWithReturnCode
    raise errors.VirtualMachine.RemoteCommandError(error_text)
RemoteCommandError: Got non-zero return code (1) executing which gsutil
Full command: ssh -A -p 22 ubuntu@54.186.54.108 -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /tmp/perfkitbenchmarker/runs/5661e0c3/perfkitbenchmarker_keyfile -t -t bash -l -c "which gsutil"
STDOUT: STDERR: Warning: Permanently added '54.186.54.108' (ECDSA) to the list of known hosts.
Connection to 54.186.54.108 closed.


2018-05-04 01:14:55,755 5661e0c3 MainThread object_storage_service(1/1) ERROR    Error during benchmark object_storage_service
Traceback (most recent call last):
  File "/home/ubuntu/PerfKitBenchmarker-1.13.0/perfkitbenchmarker/pkb.py", line 555, in RunBenchmark
    DoPreparePhase(spec, detailed_timer)
  File "/home/ubuntu/PerfKitBenchmarker-1.13.0/perfkitbenchmarker/pkb.py", line 450, in DoPreparePhase
    spec.BenchmarkPrepare(spec)
  File "/home/ubuntu/PerfKitBenchmarker-1.13.0/perfkitbenchmarker/linux_benchmarks/object_storage_service_benchmark.py", line 1265, in Prepare
    vm_util.RunThreaded(lambda vm: PrepareVM(vm, service), vms)
  File "/home/ubuntu/PerfKitBenchmarker-1.13.0/perfkitbenchmarker/background_tasks.py", line 621, in RunThreaded
    max_concurrency=max_concurrent_threads)
  File "/home/ubuntu/PerfKitBenchmarker-1.13.0/perfkitbenchmarker/background_tasks.py", line 565, in RunParallelThreads
    errors.VmUtil.ThreadException)
  File "/home/ubuntu/PerfKitBenchmarker-1.13.0/perfkitbenchmarker/background_tasks.py", line 540, in _RunParallelTasks
    '{0}{1}'.format(os.linesep, os.linesep.join(error_strings)))
ThreadException: The following exceptions occurred during parallel execution:
Exception occurred while calling <lambda>(54.186.54.108):
Traceback (most recent call last):
  File "/home/ubuntu/PerfKitBenchmarker-1.13.0/perfkitbenchmarker/background_tasks.py", line 235, in Run
    self.return_value = self.target(*self.args, **self.kwargs)
  File "/home/ubuntu/PerfKitBenchmarker-1.13.0/perfkitbenchmarker/linux_benchmarks/object_storage_service_benchmark.py", line 1265, in <lambda>
    vm_util.RunThreaded(lambda vm: PrepareVM(vm, service), vms)
  File "/home/ubuntu/PerfKitBenchmarker-1.13.0/perfkitbenchmarker/linux_benchmarks/object_storage_service_benchmark.py", line 1211, in PrepareVM
    service.PrepareVM(vm)
  File "/home/ubuntu/PerfKitBenchmarker-1.13.0/perfkitbenchmarker/providers/gcp/gcs.py", line 103, in PrepareVM
    vm.gsutil_path, _ = vm.RemoteCommand('which gsutil', login_shell=True)
  File "/home/ubuntu/PerfKitBenchmarker-1.13.0/perfkitbenchmarker/linux_virtual_machine.py", line 454, in RemoteCommand
    suppress_warning, timeout)[:2]
  File "/home/ubuntu/PerfKitBenchmarker-1.13.0/perfkitbenchmarker/linux_virtual_machine.py", line 445, in RemoteCommandWithReturnCode
    suppress_warning, timeout)
  File "/home/ubuntu/PerfKitBenchmarker-1.13.0/perfkitbenchmarker/linux_virtual_machine.py", line 516, in RemoteHostCommandWithReturnCode
    raise errors.VirtualMachine.RemoteCommandError(error_text)
RemoteCommandError: Got non-zero return code (1) executing which gsutil
Full command: ssh -A -p 22 ubuntu@54.186.54.108 -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /tmp/perfkitbenchmarker/runs/5661e0c3/perfkitbenchmarker_keyfile -t -t bash -l -c "which gsutil"
STDOUT: STDERR: Warning: Permanently added '54.186.54.108' (ECDSA) to the list of known hosts.
Connection to 54.186.54.108 closed.
```

### What was expected to happen

I expected the benchmark to complete successfully.

**Comment by cwilkes** [comment]
Thanks for reporting this error!

Currently the --storage flag:
 https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/master/perfkitbenchmarker/linux_benchmarks/object_storage_service_benchmark.py#L58
defaults to "GCP" 

This means that if you only specify a cloud, ie --cloud AWS, you will inadvertently try to use GCS instead of S3.

The fix is for the cloud to not have a default for this and set it to the --cloud value if none is set.

For now can you try passing in "--storage AWS" and see if that works?

**Comment by dlott** [comment]
Glad this worked.  Please reopen if you have further issues.
