### ISSUE TITLE
getting new intermittent connection timed out errors with AWS cloud

### ISSUE THREAD

**Issue by flint-dominic** [GoogleCloudPlatform/PerfKitBenchmarker#1684]
STDERR: 
2018-05-15 10:27:30,568 6d120d50 MainThread aws_dynamodb_ycsb(1/1) pkb.py:791 ERROR    Exception running benchmark
Traceback (most recent call last):
  File "/usr/local/google/home/flint/Documents/test/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 789, in RunBenchmarkTask
    RunBenchmark(spec, collector)
  File "/usr/local/google/home/flint/Documents/test/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 651, in RunBenchmark
    DoPreparePhase(spec, detailed_timer)
  File "/usr/local/google/home/flint/Documents/test/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 501, in DoPreparePhase
    spec.BenchmarkPrepare(spec)
  File "/usr/local/google/home/flint/Documents/test/PerfKitBenchmarker/perfkitbenchmarker/linux_benchmarks/aws_dynamodb_ycsb_benchmark.py", line 111, in Prepare
    vm_util.RunThreaded(_Install, vms)
  File "/usr/local/google/home/flint/Documents/test/PerfKitBenchmarker/perfkitbenchmarker/background_tasks.py", line 624, in RunThreaded
    max_concurrency=max_concurrent_threads)
  File "/usr/local/google/home/flint/Documents/test/PerfKitBenchmarker/perfkitbenchmarker/background_tasks.py", line 568, in RunParallelThreads
    errors.VmUtil.ThreadException)
  File "/usr/local/google/home/flint/Documents/test/PerfKitBenchmarker/perfkitbenchmarker/background_tasks.py", line 543, in _RunParallelTasks
    '{0}{1}'.format(os.linesep, os.linesep.join(error_strings)))
ThreadException: The following exceptions occurred during parallel execution:
Exception occurred while calling _Install(34.238.176.217):
Traceback (most recent call last):
  File "/usr/local/google/home/flint/Documents/test/PerfKitBenchmarker/perfkitbenchmarker/background_tasks.py", line 235, in Run
    self.return_value = self.target(*self.args, **self.kwargs)
  File "/usr/local/google/home/flint/Documents/test/PerfKitBenchmarker/perfkitbenchmarker/linux_benchmarks/aws_dynamodb_ycsb_benchmark.py", line 153, in _Install
    vm.RemoteCopy(FLAGS.aws_dynamodb_ycsb_awscredentials_properties, AWS_CREDENTIAL_DIR)
  File "/usr/local/google/home/flint/Documents/test/PerfKitBenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 509, in RemoteCopy
    self.RemoteHostCopy(file_path, remote_path, copy_to)
  File "/usr/local/google/home/flint/Documents/test/PerfKitBenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 547, in RemoteHostCopy
    raise errors.VirtualMachine.RemoteCommandError(error_text)
RemoteCommandError: Got non-zero return code (1) executing scp -P 22 -pr -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=30 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /tmp/perfkitbenchmarker/runs/6d120d50/perfkitbenchmarker_keyfile ./AWSCredentials.properties ubuntu@34.238.176.217:/tmp/AWSCredentials.properties
STDOUT: STDERR: ssh: connect to host 34.238.176.217 port 22: Connection timed out
lost connection

This was working before fine, something change on AWS side?

**Comment by flint-dominic** [comment]
this may being caused by connection issues with github from aws trying to download ycsb.

**Comment by flint-dominic** [comment]
looks like this isn't a pkb issue, but a aws/github connection issue, ill close it.
