### ISSUE TITLE
ERROR in my first run of ./pkb.py

### ISSUE THREAD

**Issue by elham1296** [GoogleCloudPlatform/PerfKitBenchmarker#185]
Hi,
I want to start work with pkb and when  I want to run these commands:
./pkb.py --project=dev-entropy-88718 --benchmarks=iperf
./pkb.py --project=dev-entropy-88718 --benchmarks=iperf --machine_type=f1-micro
, the bellow errors occur. Please help me to solve this problem. 
Thanks,
Elham 

------------------------------------------
1 of 5,729
 
run1
Inbox
	x
Hojati, Elham
	
8:30 PM (5 minutes ago)
		
to me
./pkb.py --project=dev-entropy-88718 --benchmarks=iperf

eli@kali:~$ cd PerfKitBenchmarker-0.11.1/
eli@kali:~/PerfKitBenchmarker-0.11.1$ $ ./pkb.py --project=dev-entropy-88718 --benchmarks=iperf
bash: $: command not found
eli@kali:~/PerfKitBenchmarker-0.11.1$  ./pkb.py --project=dev-entropy-88718 --benchmarks=iperf
2015-03-22 20:25:10,101 INFO     Verbose logging to: /tmp/perfkitbenchmarker/run_11207935/pkb.log
2015-03-22 20:25:10,236 INFO     Preparing benchmark iperf
2015-03-22 20:25:10,244 INFO     Running: gcloud compute disks create perfkit-11207935-1 --size 10 --type pd-standard --project dev-entropy-88718 --format json --quiet --zone us-central1-a --image ubuntu-14-04
2015-03-22 20:25:10,259 INFO     Running: gcloud compute disks create perfkit-11207935-0 --size 10 --type pd-standard --project dev-entropy-88718 --format json --quiet --zone us-central1-a --image ubuntu-14-04
2015-03-22 20:25:14,096 INFO     Running: gcloud compute disks describe perfkit-11207935-1 --project dev-entropy-88718 --format json --quiet --zone us-central1-a
2015-03-22 20:25:14,181 INFO     Running: gcloud compute disks describe perfkit-11207935-0 --project dev-entropy-88718 --format json --quiet --zone us-central1-a
2015-03-22 20:25:17,347 ERROR    Got exception running _CreateResource: Creation of GceDisk failed.
2015-03-22 20:25:17,565 ERROR    Got exception running _CreateResource: Creation of GceDisk failed.
2015-03-22 20:25:44,198 INFO     Running: gcloud compute disks create perfkit-11207935-0 --size 10 --type pd-standard --project dev-entropy-88718 --format json --quiet --zone us-central1-a --image ubuntu-14-04
2015-03-22 20:25:45,639 INFO     Running: gcloud compute disks create perfkit-11207935-1 --size 10 --type pd-standard --project dev-entropy-88718 --format json --quiet --zone us-central1-a --image ubuntu-14-04
2015-03-22 20:25:47,358 INFO     Running: gcloud compute disks describe perfkit-11207935-0 --project dev-entropy-88718 --format json --quiet --zone us-central1-a
2015-03-22 20:25:49,111 INFO     Running: gcloud compute disks describe perfkit-11207935-1 
2015-03-22 20:29:50,315 INFO     Running: gcloud compute disks create perfkit-11207935-0 --size 10 --type pd-standard --project dev-entropy-88718 --format json --quiet --zone us-central1-a --image ubuntu-14-04
2015-03-22 20:29:53,637 INFO     Running: gcloud compute disks describe perfkit-11207935-0 --project dev-entropy-88718 --format json --quiet --zone us-central1-a
2015-03-22 20:29:56,221 ERROR    Got exception running _CreateResource: Creation of GceDisk failed.
^CTraceback (most recent call last):
  File "./pkb.py", line 21, in <module>
    sys.exit(Main())
  File "/home/eli/PerfKitBenchmarker-0.11.1/perfkitbenchmarker/pkb.py", line 358, in Main
    return RunBenchmarks()
  File "/home/eli/PerfKitBenchmarker-0.11.1/perfkitbenchmarker/pkb.py", line 324, in RunBenchmarks
    RunBenchmark(benchmark, collector)
  File "/home/eli/PerfKitBenchmarker-0.11.1/perfkitbenchmarker/pkb.py", line 228, in RunBenchmark
    benchmark_specification.Prepare()
  File "/home/eli/PerfKitBenchmarker-0.11.1/perfkitbenchmarker/benchmark_spec.py", line 189, in Prepare
    vm_util.RunThreaded(self.PrepareVm, prepare_args)
  File "/home/eli/PerfKitBenchmarker-0.11.1/perfkitbenchmarker/vm_util.py", line 236, in RunThreaded
    thread.join(1000)  # Set timeout so that join is interruptable.
  File "/home/eli/PerfKitBenchmarker-0.11.1/perfkitbenchmarker/vm_util.py", line 177, in join
    super(ThreadWithExceptions, self).join(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 679, in join
    self.__block.wait(delay)
  File "/usr/lib/python2.7/threading.py", line 263, in wait
    _sleep(delay)
KeyboardInterrupt
eli@kali:~/PerfKitBenchmarker-0.11.1$ ^C

**Comment by voellm** [comment]
The failure is on running the first command.

There could be a couple of causes...

Try to run gcloud to make sure it is working first.

$ gcloud compute --project=dev-entropy-8871 instances list

The other issue is you could be out of quota.

  Tony

**Comment by elham1296** [comment]
dear Voellm,
I run gcloud compute --project=dev-entropy-88718 instances list, and this is its error: 

li@kali:~$ gcloud compute --project=dev-entropy-88718 instances list
NAME ZONE MACHINE_TYPE INTERNAL_IP EXTERNAL_IP STATUS
ERROR: (gcloud.compute.instances.list) Some requests did not succeed:
 - The resource 'projects/dev-entropy-88718/global/instances' was not found

Please let me know how I can solve it.
Thanks

**Comment by voellm** [comment]
Very likely you have to run "gcloud config auth"

If you have more than one @gmail or Google domain account double check you
are using the right one.

**Comment by voellm** [comment]
Is your issue resolved?  Ok to close?

**Comment by elham1296** [comment]
Hi Voellm,
Excuse me for bothering you again,
I run gcloud auth again and there is no other gmail account. 
still I have this error:
global.compute.instances list
global/instances was not found
Would you please let me know how I can check global instance of the project
Thanks,
Eli

**Comment by voellm** [comment]
What version of gcloud do you have? Also do you have billing enabled on the
project?
Perhaps use http://cloud.google.com to look at it.

**Comment by elham1296** [comment]
google Cloud SDK 0.9.52
and also billing enabled on the project.
maybe it`s related to the content of the project.
Would you please check it for me:
--------------------------------------------
eli@kali:~$ cd dev-entropy-88718/
eli@kali:~/dev-entropy-88718$ ls
default  PerfKitExplorer
eli@kali:~/dev-entropy-88718$ ls default/
app.yaml  CONTRIB.md  favicon.ico  LICENSE  main.py  README.md
eli@kali:~/dev-entropy-88718$ ls PerfKitExplorer/
appengine_config.py  compile.sh    gulpfile.js  node_modules  setup.cfg
app.yaml             config        index.yaml   out           test
bin                  CONTRIBUTING  __init__.py  package.json  third_party
client               data          lib          README.md
compile.cmd          deploy        LICENSE      server
eli@kali:~/dev-entropy-88718$ 
--------------------------------------------
I want to make sure that having both defults and PerfKitExplorer folders in my project folder is not wrong.
Thanks for your attention.

**Comment by voellm** [comment]
When you go to http://cloud.google.com/console do you see your project
listed?

Are you using the Project ID in the second column as the --project=
parameter?

There is a difference between project name, project id, and project number.

**Comment by meteorfox** [comment]
@elham1296 You are probably using the right value already. But make sure you are passing the **project-id**, and not the project name. Confirm that 'dev-entropy-88718' is your project-id. I had a similar issue a while back, and it was because of this.

Here's how that looks, project ID is the second column (e.g. mine says praxis-deck-796), when you go to http://cloud.google.com/console

![screenshot from 2015-03-26 19 06 03](https://cloud.githubusercontent.com/assets/232300/6859788/339800de-d3eb-11e4-9154-1541a0bf205f.png)

**Comment by voellm** [comment]
We have FIXED a ton of issue since this was reported.  We hope you like all the improvements.
