### ISSUE TITLE
RemoteCommandError: Got non-zero return code (255) executing hostname

### ISSUE THREAD

**Issue by nikhilsap** [GoogleCloudPlatform/PerfKitBenchmarker#1880]
Hello,

I am trying to run fio on AWS using perfkit benchmarker using the command:

`./pkb.py --cloud=AWS --benchmarks=fio --machine_type=m4.xlarge --data_disk_type=gp2  --zones=eu-central-1`

That generates an error:

`RemoteCommandError: Got non-zero return code (255) executing hostname
Full command: ssh -A -p 22 ubuntu@18.204.56.184 -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /var/folders/gz/hbmv14pn5_q6tv8scqvj10fr0000gp/T/perfkitbenchmarker/runs/c7a0d238/perfkitbenchmarker_keyfile -o ControlPath="/var/folders/gz/hbmv14pn5_q6tv8scqvj10fr0000gp/T/perfkitbenchmarker/runs/c7a0d238/ssh/%C" -o ControlMaster=auto -o ControlPersist=10m hostname
STDOUT: STDERR: ControlPath too long ('/var/folders/gz/hbmv14pn5_q6tv8scqvj10fr0000gp/T/perfkitbenchmarker/runs/c7a0d238/ssh/54fe57a3b140329fb46e97c8f9a3fb0991e068f2' >= 104 bytes)`

I tried running with `--data_disk_type=io1` also, but faced the same error. 

Appreciate your help.

**Comment by HarpPDX** [comment]
-- STDOUT: STDERR: ControlPath too long 

I ran into this issue recently on my MacBook Pro. The problem was that my TMPDIR path was too long.

Try:  $ TMPDIR=/tmp; ./pkb.py ........
Or:   $ export TMPDIR=/tmp
        $ ./pkb.py ....

**Comment by yuyantingzero** [comment]
The other option is --ssh_reuse_connections=False
The change is committed recently to speed up ssh connections.

**Comment by nikhilsap** [comment]
Creating TMPDIR resolved that error. But facing different error now.

`he file /dev/xvdba does not exist and no size was specified`

> RemoteCommandError: Got non-zero return code (1) executing sudo pip install -U pip
> Full command: ssh -A -p 22 ubuntu@3.122.240.238 -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /tmp/perfkitbenchmarker/runs/b626001a/perfkitbenchmarker_keyfile sudo pip install -U pip
> STDOUT: STDERR: Warning: Permanently added '3.122.240.238' (ECDSA) to the list of known hosts.
> Traceback (most recent call last):
>   File "/usr/bin/pip", line 11, in <module>
>     sys.exit(main())
>   File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 215, in main
>     locale.setlocale(locale.LC_ALL, '')
>   File "/usr/lib/python2.7/locale.py", line 581, in setlocale
>     return _setlocale(category, locale)
> locale.Error: unsupported locale setting

**Comment by HarpPDX** [comment]
-- The file /dev/xvdba does not exist and no size was specified
This is normal...usually takes a couple retries before the disk is attached and able to be mounted and formatted.

-- locale.Error: unsupported locale setting
I've never run into this specific problem.  I ran the command that you presented in the first post. I do not get this error, but do get others about 'apt-get update' timing out. Eventually it succeeded after several retries and continued. The benchmark (fio) completed successfully.

I recommend you try again...possibly in a different region. There seems to be issues with eu-central-1...maybe try us-east-1.

**Comment by ladychili** [comment]
> The other option is --ssh_reuse_connections=False
> The change is committed recently to speed up ssh connections.

I just ran into the same issue, and adding flag `--ssh_reuse_connections=False` sorted it out.

**Comment by s-deitz** [comment]
Any updates on this issue? If you can include the start of the PKB log that may help as well.
