### ISSUE TITLE
LocalMachine/DC test failing

### ISSUE THREAD

**Issue by omps** [GoogleCloudPlatform/PerfKitBenchmarker#1898]
I am runnning perfkit benchmark or a local virtual machines, While trying to run the perfkit on a rhel host, i am getting the below error, this looks like despite providing the os_type this is still failing to the debian and trying to install packages using debian, any help or like to the rhel code would be highly appreciated. I can help fix and submit the PR.

```
[PerfKitBenchmarker]$ ./pkb.py --benchmarks=iperf --static_vm_file=testhost.json --os_type=RHEL
WARNING: Logging before flag parsing goes to stderr.
E0422 14:35:42.054932 140334663776064 pkb.py:396] flag --os_type=RHEL: value should be one of <centos7|debian|debian9|juju|rhel|ubuntu_conta
iner|ubuntu1404|ubuntu1604|ubuntu1604_cuda9|ubuntu1710|ubuntu1804|windows|windows2012|windows2016|windows2019>
[PerfKitBenchmarker]$ ./pkb.py --benchmarks=iperf --static_vm_file=testhost.json --os_type=rhel
2019-04-22 14:36:07,744 055a1864 MainThread INFO     Verbose logging to: /tmp/perfkitbenchmarker/runs/055a1864/pkb.log
2019-04-22 14:36:07,744 055a1864 MainThread INFO     PerfKitBenchmarker version: v1.12.0-1118-g4943783
2019-04-22 14:36:07,745 055a1864 MainThread INFO     Flag values:
--os_type=rhel
--static_vm_file=testhost.json
--benchmarks=iperf
2019-04-22 14:36:08,131 055a1864 MainThread WARNING  Could not find os type for VM. Defaulting to debian.
2019-04-22 14:36:08,132 055a1864 MainThread INFO     Setting --max_concurrent_threads=200.
2019-04-22 14:36:08,166 055a1864 MainThread WARNING  The key "flags" was not in the default config, but was in user overrides. This may indi
cate a typo.
2019-04-22 14:36:08,174 055a1864 MainThread iperf(1/1) INFO     Provisioning resources for benchmark iperf
2019-04-22 14:36:08,174 055a1864 MainThread iperf(1/1) INFO     Running: gcloud config list --format=json
2019-04-22 14:36:08,179 055a1864 MainThread iperf(1/1) ERROR    Error during benchmark iperf
Traceback (most recent call last):
  File "/home/usero/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 752, in RunBenchmark

2019-04-22 14:36:08,179 055a1864 MainThread iperf(1/1) ERROR    Error during benchmark iperf
Traceback (most recent call last):
  File "/home/usero/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 752, in RunBenchmark
    DoProvisionPhase(spec, detailed_timer)
  File "/home/usero/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 540, in DoProvisionPhase
    spec.ConstructVirtualMachines()
  File "/home/usero/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 408, in ConstructVirtualMachines
    vms = self.ConstructVirtualMachineGroup(group_name, group_spec)
  File "/home/usero/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 347, in ConstructVirtualMachineGroup
    vm = self._CreateVirtualMachine(group_spec.vm_spec, os_type, cloud)
  File "/home/usero/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 666, in _CreateVirtualMachine
    return vm_class(vm_spec)
  File "/home/usero/PerfKitBenchmarker/perfkitbenchmarker/providers/gcp/gce_virtual_machine.py", line 781, in __init__
    super(RhelBasedGceVirtualMachine, self).__init__(vm_spec)
  File "/home/usero/PerfKitBenchmarker/perfkitbenchmarker/providers/gcp/gce_virtual_machine.py", line 371, in __init__
    self.project = vm_spec.project or util.GetDefaultProject()
  File "/home/usero/.local/lib/python2.7/site-packages/functools32/functools32.py", line 400, in wrapper
    result = user_function(*args, **kwds)
  File "/home/usero/PerfKitBenchmarker/perfkitbenchmarker/providers/gcp/util.py", line 39, in GetDefaultProject
    stdout, _, _ = vm_util.IssueCommand(cmd)
  File "/home/usero/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 352, in IssueCommand
    stderr=tf_err, cwd=cwd)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
2019-04-22 14:36:08,182 055a1864 Thread-1 iperf(1/1) INFO     Running: ssh -A -p 22 root@hostname -2 -o UserKnownHostsFile=/dev/null -
o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o G
SSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /home/usero/.ssh/id_dsa -o ControlPath="/tmp/perfkitbenchmark
er/runs/055a1864/ssh/%C" -o ControlMaster=auto -o ControlPersist=30m sudo dpkg --clear-selections
2019-04-22 14:36:08,482 055a1864 Thread-1 iperf(1/1) INFO     Ran: {ssh -A -p 22 root@hostname -2 -o UserKnownHostsFile=/dev/null -o S
trictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSA
PIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /home/usero/.ssh/id_dsa -o ControlPath="/tmp/perfkitbenchmarker/
runs/055a1864/ssh/%C" -o ControlMaster=auto -o ControlPersist=30m sudo dpkg --clear-selections}  ReturnCode:1
STDOUT:
STDERR: Warning: Permanently added 'hostname' (RSA) to the list of known hosts.
sudo: dpkg: command not found


2019-04-22 14:36:08,497 055a1864 MainThread iperf(1/1) ERROR    Exception occurred while calling DeleteVm(hostname):
Traceback (most recent call last):
  File "/home/usero/PerfKitBenchmarker/perfkitbenchmarker/background_tasks.py", line 255, in Run
    self.return_value = self.target(*self.args, **self.kwargs)
  File "/home/usero/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 732, in DeleteVm
    vm.PackageCleanup()
  File "/home/usero/PerfKitBenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 492, in PackageCleanup
    self.RestorePackages()
  File "/home/usero/PerfKitBenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 1173, in RestorePackages
    self.RemoteCommand('sudo dpkg --clear-selections')
  File "/home/usero/PerfKitBenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 617, in RemoteCommand
    return self.RemoteCommandWithReturnCode(*args, **kwargs)[:2]
  File "/home/usero/PerfKitBenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 633, in RemoteCommandWithReturnCode
    return self.RemoteHostCommandWithReturnCode(*args, **kwargs)
  File "/home/usero/PerfKitBenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 702, in RemoteHostCommandWithReturnCode
    raise errors.VirtualMachine.RemoteCommandError(error_text)
RemoteCommandError: Got non-zero return code (1) executing sudo dpkg --clear-selections
Full command: ssh -A -p 22 root@hostname -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o Prefe
rredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o Serve
rAliveCountMax=10 -i /home/usero/.ssh/id_dsa -o ControlPath="/tmp/perfkitbenchmarker/runs/055a1864/ssh/%C" -o ControlMaster=auto -o Control
Persist=30m sudo dpkg --clear-selections
STDOUT: STDERR: Warning: Permanently added 'hostname' (RSA) to the list of known hosts.
sudo: dpkg: command not found

2019-04-22 14:36:08,498 055a1864 MainThread iperf(1/1) ERROR    Got an exception deleting VMs. Attempting to continue tearing down.
Traceback (most recent call last):
  File "/home/usero/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 576, in Delete
    vm_util.RunThreaded(self.DeleteVm, self.vms)
  File "/home/usero/PerfKitBenchmarker/perfkitbenchmarker/background_tasks.py", line 647, in RunThreaded
    max_concurrency=max_concurrent_threads)
  File "/home/usero/PerfKitBenchmarker/perfkitbenchmarker/background_tasks.py", line 587, in RunParallelThreads
    errors.VmUtil.ThreadException, post_task_delay)
  File "/home/usero/PerfKitBenchmarker/perfkitbenchmarker/background_tasks.py", line 561, in _RunParallelTasks
    '{0}{1}'.format(os.linesep, os.linesep.join(error_strings)))
ThreadException: The following exceptions occurred during parallel execution:
Exception occurred while calling DeleteVm(hostname):
Traceback (most recent call last):
  File "/home/usero/PerfKitBenchmarker/perfkitbenchmarker/background_tasks.py", line 255, in Run
    self.return_value = self.target(*self.args, **self.kwargs)
  File "/home/usero/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 732, in DeleteVm
    vm.PackageCleanup()
  File "/home/usero/PerfKitBenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 492, in PackageCleanup
    self.RestorePackages()
  File "/home/usero/PerfKitBenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 1173, in RestorePackages
    self.RemoteCommand('sudo dpkg --clear-selections')
  File "/home/usero/PerfKitBenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 617, in RemoteCommand
    return self.RemoteCommandWithReturnCode(*args, **kwargs)[:2]
  File "/home/usero/PerfKitBenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 633, in RemoteCommandWithReturnCode
    return self.RemoteHostCommandWithReturnCode(*args, **kwargs)
  File "/home/usero/PerfKitBenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 702, in RemoteHostCommandWithReturnCode
    raise errors.VirtualMachine.RemoteCommandError(error_text)
RemoteCommandError: Got non-zero return code (1) executing sudo dpkg --clear-selections
Full command: ssh -A -p 22 root@hostname -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o Prefe
rredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o Serve
rAliveCountMax=10 -i /home/usero/.ssh/id_dsa -o ControlPath="/tmp/perfkitbenchmarker/runs/055a1864/ssh/%C" -o ControlMaster=auto -o Control
Persist=30m sudo dpkg --clear-selections
STDOUT: STDERR: Warning: Permanently added 'hostname' (RSA) to the list of known hosts.
sudo: dpkg: command not found
2019-04-22 14:36:08,501 055a1864 MainThread iperf(1/1) ERROR    Exception running benchmark
Traceback (most recent call last):
  File "/home/usero/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 903, in RunBenchmarkTask
    RunBenchmark(spec, collector)
  File "/home/usero/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 752, in RunBenchmark
    DoProvisionPhase(spec, detailed_timer)
  File "/home/usero/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 540, in DoProvisionPhase
    spec.ConstructVirtualMachines()
  File "/home/usero/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 408, in ConstructVirtualMachines
    vms = self.ConstructVirtualMachineGroup(group_name, group_spec)
  File "/home/usero/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 347, in ConstructVirtualMachineGroup
    vm = self._CreateVirtualMachine(group_spec.vm_spec, os_type, cloud)
  File "/home/usero/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 666, in _CreateVirtualMachine
    return vm_class(vm_spec)
  File "/home/usero/PerfKitBenchmarker/perfkitbenchmarker/providers/gcp/gce_virtual_machine.py", line 781, in __init__
    super(RhelBasedGceVirtualMachine, self).__init__(vm_spec)
  File "/home/usero/PerfKitBenchmarker/perfkitbenchmarker/providers/gcp/gce_virtual_machine.py", line 371, in __init__
    self.project = vm_spec.project or util.GetDefaultProject()
  File "/home/usero/.local/lib/python2.7/site-packages/functools32/functools32.py", line 400, in wrapper
    result = user_function(*args, **kwds)
  File "/home/usero/PerfKitBenchmarker/perfkitbenchmarker/providers/gcp/util.py", line 39, in GetDefaultProject
    stdout, _, _ = vm_util.IssueCommand(cmd)
  File "/home/usero/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 352, in IssueCommand
    stderr=tf_err, cwd=cwd)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
2019-04-22 14:36:08,502 055a1864 MainThread iperf(1/1) ERROR    Benchmark 1/1 iperf (UID: iperf0) failed. Execution will continue.
2019-04-22 14:36:08,502 055a1864 MainThread iperf(1/1) INFO     Benchmark run statuses:
---------------------------------------
Name   UID     Status  Failed Substatus
---------------------------------------
iperf  iperf0  FAILED
---------------------------------------
Success rate: 0.00% (0/1)
2019-04-22 14:36:08,503 055a1864 MainThread iperf(1/1) INFO     Complete logs can be found at: /tmp/perfkitbenchmarker/runs/055a1864/pkb.log
2019-04-22 14:36:08,503 055a1864 MainThread iperf(1/1) INFO     Completion statuses can be found at: /tmp/perfkitbenchmarker/runs/055a1864/c
ompletion_statuses.json

```

**Comment by jellyfishcake** [comment]
I can run the benchmark, there is nothing wrong with it.
Your output logs already pointed to the problem. You had a wrong flag value.
E0422 14:35:42.054932 140334663776064 pkb.py:396] flag --os_type=RHEL: value should be one of <centos7|debian|debian9|juju|rhel|ubuntu_conta
iner|ubuntu1404|ubuntu1604|ubuntu1604_cuda9|ubuntu1710|ubuntu1804|windows|windows2012|windows2016|windows2019>
....
2019-04-22 14:36:08,131 055a1864 MainThread WARNING  Could not find os type for VM. Defaulting to debian.

**Comment by omps** [comment]
even when i tried with rhel it is giving me the same error.

```
[PerfKitBenchmarker]$ ./pkb.py --benchmarks=iperf --benchmark_config_file=iperf.yaml --ip_addresses=EXTERNAL --os_type=rhel
2019-04-24 07:14:49,543 a3dd31aa MainThread INFO     Verbose logging to: /tmp/perfkitbenchmarker/runs/a3dd31aa/pkb.log
2019-04-24 07:14:49,543 a3dd31aa MainThread INFO     PerfKitBenchmarker version: v1.12.0-1118-g4943783
2019-04-24 07:14:49,544 a3dd31aa MainThread INFO     Flag values:
--ip_addresses=EXTERNAL
--benchmark_config_file=iperf.yaml
--os_type=rhel
--benchmarks=iperf
2019-04-24 07:14:49,776 a3dd31aa MainThread INFO     Setting --max_concurrent_threads=200.
2019-04-24 07:14:49,816 a3dd31aa MainThread WARNING  The key "static_vms" was not in the default config, but was in user overrides. This may
 indicate a typo.
2019-04-24 07:14:49,816 a3dd31aa MainThread WARNING  The key "flags" was not in the default config, but was in user overrides. This may indi
cate a typo.
2019-04-24 07:14:49,825 a3dd31aa MainThread iperf(1/1) INFO     Provisioning resources for benchmark iperf
2019-04-24 07:14:49,825 a3dd31aa MainThread iperf(1/1) WARNING  Could not find os type for VM. Defaulting to debian.
2019-04-24 07:14:49,825 a3dd31aa MainThread iperf(1/1) INFO     Running: gcloud config list --format=json
2019-04-24 07:14:49,831 a3dd31aa MainThread iperf(1/1) ERROR    Error during benchmark iperf
Traceback (most recent call last):
  File "/home/user/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 752, in RunBenchmark
    DoProvisionPhase(spec, detailed_timer)
  File "/home/user/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 540, in DoProvisionPhase
    spec.ConstructVirtualMachines()
  File "/home/user/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 408, in ConstructVirtualMachines
    vms = self.ConstructVirtualMachineGroup(group_name, group_spec)
  File "/home/user/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 347, in ConstructVirtualMachineGroup
    vm = self._CreateVirtualMachine(group_spec.vm_spec, os_type, cloud)
  File "/home/user/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 666, in _CreateVirtualMachine
    return vm_class(vm_spec)
  File "/home/user/PerfKitBenchmarker/perfkitbenchmarker/providers/gcp/gce_virtual_machine.py", line 781, in __init__
    super(RhelBasedGceVirtualMachine, self).__init__(vm_spec)
  File "/home/user/PerfKitBenchmarker/perfkitbenchmarker/providers/gcp/gce_virtual_machine.py", line 371, in __init__
    self.project = vm_spec.project or util.GetDefaultProject()
  File "/home/user/.local/lib/python2.7/site-packages/functools32/functools32.py", line 400, in wrapper
    result = user_function(*args, **kwds)
  File "/home/user/PerfKitBenchmarker/perfkitbenchmarker/providers/gcp/util.py", line 39, in GetDefaultProject
    stdout, _, _ = vm_util.IssueCommand(cmd)
  File "/home/singho/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line user, in IssueCommand
    stderr=tf_err, cwd=cwd)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
2019-04-24 07:14:49,837 a3dd31aa MainThread iperf(1/1) ERROR    Exception running benchmark
Traceback (most recent call last):
  File "/home/singho/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 903, in RunBenchmarkTask
    RunBenchmark(spec, collector)
  File "/home/singho/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 752, in RunBenchmark
    DoProvisionPhase(spec, detailed_timer)
  File "/home/singho/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 540, in DoProvisionPhase
    spec.ConstructVirtualMachines()
  File "/home/singho/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 408, in ConstructVirtualMachines
    vms = self.ConstructVirtualMachineGroup(group_name, group_spec)
  File "/home/singho/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 347, in ConstructVirtualMachineGroup
    vm = self._CreateVirtualMachine(group_spec.vm_spec, os_type, cloud)
  File "/home/singho/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 666, in _CreateVirtualMachine
    return vm_class(vm_spec)
  File "/home/singho/PerfKitBenchmarker/perfkitbenchmarker/providers/gcp/gce_virtual_machine.py", line 781, in __init__
    super(RhelBasedGceVirtualMachine, self).__init__(vm_spec)
  File "/home/singho/PerfKitBenchmarker/perfkitbenchmarker/providers/gcp/gce_virtual_machine.py", line 371, in __init__
    self.project = vm_spec.project or util.GetDefaultProject()
  File "/home/singho/.local/lib/python2.7/site-packages/functools32/functools32.py", line 400, in wrapper
    result = user_function(*args, **kwds)
  File "/home/singho/PerfKitBenchmarker/perfkitbenchmarker/providers/gcp/util.py", line 39, in GetDefaultProject
    stdout, _, _ = vm_util.IssueCommand(cmd)
  File "/home/singho/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line user, in IssueCommand
    stderr=tf_err, cwd=cwd)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
2019-04-24 07:14:49,838 a3dd31aa MainThread iperf(1/1) ERROR    Benchmark 1/1 iperf (UID: iperf0) failed. Execution will continue.
2019-04-24 07:14:49,838 a3dd31aa MainThread iperf(1/1) INFO     Benchmark run statuses:
---------------------------------------
Name   UID     Status  Failed Substatus
---------------------------------------
iperf  iperf0  FAILED
---------------------------------------
Success rate: 0.00% (0/1)
2019-04-24 07:14:49,839 a3dd31aa MainThread iperf(1/1) INFO     Complete logs can be found at: /tmp/perfkitbenchmarker/runs/a3dd31aa/pkb.log
2019-04-24 07:14:49,839 a3dd31aa MainThread iperf(1/1) INFO     Completion statuses can be found at: /tmp/perfkitbenchmarker/runs/a3dd31aa/completion_statuses.json
```

**Comment by gareth-ferneyhough** [comment]
See the description for the static_vm file here: https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/master/perfkitbenchmarker/static_virtual_machine.py#L166

There is an os_type field for each static vm, so try setting that to rhel inside your static_vm file. Looks like the commandline flag value should be plumbed down to these static_vms, but it does not appear to be the case.

**Comment by omps** [comment]
yes it make sense, I was trying from command line but providing the details in the file does work.

It always happen that when the pkb command is run why it is doing this
` Running: gcloud config list --format=json..`

even if i run just the pkb.py it just runs a lot of command throws lots of output and print 

```
-------------------------------------------------------------------------
Name                    UID                      Status  Failed Substatus
-------------------------------------------------------------------------
unixbench               unixbench0               FAILED
sysbench                sysbench0                FAILED
speccpu2006             speccpu20060             FAILED
redis                   redis0                   FAILED
ping                    ping0                    FAILED
object_storage_service  object_storage_service0  FAILED
netperf                 netperf0                 FAILED
mongodb_ycsb            mongodb_ycsb0            FAILED
mesh_network            mesh_network0            FAILED
iperf                   iperf0                   FAILED
hpcc                    hpcc0                    FAILED
hadoop_terasort         hadoop_terasort0         FAILED
fio                     fio0                     FAILED
coremark                coremark0                FAILED
copy_throughput         copy_throughput0         FAILED
cluster_boot            cluster_boot0            FAILED
cassandra_stress        cassandra_stress0        FAILED
block_storage_workload  block_storage_workload0  FAILED
aerospike               aerospike0               FAILED
-------------------------------------------------------------------------
```


where i just ran this command 

./pkb.py

**Comment by omps** [comment]
moreover is it really necessary to create the cloud account, if i am planning to just run it to some virtual machines, locally?

**Comment by omps** [comment]
seems the issue was mainly with the arguments i was specifying on the CLI. after specifying the host in static_vm_file able to solve the issue.

`./pkb.py --benchmarks=unixbench --benchmark_config_file=unixbech.yaml --static_vm_file=testhost.json`

 To figure this out I need to follow 5 different documents. Doc consolidation is needed. Thanks for the help

**Comment by antigenius0910** [comment]
> seems the issue was mainly with the arguments i was specifying on the CLI. after specifying the host in static_vm_file able to solve the issue.
> 
> `./pkb.py --benchmarks=unixbench --benchmark_config_file=unixbech.yaml --static_vm_file=testhost.json`
> 
> To figure this out I need to follow 5 different documents. Doc consolidation is needed. Thanks for the help

Hi @omps,

Would you mind sharing your "unixbech.yaml" and "testhost.json" config as well? I can do iperf on static_vms but somehow having problem with unixbench on static_vms. 

Thanks
