### ISSUE TITLE
striping all 4 local drives failing on AWS m5d.24xlarge

### ISSUE THREAD

**Issue by HarpPDX** [GoogleCloudPlatform/PerfKitBenchmarker#1905]
Got this error when set num_striped_disks to 4 on an AWS m5d.24xlarge:
```
RemoteCommandError: Got non-zero return code (1) executing yes | sudo mdadm --create /dev/md0 --level=stripe --raid-devices=4 /dev/nvme1n1 /dev/nvme2n1 /dev/nvme3n1 /dev/nvme4n1
Full command: ssh -A -p 22 ubuntu@35.172.229.206 -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /tmp/perfkitbenchmarker/runs/mg1/perfkitbenchmarker_keyfile -o ControlPath="/tmp/perfkitbenchmarker/runs/mg1/ssh/%C" -o ControlMaster=auto -o ControlPersist=10m yes | sudo mdadm --create /dev/md0 --level=stripe --raid-devices=4 /dev/nvme1n1 /dev/nvme2n1 /dev/nvme3n1 /dev/nvme4n1
STDOUT: STDERR: mdadm: super1.x cannot open /dev/nvme4n1: Device or resource busy
mdadm: /dev/nvme4n1 is not suitable for this array.
mdadm: create aborted

```

An assumption in aws_disk.py about the index of the local vs. boot drive is causing a failure:
```
          # If the root drive is also NVME, assume the second drive is the
          # local drive.
          first_device_letter = 'a'

```

It turns out that the first drive is the local drive and the boot drive is the last drive.  Changing first_device_letter from 'a' to 'b' fixed this for me...although I'm not confident that is the correct fix:
```
ubuntu@ip-10-0-0-83:~$ lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
loop0         7:0    0  89.3M  1 loop  /snap/core/6673
loop1         7:1    0  17.9M  1 loop  /snap/amazon-ssm-agent/1068
nvme0n1     259:0    0 838.2G  0 disk
└─md0         9:0    0   3.3T  0 raid0 /scratch
nvme1n1     259:1    0 838.2G  0 disk
└─md0         9:0    0   3.3T  0 raid0 /scratch
nvme2n1     259:2    0 838.2G  0 disk
└─md0         9:0    0   3.3T  0 raid0 /scratch
nvme3n1     259:3    0 838.2G  0 disk
└─md0         9:0    0   3.3T  0 raid0 /scratch
nvme4n1     259:4    0   200G  0 disk
└─nvme4n1p1 259:5    0   200G  0 part  /
```

**Comment by HarpPDX** [comment]
The drive order does not seem to be consistent on the m5d.24xlarge.  I ran several benchmarks successfully with the above "fix", but then ran into a similar error during one run where it looks like nvme3n1 is the boot drive...so 0,1,2, and 4 are the local nvme drives.

```
2019-04-26 21:14:47,842 mgdisk6 MainThread mongodb_stress(1/1) ERROR    Exception occurred while calling PrepareVmAfterBoot(34.207.116.137):
Traceback (most recent call last):
  File "/home/jharper5/share/pkb/perfkitbenchmarker/background_tasks.py", line 247, in Run
    self.return_value = self.target(*self.args, **self.kwargs)
  File "/home/jharper5/share/pkb/perfkitbenchmarker/benchmark_spec.py", line 715, in PrepareVmAfterBoot
    vm.CreateScratchDisk(disk_spec)
  File "/home/jharper5/share/pkb/perfkitbenchmarker/providers/aws/aws_virtual_machine.py", line 803, in CreateScratchDisk
    self._CreateScratchDiskFromDisks(disk_spec, disks)
  File "/home/jharper5/share/pkb/perfkitbenchmarker/linux_virtual_machine.py", line 892, in _CreateScratchDiskFromDisks
    self.StripeDisks(device_paths, data_disk.GetDevicePath())
  File "/home/jharper5/share/pkb/perfkitbenchmarker/linux_virtual_machine.py", line 910, in StripeDisks
    self.RemoteHostCommand(stripe_cmd)
  File "/home/jharper5/share/pkb/perfkitbenchmarker/linux_virtual_machine.py", line 701, in RemoteHostCommand
    suppress_warning, timeout)[:2]
  File "/home/jharper5/share/pkb/perfkitbenchmarker/linux_virtual_machine.py", line 668, in RemoteHostCommandWithReturnCode
    raise errors.VirtualMachine.RemoteCommandError(error_text)
RemoteCommandError: Got non-zero return code (1) executing yes | sudo mdadm --create /dev/md0 --level=stripe --raid-devices=4 /dev/nvme0n1 /dev/nvme1n1 /dev/nvme2n1 /dev/nvme3n1
Full command: ssh -A -p 22 ubuntu@34.207.116.137 -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /tmp/perfkitbenchmarker/runs/mgdisk6/perfkitbenchmarker_keyfile -o ControlPath="/tmp/perfkitbenchmarker/runs/mgdisk6/ssh/%C" -o ControlMaster=auto -o ControlPersist=10m yes | sudo mdadm --create /dev/md0 --level=stripe --raid-devices=4 /dev/nvme0n1 /dev/nvme1n1 /dev/nvme2n1 /dev/nvme3n1
STDOUT: STDERR: mdadm: super1.x cannot open /dev/nvme3n1: Device or resource busy
mdadm: /dev/nvme3n1 is not suitable for this array.
mdadm: create aborted

```

**Comment by HarpPDX** [comment]
The behavior changed again today...the first drive (/dev/nvme0n1) was the boot drive on several consecutive benchmark runs.

**Comment by yuyantingzero** [comment]
Never seen this before. Reading AWS docs (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/nvme-ebs-volumes.html), seems related  "The block device driver can assign NVMe device names in a different order than you specified for the volumes in the block device mapping."

Also from the document, sudo nvme id-ctrl -v /dev/nvme1n1 should be able to tell if the device is EBS or instance store?
