### ISSUE TITLE
cassandra_stress Benchmark fails on staticVM's due to Java Issue

### ISSUE THREAD

**Issue by testmadhumita** [GoogleCloudPlatform/PerfKitBenchmarker#1920]
Hi , 
I am running the Cassandra on Local Static VM's. 
Here is the command and YAML File defined. 
python pkb.py --benchmarks=cassandra_stress --benchmark_config_file=/root/Git_Perfkit/cassandra_stress-bare-metal.yaml

YAML:
static_vms:
    - &vm0
        ip_address: 10.X.X.21
        os_type: centos7
        user_name: pkb
        ssh_private_key: ~/.ssh/id_rsa
        internal_ip: 10.X.X.21
        disk_specs:
            - mount_point: /home
    - &vm1
        os_type: centos7
        ip_address: 10.X.X.20
        user_name: pkb
        ssh_private_key: ~/.ssh/id_rsa
        internal_ip: 10.X.X.20

cassandra_stress:
    vm_groups:
        workers:
            static_vms:
                - *vm0
            vm_count: 1
        client:
            static_vms:
                - *vm1

    flags:
        cassandra_concurrent_reads: 32

**Java Error, I am receiving -** Here attached is the log file for your reference

2019-05-27 03:23:49,255 d31ac05a Thread-31 cassandra_stress(1/1) INFO     Ran: {ssh -A -p 22 pkb@10.20.7.21 -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i ~/.ssh/id_rsa -o ControlPath="/tmp/perfkitbenchmarker/runs/d31ac05a/ssh/%C" -o ControlMaster=auto -o ControlPersist=30m cd /opt/pkb; git clone https://github.com/apache/cassandra.git; cd /opt/pkb/cassandra; git checkout cassandra-2.1.10; /opt/pkb/ant/bin/ant}  ReturnCode:1
STDOUT: Cloning into 'cassandra'...
Error: JAVA_HOME is not defined correctly.
  We cannot execute /opt/pkb/jdk//bin/java

STDERR: Note: checking out 'cassandra-2.1.10'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 78f2e7a... bump version

2019-05-27 03:23:49,264 d31ac05a MainThread cassandra_stress(1/1) ERROR    Exception occurred while calling <lambda>(10.20.7.21):
Traceback (most recent call last):
  File "/root/Git_Perfkit/PerfKitBenchmarker/perfkitbenchmarker/background_tasks.py", line 255, in Run
    self.return_value = self.target(*self.args, **self.kwargs)
  File "/root/Git_Perfkit/PerfKitBenchmarker/perfkitbenchmarker/linux_benchmarks/cassandra_stress_benchmark.py", line 321, in <lambda>
    vm_util.RunThreaded(lambda vm: vm.Install('cassandra'), cassandra_vms)
  File "/root/Git_Perfkit/PerfKitBenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 1104, in Install
    package.YumInstall(self)
  File "/root/Git_Perfkit/PerfKitBenchmarker/perfkitbenchmarker/linux_packages/cassandra.py", line 93, in YumInstall
    _Install(vm)
  File "/root/Git_Perfkit/PerfKitBenchmarker/perfkitbenchmarker/linux_packages/cassandra.py", line 84, in _Install
    ANT_HOME_DIR))
  File "/root/Git_Perfkit/PerfKitBenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 635, in RemoteCommand
    return self.RemoteCommandWithReturnCode(*args, **kwargs)[:2]
  File "/root/Git_Perfkit/PerfKitBenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 651, in RemoteCommandWithReturnCode
    return self.RemoteHostCommandWithReturnCode(*args, **kwargs)
  File "/root/Git_Perfkit/PerfKitBenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 721, in RemoteHostCommandWithReturnCode
    raise errors.VirtualMachine.RemoteCommandError(error_text)
RemoteCommandError: Got non-zero return code (1) executing cd /opt/pkb; git clone https://github.com/apache/cassandra.git; cd /opt/pkb/cassandra; git checkout cassandra-2.1.10; /opt/pkb/ant/bin/ant
Full command: ssh -A -p 22 pkb@10.20.7.21 -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i ~/.ssh/id_rsa -o ControlPath="/tmp/perfkitbenchmarker/runs/d31ac05a/ssh/%C" -o ControlMaster=auto -o ControlPersist=30m cd /opt/pkb; git clone https://github.com/apache/cassandra.git; cd /opt/pkb/cassandra; git checkout cassandra-2.1.10; /opt/pkb/ant/bin/ant
STDOUT: Cloning into 'cassandra'...
Error: JAVA_HOME is not defined correctly.
  We cannot execute /opt/pkb/jdk//bin/java
STDERR: Note: checking out 'cassandra-2.1.10'.
[pkb.log](https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/files/3223189/pkb.log)

**Comment by yuyantingzero** [comment]
I tried running the benchmark on a clean setup with CentOS Linux release 7.6.1810 (Core) not able to repro your issue.
This error is likely related to your local environment, specifically Java installation. 
Can you try: echo $JAVA_HOME? 
Also, do you have pre-installed Java on your test machine, if so, maybe try removing those packages. 

The other option is install everything manually and use --install_packages=False to bypass installation and directly run the benchmark.
