### ISSUE TITLE
YCSB benchmark - always failing with RemoteCommandError

### ISSUE THREAD

**Issue by BhuviTheDataGuy** [GoogleCloudPlatform/PerfKitBenchmarker#2634]
We are trying to run the YCSB benchmark for Spanner, but after 2hrs, its failing, We ran the test so many times. But after 2hr it'll throw the RemoteCommandError.

But sometimes it worked without any errors.

### Error:

```py
2020-12-09 13:34:09,799 perf64kb MainThread cloud_spanner_ycsb(1/1) pkb.py:1079 ERROR    Exception running benchmark
Traceback (most recent call last):
  File "/root/spanner_pkb_fork/perfkitbenchmarker/pkb.py", line 1077, in RunBenchmarkTask
    RunBenchmark(spec, collector)
  File "/root/spanner_pkb_fork/perfkitbenchmarker/pkb.py", line 929, in RunBenchmark
    DoRunPhase(spec, collector, detailed_timer)
  File "/root/spanner_pkb_fork/perfkitbenchmarker/pkb.py", line 763, in DoRunPhase
    samples = spec.BenchmarkRun(spec)
  File "/root/spanner_pkb_fork/perfkitbenchmarker/linux_benchmarks/cloud_spanner_ycsb_benchmark.py", line 164, in Run
    samples = list(benchmark_spec.executor.LoadAndRun(
  File "/root/spanner_pkb_fork/perfkitbenchmarker/linux_packages/ycsb.py", line 1397, in LoadAndRun
    run_samples += self.Run(vms, workloads=workloads,
  File "/root/spanner_pkb_fork/perfkitbenchmarker/linux_packages/ycsb.py", line 1362, in Run
    samples = list(self.RunStaircaseLoads(vms, workloads,
  File "/root/spanner_pkb_fork/perfkitbenchmarker/linux_packages/ycsb.py", line 1215, in RunStaircaseLoads
    vm_util.RunThreaded(PushWorkload, [((vm, workload_file, remote_path), {})
  File "/root/spanner_pkb_fork/perfkitbenchmarker/background_tasks.py", line 650, in RunThreaded
    return RunParallelThreads(target_arg_tuples,
  File "/root/spanner_pkb_fork/perfkitbenchmarker/background_tasks.py", line 585, in RunParallelThreads
    return _RunParallelTasks(
  File "/root/spanner_pkb_fork/perfkitbenchmarker/background_tasks.py", line 559, in _RunParallelTasks
    raise parallel_exception_class(
perfkitbenchmarker.errors.VmUtil.ThreadException: The following exceptions occurred during parallel execution:
Exception occurred while calling PushWorkload(34.125.76.53, /root/spanner_pkb_fork/perfkitbenchmarker/data/ycsb/workloadq, /opt/pkb/workloadq):
Traceback (most recent call last):
  File "/root/spanner_pkb_fork/perfkitbenchmarker/background_tasks.py", line 255, in Run
    self.return_value = self.target(*self.args, **self.kwargs)
  File "/root/spanner_pkb_fork/perfkitbenchmarker/linux_packages/ycsb.py", line 1213, in PushWorkload
    vm.RemoteCommand('sudo rm -f ' + remote_path)
  File "/root/spanner_pkb_fork/perfkitbenchmarker/linux_virtual_machine.py", line 798, in RemoteCommand
    return self.RemoteCommandWithReturnCode(*args, **kwargs)[:2]
  File "/root/spanner_pkb_fork/perfkitbenchmarker/linux_virtual_machine.py", line 814, in RemoteCommandWithReturnCode
    return self.RemoteHostCommandWithReturnCode(*args, **kwargs)
  File "/root/spanner_pkb_fork/perfkitbenchmarker/linux_virtual_machine.py", line 885, in RemoteHostCommandWithReturnCode
    raise errors.VirtualMachine.RemoteCommandError(error_text)
perfkitbenchmarker.errors.VirtualMachine.RemoteCommandError: Got non-zero return code (-13) executing sudo rm -f /opt/pkb/workloadq
Full command: ssh -A -p 22 perfkit@54.15.66.13 -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /tmp/perfkitbenchmarker/runs/perf64kb/perfkitbenchmarker_keyfile -o ControlPath="/tmp/perfkitbenchmarker/runs/perf64kb/ssh/%h" -o ControlMaster=auto -o ControlPersist=30m sudo rm -f /opt/pkb/workloadq
STDOUT: STDERR:    
```

**Comment by bvliu** [comment]
Hi, can you provide the run command you are using and the PKB version? Thanks.

**Comment by BhuviTheDataGuy** [comment]
**Version:** v1.15.1

Run command:
```py
./pkb.py --benchmark_config_file=/root/custom.yaml benchmarks=cloud_spanner_ycsb --zone=us-west4-a --run_uri=perf256kb --bigquery_table=pkb.pkb_result
```

Yaml File:
```yaml
benchmarks:
- cloud_spanner_ycsb:
    flags:
      cloud_spanner_config: regional-us-west4
      machine_type: n2-highcpu-2
      cloud_spanner_nodes: 3
      ycsb_between_run_sleep_time: 1800
      ycsb_client_vms: 30
      ycsb_field_count: 1
      ycsb_field_length: 262144
      ycsb_measurement_type: hdrhistogram
      ycsb_operation_count: 100000000
      ycsb_preload_threads: '320'
      ycsb_record_count: 10000000
      ycsb_run_parameters: target=20000,requestdistribution=zipfian,dataintegrity=True
      cloud_spanner_ycsb_readmode: query
      ycsb_run_stage_iterations: 5
      ycsb_sleep_after_load_in_sec: 1800
      ycsb_tar_url: https://storage.googleapis.com/externally_shared_files/ycsb-0.18.0-SNAPSHOT.tar.gz
      ycsb_threads_per_client: '60'
      ycsb_timelimit: 1800
      ycsb_version: 0.18.0-SNAPSHOT
      ycsb_workload_files: workloadq
      zones: us-west4-a
```

**Comment by bvliu** [comment]
A few suggestions here: 

- Does ssh into the remote worker and `sudo rm -f /opt/pkb/workloadq` work? It seems like there may be an issue with the permissions here.
- Currently the PKB default is YCSB version 0.17.0, which is currently the latest release on [GitHub](https://github.com/brianfrankcooper/YCSB/releases/tag/0.17.0). Does your configuration work with this version?
- `ycsb_workload_files: workloadq` can you try with one of the PKB-provided workload files?
- Does this work on a smaller scale experiment with the same number of client-vms?

**Comment by yuyantingzero** [comment]
Seems like we are trying to delete a non-existing workload file. 

Can you try making following edit:
  File "/root/spanner_pkb_fork/perfkitbenchmarker/linux_packages/ycsb.py", line 1213, in PushWorkload
    vm.RemoteCommand('sudo rm -f ' + remote_path**, ignore_failure=True**)

**Comment by BhuviTheDataGuy** [comment]
Sure, I'll change the line.

But I checked it, the file was there,
And the strange behavior is, its executed successfully for some time, and in some cases like 2 or 3 iterations were successful out of 5.
