### ISSUE TITLE
Openstack - Exception occurred while calling CreateAndBootVm(<BaseVirtualMachine [ip=None, internal_ip=None]>)

### ISSUE THREAD

**Issue by yasmindemiral** [GoogleCloudPlatform/PerfKitBenchmarker#2959]
Hi, I try to run pkb on openstack victoria, when i use this command:
`./pkb.py --cloud=OpenStack --machine_type=m1.small --openstack_network=provider --benchmarks=ping  --os_type=centos7 --openstack_image_username=centos` 

It gave an error: 

`2021-06-01 09:54:06,579 dfaa48b5 MainThread ping(1/1) ERROR    Exception occurred while calling CreateAndBootVm(<BaseVirtualMachine [ip=None, internal_ip=None]>):
Traceback (most recent call last):
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/background_tasks.py", line 255, in Run
    self.return_value = self.target(*self.args, **self.kwargs)
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 800, in CreateAndBootVm
    vm.Create()
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/resource.py", line 262, in Create
    self._PostCreate()
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 271, in WrappedFunction
    return f(*args, **kwargs)
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/providers/openstack/os_virtual_machine.py", line 119, in _PostCreate
    self._SetIPAddresses()
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/providers/openstack/os_virtual_machine.py", line 351, in _SetIPAddresses
    self.ip_address = self._GetNetworkIPAddress(server_dict, self.network_name)
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/providers/openstack/os_virtual_machine.py", line 359, in _GetNetworkIPAddress
    addresses = server_dict['addresses'].split(',')
AttributeError: 'dict' object has no attribute 'split'

2021-06-01 09:54:07,096 dfaa48b5 MainThread ping(1/1) ERROR    Exception occurred while calling CreateAndBootVm(<BaseVirtualMachine [ip=None, internal_ip=None]>):
Traceback (most recent call last):
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/background_tasks.py", line 255, in Run
    self.return_value = self.target(*self.args, **self.kwargs)
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 800, in CreateAndBootVm
    vm.Create()
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/resource.py", line 262, in Create
    self._PostCreate()
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 271, in WrappedFunction
    return f(*args, **kwargs)
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/providers/openstack/os_virtual_machine.py", line 119, in _PostCreate
    self._SetIPAddresses()
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/providers/openstack/os_virtual_machine.py", line 351, in _SetIPAddresses
    self.ip_address = self._GetNetworkIPAddress(server_dict, self.network_name)
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/providers/openstack/os_virtual_machine.py", line 359, in _GetNetworkIPAddress
    addresses = server_dict['addresses'].split(',')
AttributeError: 'dict' object has no attribute 'split'

2021-06-01 09:54:07,100 dfaa48b5 MainThread ping(1/1) ERROR    Error during benchmark ping
Traceback (most recent call last):
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 903, in RunBenchmark
    DoProvisionPhase(spec, detailed_timer)
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 642, in DoProvisionPhase
    spec.Provision()
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 606, in Provision
    vm_util.RunThreaded(
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/background_tasks.py", line 650, in RunThreaded
    return RunParallelThreads(target_arg_tuples,
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/background_tasks.py", line 585, in RunParallelThreads
    return _RunParallelTasks(
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/background_tasks.py", line 559, in _RunParallelTasks
    raise parallel_exception_class(
perfkitbenchmarker.errors.VmUtil.ThreadException: The following exceptions occurred during parallel execution:
Exception occurred while calling CreateAndBootVm(<BaseVirtualMachine [ip=None, internal_ip=None]>):
Traceback (most recent call last):
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/background_tasks.py", line 255, in Run
    self.return_value = self.target(*self.args, **self.kwargs)
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 800, in CreateAndBootVm
    vm.Create()
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/resource.py", line 262, in Create
    self._PostCreate()
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 271, in WrappedFunction
    return f(*args, **kwargs)
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/providers/openstack/os_virtual_machine.py", line 119, in _PostCreate
    self._SetIPAddresses()
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/providers/openstack/os_virtual_machine.py", line 351, in _SetIPAddresses
    self.ip_address = self._GetNetworkIPAddress(server_dict, self.network_name)
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/providers/openstack/os_virtual_machine.py", line 359, in _GetNetworkIPAddress
    addresses = server_dict['addresses'].split(',')
AttributeError: 'dict' object has no attribute 'split'

Exception occurred while calling CreateAndBootVm(<BaseVirtualMachine [ip=None, internal_ip=None]>):
Traceback (most recent call last):
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/background_tasks.py", line 255, in Run
    self.return_value = self.target(*self.args, **self.kwargs)
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 800, in CreateAndBootVm
    vm.Create()
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/resource.py", line 262, in Create
    self._PostCreate()
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 271, in WrappedFunction
    return f(*args, **kwargs)
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/providers/openstack/os_virtual_machine.py", line 119, in _PostCreate
    self._SetIPAddresses()
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/providers/openstack/os_virtual_machine.py", line 351, in _SetIPAddresses
    self.ip_address = self._GetNetworkIPAddress(server_dict, self.network_name)
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/providers/openstack/os_virtual_machine.py", line 359, in _GetNetworkIPAddress
    addresses = server_dict['addresses'].split(',')
AttributeError: 'dict' object has no attribute 'split'  ` 

Can you help me? Is there any bug ?

**Comment by tohaowu** [comment]
It seems that VM was not created successfully. PKB can't get the VM ip address.

**Comment by yasmindemiral** [comment]
I follow the test, virtual machine are created, then running `openstack server show pkb-e03958f0-0 --format json`, the result is http://paste.openstack.org/show/806254/ . It didnt take IP address, I didnt understand.

**Comment by dlott** [comment]
Your paste shows there's a dict with a `provider` inside the `addresses` and then the actual IP:

```
  "addresses": {
    "provider": [
      "10.8.129.220"
    ]
  },
```

Whereas the code seems to expect `addresses` as a comma separated list:

`addresses = server_dict['addresses'].split(',')`

Perhaps the code and the CLI are out of sync?

**Comment by yasmindemiral** [comment]
I'm sure, they are sync. But the code didnt working, It cant separate IP address.

**Comment by yasmindemiral** [comment]
I use Openstack Victoria version, and i installed latest openstack-client (5.5.0), but I checked Victoria OpenstackClient (https://releases.openstack.org/victoria/index.html#victoria-python-openstackclient), so I fixed my openstackclient, the error handled, perfkitbenckmarker is working.
