### ISSUE TITLE
FIO - Your compiler doesn't support C11 atomics. gcc 4.9/clang 3.6

### ISSUE THREAD

**Issue by yasmindemiral** [GoogleCloudPlatform/PerfKitBenchmarker#3060]
Hi
I run PerfkitBenckmarker with fio benckmarker on OpenStack Victoria. I use centos7 image and centos / has gcc 4.8.5 version repo. But fio is waiting gcc 4.9.

`2021-07-08 13:48:43,098 698cfef8 Thread-118 fio(1/1) INFO     Ran: {ssh -A -p 22 centos@<IP> -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /tmp/perfkitbenchmarker/runs/698cfef8/perfkitbenchmarker_keyfile -o ControlPath="/tmp/perfkitbenchmarker/runs/698cfef8/ssh/%h" -o ControlMaster=auto -o ControlPersist=30m cd /opt/pkb/fio && ./configure && make}
ReturnCode:1
STDOUT: Operating system              Linux
CPU                           x86_64
Big endian                    no
Compiler                      gcc
Cross compile                 no

Static build                  no

Your compiler doesn't support C11 atomics. gcc 4.9/clang 3.6 are the
minimum versions with it - perhaps your compiler is too old?
C11 atomics support not found
Configure failed, check config.log and/or the above output

STDERR:
2021-07-08 13:48:43,113 698cfef8 MainThread fio(1/1) ERROR    Exception occurred while calling <lambda>(<IP>):
Traceback (most recent call last):
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/background_tasks.py", line 252, in Run
    self.return_value = self.target(*self.args, **self.kwargs)
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/linux_benchmarks/fio_benchmark.py", line 581, in <lambda>
    vm_util.RunThreaded(lambda vm: PrepareWithExec(vm, exec_path), vms)
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/linux_benchmarks/fio_benchmark.py", line 604, in PrepareWithExec
    vm.Install('fio')
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 1665, in Install
    package.YumInstall(self)
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/linux_packages/fio.py", line 82, in YumInstall
    _Install(vm)
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/linux_packages/fio.py", line 68, in _Install
    vm.RemoteCommand('cd {0} && ./configure && make'.format(FIO_DIR))
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 938, in RemoteCommand
    return self.RemoteCommandWithReturnCode(*args, **kwargs)[:2]
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 954, in RemoteCommandWithReturnCode
    return self.RemoteHostCommandWithReturnCode(*args, **kwargs)
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 1026, in RemoteHostCommandWithReturnCode
    raise errors.VirtualMachine.RemoteCommandError(error_text)`  

How I can run fio benckmark ?

**Comment by spencerghkim** [comment]
You could try running pkb with flag --gcc_version={version} 
(e.g. version=9.2.0 or any folder in https://ftp.gnu.org/gnu/gcc/).

**Comment by yasmindemiral** [comment]
Okey, I use --gcc_version={version} but it give an error about "STDOUT: STDERR: bash: wget: command not found" is there any flag about wget ?

**Comment by yuyantingzero** [comment]
we upgraded fio to latest version a while back, it was tested on ubuntu2004

you can add 'wget' at following line, if this works, feel free to send us a PR: https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/master/perfkitbenchmarker/linux_packages/fio.py#L62

Alternatively, use `git checkout 11aa9c077f14a4745bc173e86d69d0df42e160cd` to run fio test of previous version.
