### ISSUE TITLE
Can not load RPM file

### ISSUE THREAD

**Issue by sannidhyawalzade** [GoogleCloudPlatform/PerfKitBenchmarker#3663]
I'm trying to run benchmark on local RHEL8 machine in virtual environment. The following error is encountered

```
 MainThread iperf(1/1) ERROR    Exception occurred while calling PrepareVmAfterBoot(10.123.4.81):
Traceback (most recent call last):
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/background_tasks.py", line 252, in Run
    self.return_value = self.target(*self.args, **self.kwargs)
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/benchmark_spec.py", line 977, in PrepareVmAfterBoot
    vm.PrepareVMEnvironment()
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 525, in PrepareVMEnvironment
    self.SetupPackageManager()
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 1872, in SetupPackageManager
    self.RemoteCommand(f'sudo dnf install -y {_EPEL_URL.format(8)}')
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 1058, in RemoteCommand
    return self.RemoteCommandWithReturnCode(*args, **kwargs)[:2]
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 1074, in RemoteCommandWithReturnCode
    return self.RemoteHostCommandWithReturnCode(*args, **kwargs)
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 1146, in RemoteHostCommandWithReturnCode
    raise errors.VirtualMachine.RemoteCommandError(error_text)
perfkitbenchmarker.errors.VirtualMachine.RemoteCommandError: Got non-zero return code (1) executing sudo dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
Full command: ssh -A -p <port no> <user>@<ip add> -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /root/.ssh/id_rsa -o ControlPath="/tmp/perfkitbenchmarker/runs/77345236/ssh/%h" -o ControlMaster=auto -o ControlPersist=30m sudo dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
STDOUT: Updating Subscription Management repositories.
Waiting for process with pid 198661 to finish.
STDERR: mesg: ttyname failed: Inappropriate ioctl for device
Can not load RPM file: /var/cache/dnf/commandline-a76fe31ae310b0c7/packages/epel-release-latest-8.noarch.rpm.
Could not open: /var/cache/dnf/commandline-a76fe31ae310b0c7/packages/epel-release-latest-8.noarch.rpm
```

Command ran : $ /local/projects/perfkit/bin/python3 ./pkb.py --benchmarks=iperf --benchmark_config_file=localtest.yaml --static_vm_file=localtest.json --os_type=rhel8 --ip_addresses=EXTERNAL

**Comment by sannidhyawalzade** [comment]
ran dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
Ended up with other error

```
```
Error during benchmark iperf
Traceback (most recent call last):
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/pkb.py", line 1088, in RunBenchmark
    DoProvisionPhase(spec, detailed_timer)
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/pkb.py", line 739, in DoProvisionPhase
    spec.ConstructVirtualMachines()
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/benchmark_spec.py", line 541, in ConstructVirtualMachines
    vms = self.ConstructVirtualMachineGroup(group_name, group_spec)
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/benchmark_spec.py", line 476, in ConstructVirtualMachineGroup
    vm = self._CreateVirtualMachine(group_spec.vm_spec, os_type, cloud)
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/benchmark_spec.py", line 936, in _CreateVirtualMachine
    return vm_class(vm_spec)
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/providers/gcp/gce_virtual_machine.py", line 1129, in __init__
    super(BaseLinuxGceVirtualMachine, self).__init__(vm_spec)
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/providers/gcp/gce_virtual_machine.py", line 423, in __init__
    self.project = vm_spec.project or util.GetDefaultProject()
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/providers/gcp/util.py", line 62, in GetDefaultProject
    stdout, _, _ = vm_util.IssueCommand(cmd)
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/vm_util.py", line 382, in IssueCommand
    stderr=tf_err, cwd=cwd)
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'gcloud': 'gcloud'
```
 Exception occurred while calling DeleteVm(<IP>):
Traceback (most recent call last):
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/background_tasks.py", line 252, in Run
    self.return_value = self.target(*self.args, **self.kwargs)
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/benchmark_spec.py", line 986, in DeleteVm
    vm.PackageCleanup()
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 1748, in PackageCleanup
    self.RemoteCommand('sudo rm /etc/sudoers.d/pkb')
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 1058, in RemoteCommand
    return self.RemoteCommandWithReturnCode(*args, **kwargs)[:2]
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 1074, in RemoteCommandWithReturnCode
    return self.RemoteHostCommandWithReturnCode(*args, **kwargs)
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 1146, in RemoteHostCommandWithReturnCode
    raise errors.VirtualMachine.RemoteCommandError(error_text)
perfkitbenchmarker.errors.VirtualMachine.RemoteCommandError: Got non-zero return code (1) executing sudo rm /etc/sudoers.d/pkb
Full command: ssh -A -p <port> <user>@<IP> -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /root/.ssh/id_rsa -o ControlPath="/tmp/perfkitbenchmarker/runs/df688795/ssh/%h" -o ControlMaster=auto -o ControlPersist=30m sudo rm /etc/sudoers.d/pkb
STDOUT: STDERR: mesg: ttyname failed: Inappropriate ioctl for device
rm: cannot remove '/etc/sudoers.d/pkb': No such file or directory

```
 ```
Got an exception deleting VMs. Attempting to continue tearing down.
Traceback (most recent call last):
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/pkb.py", line 1088, in RunBenchmark
    DoProvisionPhase(spec, detailed_timer)
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/pkb.py", line 739, in DoProvisionPhase
    spec.ConstructVirtualMachines()
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/benchmark_spec.py", line 541, in ConstructVirtualMachines
    vms = self.ConstructVirtualMachineGroup(group_name, group_spec)
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/benchmark_spec.py", line 476, in ConstructVirtualMachineGroup
    vm = self._CreateVirtualMachine(group_spec.vm_spec, os_type, cloud)
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/benchmark_spec.py", line 936, in _CreateVirtualMachine
    return vm_class(vm_spec)
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/providers/gcp/gce_virtual_machine.py", line 1129, in __init__
    super(BaseLinuxGceVirtualMachine, self).__init__(vm_spec)
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/providers/gcp/gce_virtual_machine.py", line 423, in __init__
    self.project = vm_spec.project or util.GetDefaultProject()
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/providers/gcp/util.py", line 62, in GetDefaultProject
    stdout, _, _ = vm_util.IssueCommand(cmd)
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/vm_util.py", line 382, in IssueCommand
    stderr=tf_err, cwd=cwd)
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'gcloud': 'gcloud'
```

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/benchmark_spec.py", line 804, in Delete
    vm_util.RunThreaded(self.DeleteVm, self.vms)
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/background_tasks.py", line 649, in RunThreaded
    post_task_delay=post_task_delay)
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/background_tasks.py", line 584, in RunParallelThreads
    errors.VmUtil.ThreadException, post_task_delay)
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/background_tasks.py", line 558, in _RunParallelTasks
    '{0}{1}'.format(os.linesep, os.linesep.join(error_strings)))
perfkitbenchmarker.errors.VmUtil.ThreadException: The following exceptions occurred during parallel execution:
Exception occurred while calling DeleteVm(10.123.4.81):
Traceback (most recent call last):
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/background_tasks.py", line 252, in Run
    self.return_value = self.target(*self.args, **self.kwargs)
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/benchmark_spec.py", line 986, in DeleteVm
    vm.PackageCleanup()
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 1748, in PackageCleanup
    self.RemoteCommand('sudo rm /etc/sudoers.d/pkb')
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 1058, in RemoteCommand
    return self.RemoteCommandWithReturnCode(*args, **kwargs)[:2]
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 1074, in RemoteCommandWithReturnCode
    return self.RemoteHostCommandWithReturnCode(*args, **kwargs)
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 1146, in RemoteHostCommandWithReturnCode
    raise errors.VirtualMachine.RemoteCommandError(error_text)
perfkitbenchmarker.errors.VirtualMachine.RemoteCommandError: Got non-zero return code (1) executing sudo rm /etc/sudoers.d/pkb
Full command: ssh -A -p 22 root@10.123.4.81 -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /root/.ssh/id_rsa -o ControlPath="/tmp/perfkitbenchmarker/runs/df688795/ssh/%h" -o ControlMaster=auto -o ControlPersist=30m sudo rm /etc/sudoers.d/pkb
STDOUT: STDERR: mesg: ttyname failed: Inappropriate ioctl for device
rm: cannot remove '/etc/sudoers.d/pkb': No such file or director
```
```
 Exception running benchmark
Traceback (most recent call last):
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/pkb.py", line 1311, in RunBenchmarkTask
    RunBenchmark(spec_for_run, collector)
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/pkb.py", line 1088, in RunBenchmark
    DoProvisionPhase(spec, detailed_timer)
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/pkb.py", line 739, in DoProvisionPhase
    spec.ConstructVirtualMachines()
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/benchmark_spec.py", line 541, in ConstructVirtualMachines
    vms = self.ConstructVirtualMachineGroup(group_name, group_spec)
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/benchmark_spec.py", line 476, in ConstructVirtualMachineGroup
    vm = self._CreateVirtualMachine(group_spec.vm_spec, os_type, cloud)
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/benchmark_spec.py", line 936, in _CreateVirtualMachine
    return vm_class(vm_spec)
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/providers/gcp/gce_virtual_machine.py", line 1129, in __init__
    super(BaseLinuxGceVirtualMachine, self).__init__(vm_spec)
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/providers/gcp/gce_virtual_machine.py", line 423, in __init__
    self.project = vm_spec.project or util.GetDefaultProject()
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/providers/gcp/util.py", line 62, in GetDefaultProject
    stdout, _, _ = vm_util.IssueCommand(cmd)
  File "/local/projects/perfkitbenchmarker/perfkitbenchmarker/vm_util.py", line 382, in IssueCommand
    stderr=tf_err, cwd=cwd)
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'gcloud': 'gcloud'
```

**Comment by bvliu** [comment]
Hi, could you please provide the localtest yaml file you are using? Does this benchmark work just running using the default configuration (i.e. no extra flags)?
