### ISSUE TITLE
Bad value [first.middle.lastname]: Only hyphens (-), underscores (_), lowercase characters, and numbers are allowed. 

### ISSUE THREAD

**Issue by jasoncchan** [GoogleCloudPlatform/PerfKitBenchmarker#3751]
The error originates from gcloud, however I don't have this issue when using gcloud myself.
I believe PKB is using my email address to label something, and it isn't allowed because of the periods.

My email address is "first.middle.lastname@company.com" and I can not remove the periods from my company email.

```Exception running benchmark
Traceback (most recent call last):
 File "/home/first.middle.lastname/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 1314, in RunBenchmarkTask
   RunBenchmark(spec_for_run, collector)
 File "/home/first.middle.lastname/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 1091, in RunBenchmark
   DoProvisionPhase(spec, detailed_timer)
 File "/home/first.middle.lastname/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 762, in DoProvisionPhase
   spec.Provision()
 File "/home/first.middle.lastname/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 712, in Provision
   vm_util.RunThreaded(
 File "/home/first.middle.lastname/PerfKitBenchmarker/perfkitbenchmarker/background_tasks.py", line 647, in RunThreaded
   return RunParallelThreads(target_arg_tuples,
 File "/home/first.middle.lastname/PerfKitBenchmarker/perfkitbenchmarker/background_tasks.py", line 582, in RunParallelThreads
   return _RunParallelTasks(
 File "/home/first.middle.lastname/PerfKitBenchmarker/perfkitbenchmarker/background_tasks.py", line 556, in _RunParallelTasks
   raise parallel_exception_class(
perfkitbenchmarker.errors.VmUtil.ThreadException: The following exceptions occurred during parallel execution:
Exception occurred while calling CreateAndBootVm(<BaseVirtualMachine [ip=None, internal_ip=None]>):
Traceback (most recent call last):
 File "/home/first.middle.lastname/PerfKitBenchmarker/perfkitbenchmarker/background_tasks.py", line 252, in Run
   self.return_value = self.target(*self.args, **self.kwargs)
 File "/home/first.middle.lastname/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 944, in CreateAndBootVm
   vm.Create()
 File "/home/first.middle.lastname/PerfKitBenchmarker/perfkitbenchmarker/resource.py", line 355, in Create
   self._CreateResource()
 File "/home/first.middle.lastname/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 261, in WrappedFunction
   return f(*args, **kwargs)
 File "/home/first.middle.lastname/PerfKitBenchmarker/perfkitbenchmarker/resource.py", line 262, in _CreateResource
   self._Create()
 File "/home/first.middle.lastname/PerfKitBenchmarker/perfkitbenchmarker/providers/gcp/gce_virtual_machine.py", line 743, in _Create
   raise errors.Resource.CreationError(
perfkitbenchmarker.errors.Resource.CreationError: Failed to create VM: ERROR: (gcloud.compute.instances.create) argument --labels: Bad value [first.middle.lastname]: Only hyphens (-), underscores (_), lowercase characters, and numbers are allowed. International characters are allowed.
```

The command I am running is:
`
./pkb.py --benchmarks=cluster_boot --machine_type=f1-micro --zones=us-central1-f --run_stage=provision,prepare,run
`

**Comment by aarushisoni** [comment]
Hi my name is Aarushi Soni . I want to contribute to this issue . Is this issue still open ?
Please guide me through this process.

**Comment by jasoncchan** [comment]
Hi @aarushisni,

Sorry for the late reply. Thanks for following up with me. The issue is still open.

To summarize, I'm using google cloud as my cloud provider I'd like to benchmark, and I'm doing this using my company email address. My company email address uses this format first.middle.lastname@mycompany.com and the periods in the name are problematic.

Google cloud does not allow periods when it's doing its provisioning, and it seems like PerfKitBenchmarker is using my email address, which contains periods to provision resources.

I think the fix would be to in PerfKitBenchmarker to strip out periods from people's email address before using it for provisioning.

**Comment by dlott** [comment]
Thanks for the report!  As a workaround, can you try specifying the `--owner` flag to work around the autodetection?

https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/bcb72ced29b6a77d685be273c6a638f5b907de7d/perfkitbenchmarker/pkb.py#L206
