### ISSUE TITLE
Bigtable Benchmarking Tutorial is failing with error 

### ISSUE THREAD

**Issue by maheshgoyal15** [GoogleCloudPlatform/PerfKitBenchmarker#4013]
I am trying to follow the steps mentioned in the tutorial https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/tree/master/tutorials/bigtable_walkthrough to run the Bigtable  benchmark and its failing with the below error. 

This where the error starts : 

```
[For throughput.yaml] ERROR    Unknown command line flag 'google_bigtable_client_version'. Did you mean: google_bigtable_admin_endpoint, google_bigtable_endpoint ?
[For throughput.yaml] INFO     For usage instructions, use --helpmatch={module_name}
[For throughput.yaml] INFO     For example, ./pkb.py --helpmatch=benchmarks.fio
[For latency.yaml] ERROR    Unknown command line flag 'google_bigtable_client_version'. Did you mean: google_bigtable_admin_endpoint, google_bigtable_endpoint ?

```
I have Python 3.9 installed and I tried several times. Looks like the new docker image is breaking the pipeline
```
 sudo docker run --init --rm -it -v ~/pkb_configs:/pkb/configs \
-v /tmp:/tmp gcr.io/cloud-bigtable-ecosystem/pkb:latest
I0211 04:06:57.852136 140669124077376 batch_runner.py:146] Running BatchRunner with the following directories: config_dir=/pkb/configs/, pkb_workspace_dir=/tmp/pkb_workspace, state_dir=/pkb/configs/
I0211 04:06:57.885868 140669114345216 single_runner.py:132] ----------Execute the following command to run benchmark throughput.yaml----------:
/usr/bin/env python3 /pkb/PerfKitBenchmarker/pkb.py --project=maheshgoyal-project-1 --file_log_level=debug --gcloud_scopes=https://www.googleapis.com/auth/bigtable.admin,https://www.googleapis.com/auth/bigtable.data,storage-rw --ssh_connect_timeout=30 --ssh_reuse_connections=False --gce_network_name=default --gce_remote_access_firewall_rule=default-allow-internal --connect_via_internal_ip=True --hbase_bin_url=https://storage.googleapis.com/cbt_ycsb_client_jar/hbase-1.4.7-bin.tar.gz --hadoop_bin_url=https://storage.googleapis.com/cbt_ycsb_client_jar/hadoop-3.3.1.tar.gz --google_bigtable_client_version=2.5.0 --ycsb_version=0.17.0 --ycsb_log_remote_command_output=False --ycsb_measurement_type=hdrhistogram --get_bigtable_cluster_cpu_utilization=True --bigquery_table=maheshgoyal-project-1:pkb_results.codelab --benchmarks=cloud_bigtable_ycsb --machine_type=n2-highcpu-16 --num_vms=4 --zones=us-central1-b --google_bigtable_zone=us-central1-b --bigtable_node_count=3 --bigtable_storage_type=ssd --ycsb_field_count=1 --ycsb_field_length=1024 --ycsb_record_count=5000000 --ycsb_run_parameters=target=6000,readallfields=false,requestdistribution=zipfian --ycsb_threads_per_client=32 --ycsb_operation_count=2147483647 --ycsb_timelimit=600 --ycsb_workload_files=workloada --metadata=experiment:throughput_test --json_path=/tmp/pkb_workspace/throughput-1676088417.8811765.json
I0211 04:06:57.891442 140669037311744 single_runner.py:132] ----------Execute the following command to run benchmark latency.yaml----------:
/usr/bin/env python3 /pkb/PerfKitBenchmarker/pkb.py --project=maheshgoyal-project-1 --file_log_level=debug --gcloud_scopes=https://www.googleapis.com/auth/bigtable.admin,https://www.googleapis.com/auth/bigtable.data,storage-rw --ssh_connect_timeout=30 --ssh_reuse_connections=False --gce_network_name=default --gce_remote_access_firewall_rule=default-allow-internal --connect_via_internal_ip=True --hbase_bin_url=https://storage.googleapis.com/cbt_ycsb_client_jar/hbase-1.4.7-bin.tar.gz --hadoop_bin_url=https://storage.googleapis.com/cbt_ycsb_client_jar/hadoop-3.3.1.tar.gz --google_bigtable_client_version=2.5.0 --ycsb_version=0.17.0 --ycsb_log_remote_command_output=False --ycsb_measurement_type=hdrhistogram --get_bigtable_cluster_cpu_utilization=True --bigquery_table=maheshgoyal-project-1:pkb_results.codelab --benchmarks=cloud_bigtable_ycsb --machine_type=n2-highcpu-16 --num_vms=1 --zones=us-central1-b --google_bigtable_zone=us-central1-b --bigtable_node_count=3 --bigtable_storage_type=ssd --ycsb_field_count=1 --ycsb_field_length=1024 --ycsb_record_count=5000000 --ycsb_run_parameters=target=3000,readallfields=false,requestdistribution=zipfian --ycsb_threads_per_client=32 --ycsb_operation_count=2147483647 --ycsb_timelimit=600 --ycsb_workload_files=workloada --metadata=experiment:latency_test --json_path=/tmp/pkb_workspace/latency-1676088417.886654.json
[For throughput.yaml] ERROR    Unknown command line flag 'google_bigtable_client_version'. Did you mean: google_bigtable_admin_endpoint, google_bigtable_endpoint ?
[For throughput.yaml] INFO     For usage instructions, use --helpmatch={module_name}
[For throughput.yaml] INFO     For example, ./pkb.py --helpmatch=benchmarks.fio
[For latency.yaml] ERROR    Unknown command line flag 'google_bigtable_client_version'. Did you mean: google_bigtable_admin_endpoint, google_bigtable_endpoint ?
[For latency.yaml] INFO     For usage instructions, use --helpmatch={module_name}
[For latency.yaml] INFO     For example, ./pkb.py --helpmatch=benchmarks.fio
E0211 04:07:06.359612 140669124077376 batch_runner.py:439] Test run of throughput.yaml failed with exception
Traceback (most recent call last):
  File "batch_runner.py", line 434, in _run_unordered_tests
    future.result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "batch_runner.py", line 300, in _run_test
    runner.run(dry_run)
  File "/pkb/single_runner.py", line 153, in run
    raise subprocess.CalledProcessError(return_code, args)
subprocess.CalledProcessError: Command '['/usr/bin/env', 'python3', '/pkb/PerfKitBenchmarker/pkb.py', '--project=maheshgoyal-project-1', '--file_log_level=debug', '--gcloud_scopes=https://www.googleapis.com/auth/bigtable.admin,https://www.googleapis.com/auth/bigtable.data,storage-rw', '--ssh_connect_timeout=30', '--ssh_reuse_connections=False', '--gce_network_name=default', '--gce_remote_access_firewall_rule=default-allow-internal', '--connect_via_internal_ip=True', '--hbase_bin_url=https://storage.googleapis.com/cbt_ycsb_client_jar/hbase-1.4.7-bin.tar.gz', '--hadoop_bin_url=https://storage.googleapis.com/cbt_ycsb_client_jar/hadoop-3.3.1.tar.gz', '--google_bigtable_client_version=2.5.0', '--ycsb_version=0.17.0', '--ycsb_log_remote_command_output=False', '--ycsb_measurement_type=hdrhistogram', '--get_bigtable_cluster_cpu_utilization=True', '--bigquery_table=maheshgoyal-project-1:pkb_results.codelab', '--benchmarks=cloud_bigtable_ycsb', '--machine_type=n2-highcpu-16', '--num_vms=4', '--zones=us-central1-b', '--google_bigtable_zone=us-central1-b', '--bigtable_node_count=3', '--bigtable_storage_type=ssd', '--ycsb_field_count=1', '--ycsb_field_length=1024', '--ycsb_record_count=5000000', '--ycsb_run_parameters=target=6000,readallfields=false,requestdistribution=zipfian', '--ycsb_threads_per_client=32', '--ycsb_operation_count=2147483647', '--ycsb_timelimit=600', '--ycsb_workload_files=workloada', '--metadata=experiment:throughput_test', '--json_path=/tmp/pkb_workspace/throughput-1676088417.8811765.json']' returned non-zero exit status 1.
E0211 04:07:06.362101 140669124077376 batch_runner.py:439] Test run of latency.yaml failed with exception
Traceback (most recent call last):
  File "batch_runner.py", line 434, in _run_unordered_tests
    future.result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "batch_runner.py", line 300, in _run_test
    runner.run(dry_run)
  File "/pkb/single_runner.py", line 153, in run
    raise subprocess.CalledProcessError(return_code, args)
subprocess.CalledProcessError: Command '['/usr/bin/env', 'python3', '/pkb/PerfKitBenchmarker/pkb.py', '--project=maheshgoyal-project-1', '--file_log_level=debug', '--gcloud_scopes=https://www.googleapis.com/auth/bigtable.admin,https://www.googleapis.com/auth/bigtable.data,storage-rw', '--ssh_connect_timeout=30', '--ssh_reuse_connections=False', '--gce_network_name=default', '--gce_remote_access_firewall_rule=default-allow-internal', '--connect_via_internal_ip=True', '--hbase_bin_url=https://storage.googleapis.com/cbt_ycsb_client_jar/hbase-1.4.7-bin.tar.gz', '--hadoop_bin_url=https://storage.googleapis.com/cbt_ycsb_client_jar/hadoop-3.3.1.tar.gz', '--google_bigtable_client_version=2.5.0', '--ycsb_version=0.17.0', '--ycsb_log_remote_command_output=False', '--ycsb_measurement_type=hdrhistogram', '--get_bigtable_cluster_cpu_utilization=True', '--bigquery_table=maheshgoyal-project-1:pkb_results.codelab', '--benchmarks=cloud_bigtable_ycsb', '--machine_type=n2-highcpu-16', '--num_vms=1', '--zones=us-central1-b', '--google_bigtable_zone=us-central1-b', '--bigtable_node_count=3', '--bigtable_storage_type=ssd', '--ycsb_field_count=1', '--ycsb_field_length=1024', '--ycsb_record_count=5000000', '--ycsb_run_parameters=target=3000,readallfields=false,requestdistribution=zipfian', '--ycsb_threads_per_client=32', '--ycsb_operation_count=2147483647', '--ycsb_timelimit=600', '--ycsb_workload_files=workloada', '--metadata=experiment:latency_test', '--json_path=/tmp/pkb_workspace/latency-1676088417.886654.json']' returned non-zero exit status 1.
Some tests have failures. You can retry by running the same invocation command again
```

Can you help whats going wrong here? I cant seem to find  as I tried almost 20 times.

**Comment by liujiongxin** [comment]
Sorry about the inconvenience. We have some difficulty publishing the new docker image.. 

In the meantime, please replace "google_bigtable_client_version: 2.5.0" with "google_bigtable_hbase_jar_url: https://storage.googleapis.com/cbt_ycsb_client_jar/bigtable-hbase-1.x-hadoop-1.20.1.jar" in the runner.yaml file.

We will publish a new image today to make it work with parameter "google_bigtable_client_version".

**Comment by liujiongxin** [comment]
The image has been updated. 

To pick it up, please clean up the existing one on your local machine with command `$ sudo docker rmi gcr.io/cloud-bigtable-ecosystem/pkb:latest` first.

**Comment by maheshgoyal15** [comment]
I tried but this still fails with the below error - 


```
[latency.yaml] 2023-02-14 05:46:29,012 8642d8a3 MainThread INFO     Running: ssh-keygen -t rsa -N  -m PEM -q -f /tmp/perfkitbenchmarker/runs/8642d8a3/perfkitbenchmarker_keyfile
E0214 05:46:29.112512 139986009745216 batch_runner.py:469] Test run of throughput.yaml failed with exception
Traceback (most recent call last):
  File "/pkb/batch_runner.py", line 465, in _run_unordered_tests
    future.result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 433, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/pkb/batch_runner.py", line 311, in _run_test
    runner.run(dry_run)
  File "/pkb/single_runner.py", line 151, in run
    raise subprocess.CalledProcessError(return_code, args)
subprocess.CalledProcessError: Command '['/usr/bin/env', 'python3', '/pkb/PerfKitBenchmarker/pkb.py', '--project=maheshgoyal-project-2', '--file_log_level=info', '--gcloud_scopes=https://www.googleapis.com/auth/bigtable.admin,https://www.googleapis.com/auth/bigtable.data,storage-rw', '--ssh_connect_timeout=30', '--ssh_reuse_connections=False', '--gce_network_name=default', '--gce_remote_access_firewall_rule=default-allow-internal', '--connect_via_internal_ip=True', '--hbase_bin_url=https://storage.googleapis.com/cbt_ycsb_client_jar/hbase-1.4.7-bin.tar.gz', '--hadoop_bin_url=https://storage.googleapis.com/cbt_ycsb_client_jar/hadoop-3.3.1.tar.gz', '--google_bigtable_client_version=2.5.0', '--ycsb_version=0.17.0', '--ycsb_log_remote_command_output=False', '--ycsb_measurement_type=hdrhistogram', '--get_bigtable_cluster_cpu_utilization=True', '--bigquery_table=maheshgoyal-project-2:pkb_results.codelab', '--benchmarks=cloud_bigtable_ycsb', '--machine_type=n1-highcpu-16', '--num_vms=4', '--zones=us-west1-a', '--google_bigtable_zone=us-west1-a', '--bigtable_node_count=None', '--bigtable_storage_type=ssd', '--ycsb_field_count=5', '--ycsb_field_length=4024', '--ycsb_record_count=100000', '--ycsb_run_parameters=target=6000,readallfields=false,requestdistribution=zipfian', '--ycsb_threads_per_client=32', '--ycsb_operation_count=2147483647', '--ycsb_timelimit=600', '--ycsb_workload_files=workloadc', '--metadata=experiment:throughput_test', '--json_path=/tmp/pkb_workspace/throughput-1676353583.643095.json']' returned non-zero exit status 1.
```

**Comment by liujiongxin** [comment]
The stack trace doesn't tell much about the failure cause. Do you have other contextual info messages around the failure point?

I just tried the throughput test used in the user guide, and it ran to completion successfully.

**Comment by maheshgoyal15** [comment]
Did you try it on CloudShell or a Debian Compute engine. Let me know, I will try it as well.

**Comment by liujiongxin** [comment]
I did it on a Debian Compute engine. The image is debian-11-bullseye-v20230206

**Comment by maheshgoyal15** [comment]
It worked for me for the region specified. I will try for other regions and see if it works.

**Comment by s-deitz** [comment]
Please reopen if necessary.
