### ISSUE TITLE
epel issue while trying to run perfkit on RHEL7.9 static VM

### ISSUE THREAD

**Issue by avinxxsh** [GoogleCloudPlatform/PerfKitBenchmarker#4090]
```2023-03-09 05:34:23,827 c0e38e7a MainThread unixbench(1/1) ERROR    Exception running benchmark
Traceback (most recent call last):
  File "/home/dgavinaa/perfkitbenchmarker/perfkitbenchmarker/pkb.py", line 1311, in RunBenchmarkTask
    RunBenchmark(spec_for_run, collector)
  File "/home/dgavinaa/perfkitbenchmarker/perfkitbenchmarker/pkb.py", line 1088, in RunBenchmark
    DoProvisionPhase(spec, detailed_timer)
  File "/home/dgavinaa/perfkitbenchmarker/perfkitbenchmarker/pkb.py", line 760, in DoProvisionPhase
    spec.Provision()
  File "/home/dgavinaa/perfkitbenchmarker/perfkitbenchmarker/benchmark_spec.py", line 718, in Provision
    vm_util.RunThreaded(self.PrepareVmAfterBoot, self.vms)
  File "/home/dgavinaa/perfkitbenchmarker/perfkitbenchmarker/background_tasks.py", line 647, in RunThreaded
    return RunParallelThreads(target_arg_tuples,
  File "/home/dgavinaa/perfkitbenchmarker/perfkitbenchmarker/background_tasks.py", line 582, in RunParallelThreads
    return _RunParallelTasks(
  File "/home/dgavinaa/perfkitbenchmarker/perfkitbenchmarker/background_tasks.py", line 556, in _RunParallelTasks
    raise parallel_exception_class(
perfkitbenchmarker.errors.VmUtil.ThreadException: The following exceptions occurred during parallel execution:
Exception occurred while calling PrepareVmAfterBoot(<ip>):
Traceback (most recent call last):
  File "/home/dgavinaa/perfkitbenchmarker/perfkitbenchmarker/background_tasks.py", line 252, in Run
    self.return_value = self.target(*self.args, **self.kwargs)
  File "/home/dgavinaa/perfkitbenchmarker/perfkitbenchmarker/benchmark_spec.py", line 977, in PrepareVmAfterBoot
    vm.PrepareVMEnvironment()
  File "/home/dgavinaa/perfkitbenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 525, in PrepareVMEnvironment
    self.SetupPackageManager()
  File "/home/dgavinaa/perfkitbenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 1861, in SetupPackageManager
    self.RemoteCommand(
  File "/home/dgavinaa/perfkitbenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 1058, in RemoteCommand
    return self.RemoteCommandWithReturnCode(*args, **kwargs)[:2]
  File "/home/dgavinaa/perfkitbenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 1074, in RemoteCommandWithReturnCode
    return self.RemoteHostCommandWithReturnCode(*args, **kwargs)
  File "/home/dgavinaa/perfkitbenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 1146, in RemoteHostCommandWithReturnCode
    raise errors.VirtualMachine.RemoteCommandError(error_text)
perfkitbenchmarker.errors.VirtualMachine.RemoteCommandError: Got non-zero return code (1) executing rpm -q epel-release || sudo yum install -y http://anglxd00001.nomura.com/pulp/isos/NOMURA/Library/custom/perfkitbenchmark/perfkitbenchmark-repo/epel-release-latest-8.noarch.rpm
Full command: ssh -A -p 22 root@<ip> -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /home/dgavinaa/.ssh/id_rsa_perfkit -o ControlPath="/tmp/perfkitbenchmarker/runs/c0e38e7a/ssh/%h" -o ControlMaster=auto -o ControlPersist=30m rpm -q epel-release || sudo yum install -y http://anglxd00001.nomura.com/pulp/isos/NOMURA/Library/custom/perfkitbenchmark/perfkitbenchmark-repo/epel-release-latest-8.noarch.rpm
STDOUT: package epel-release is not installed
Loaded plugins: enabled_repos_upload, package_upload, product-id, search-
              : disabled-repos, subscription-manager
Examining /var/tmp/yum-root-Rc1sdF/epel-release-latest-8.noarch.rpm: epel-release-8-16.el8.noarch
Marking /var/tmp/yum-root-Rc1sdF/epel-release-latest-8.noarch.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package epel-release.noarch 0:8-16.el8 will be installed
--> Processing Dependency: redhat-release >= 8 for package: epel-release-8-16.el8.noarch
--> Finished Dependency Resolution
Error: Package: epel-release-8-16.el8.noarch (/epel-release-latest-8.noarch)
           Requires: redhat-release >= 8
           Installed: redhat-release-server-7.9-6.el7_9.x86_64 (@rhel-7-server-rpms)
               redhat-release = 7.9-6.el7_9
           Available: redhat-release-server-7.0-1.el7.x86_64 (rhel-7-server-rpms)
               redhat-release = 7.0-1.el7
           Available: redhat-release-server-7.1-1.el7.x86_64 (rhel-7-server-rpms)
               redhat-release = 7.1-1.el7
           Available: redhat-release-server-7.2-9.el7.x86_64 (rhel-7-server-rpms)
               redhat-release = 7.2-9.el7
           Available: redhat-release-server-7.3-7.el7.x86_64 (rhel-7-server-rpms)
               redhat-release = 7.3-7.el7
           Available: redhat-release-server-7.4-18.el7.x86_64 (rhel-7-server-rpms)
               redhat-release = 7.4-18.el7
           Available: redhat-release-server-7.5-8.el7.x86_64 (rhel-7-server-rpms)
               redhat-release = 7.5-8.el7
           Available: redhat-release-server-7.5-8.el7.1.x86_64 (rhel-7-server-rpms)
               redhat-release = 7.5-8.el7.1
           Available: redhat-release-server-7.6-4.el7.x86_64 (rhel-7-server-rpms)
               redhat-release = 7.6-4.el7
           Available: redhat-release-server-7.7-10.el7.x86_64 (rhel-7-server-rpms)
               redhat-release = 7.7-10.el7
           Available: redhat-release-server-7.8-2.el7.x86_64 (rhel-7-server-rpms)
               redhat-release = 7.8-2.el7
           Available: redhat-release-server-7.9-3.el7.x86_64 (rhel-7-server-rpms)
               redhat-release = 7.9-3.el7
           Available: redhat-release-server-7.9-5.el7_9.x86_64 (rhel-7-server-rpms)
               redhat-release = 7.9-5.el7_9
**********************************************************************
yum can be configured to try to resolve such errors by temporarily enabling
disabled repos and searching for missing dependencies.
To enable this functionality please set 'notify_only=0' in /etc/yum/pluginconf.d/search-disabled-repos.conf
**********************************************************************

 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
Uploading Enabled Repositories Report
Loaded plugins: product-id, subscription-manager
STDERR: Error: Package: epel-release-8-16.el8.noarch (/epel-release-latest-8.noarch)
           Requires: redhat-release >= 8
           Installed: redhat-release-server-7.9-6.el7_9.x86_64 (@rhel-7-server-rpms)
               redhat-release = 7.9-6.el7_9
           Available: redhat-release-server-7.0-1.el7.x86_64 (rhel-7-server-rpms)
               redhat-release = 7.0-1.el7
           Available: redhat-release-server-7.1-1.el7.x86_64 (rhel-7-server-rpms)
               redhat-release = 7.1-1.el7
           Available: redhat-release-server-7.2-9.el7.x86_64 (rhel-7-server-rpms)
               redhat-release = 7.2-9.el7
           Available: redhat-release-server-7.3-7.el7.x86_64 (rhel-7-server-rpms)
               redhat-release = 7.3-7.el7
           Available: redhat-release-server-7.4-18.el7.x86_64 (rhel-7-server-rpms)
               redhat-release = 7.4-18.el7
           Available: redhat-release-server-7.5-8.el7.x86_64 (rhel-7-server-rpms)
               redhat-release = 7.5-8.el7
           Available: redhat-release-server-7.5-8.el7.1.x86_64 (rhel-7-server-rpms)
               redhat-release = 7.5-8.el7.1
           Available: redhat-release-server-7.6-4.el7.x86_64 (rhel-7-server-rpms)
               redhat-release = 7.6-4.el7
           Available: redhat-release-server-7.7-10.el7.x86_64 (rhel-7-server-rpms)
               redhat-release = 7.7-10.el7
           Available: redhat-release-server-7.8-2.el7.x86_64 (rhel-7-server-rpms)
               redhat-release = 7.8-2.el7
           Available: redhat-release-server-7.9-3.el7.x86_64 (rhel-7-server-rpms)
               redhat-release = 7.9-3.el7
           Available: redhat-release-server-7.9-5.el7_9.x86_64 (rhel-7-server-rpms)
               redhat-release = 7.9-5.el7_9

**Comment by avinxxsh** [comment]
command used;
/usr/local/bin/bin/python3.10 ./pkb.py --benchmarks=unixbench --benchmark_config_file=unixbench.yaml --static_vm_file=localtest.json --os_type="rhel8" --ip_addresses=EXTERNAL
