### ISSUE TITLE
When run benchmark stress_ng with `--os_type=ubuntu2204`, `libgcrypt11-dev` is not found

### ISSUE THREAD

**Issue by nogamenofun98** [GoogleCloudPlatform/PerfKitBenchmarker#4265]
I tried run in gcloud shell with this command: `./pkb.py --cloud=GCP --zones=asia-southeast1-a --benchmarks=sysbench,stress_ng,nginx,iperf,fio,apachebench,netperf_aggregate,netperf,ping`

2023-05-24 03:32:00,317 7a8804c4 MainThread sysbench(1/9) stress_ng(2/9) ERROR    Exception running benchmark
Traceback (most recent call last):
  File "/home/cloud/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 277, in WrappedFunction
    return f(*args, **kwargs)
  File "/home/cloud/PerfKitBenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 2241, in InstallPackages
    raise e
  File "/home/cloud/PerfKitBenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 2231, in InstallPackages
    self.RemoteCommand(install_command)
  File "/home/cloud/PerfKitBenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 1138, in RemoteCommand
    return self.RemoteCommandWithReturnCode(*args, **kwargs)[:2]
  File "/home/cloud/PerfKitBenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 1157, in RemoteCommandWithReturnCode
    return self.RemoteHostCommandWithReturnCode(*args, **kwargs)
  File "/home/cloud/PerfKitBenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 1242, in RemoteHostCommandWithReturnCode
    raise errors.VirtualMachine.RemoteCommandError(error_text)
perfkitbenchmarker.errors.VirtualMachine.RemoteCommandError: Got non-zero return code (100) executing sudo DEBIAN_FRONTEND='noninteractive' /usr/bin/apt-get -y install build-essential libaio-dev libapparmor-dev libattr1-dev libbsd-dev libcap-dev libgcrypt11-dev libkeyutils-dev libsctp-dev zlib1g-dev
Full command: ssh -A -p 22 perfkit@34.143.245.170 -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /tmp/perfkitbenchmarker/runs/7a8804c4/perfkitbenchmarker_keyfile -o ControlPath="/tmp/perfkitbenchmarker/runs/7a8804c4/ssh/%h" -o ControlMaster=auto -o ControlPersist=30m sudo DEBIAN_FRONTEND='noninteractive' /usr/bin/apt-get -y install build-essential libaio-dev libapparmor-dev libattr1-dev libbsd-dev libcap-dev libgcrypt11-dev libkeyutils-dev libsctp-dev zlib1g-dev
STDOUT: Reading package lists...
Building dependency tree...
Reading state information...
STDERR: E: Unable to locate package libgcrypt11-dev

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cloud/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 1028, in RunBenchmarkTask
    RunBenchmark(spec_for_run, collector)
  File "/home/cloud/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 813, in RunBenchmark
    DoPreparePhase(spec, detailed_timer)
  File "/home/cloud/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 526, in DoPreparePhase
    spec.BenchmarkPrepare(spec)
  File "/home/cloud/PerfKitBenchmarker/perfkitbenchmarker/linux_benchmarks/stress_ng_benchmark.py", line 174, in Prepare
    vm.Install('stress_ng')
  File "/home/cloud/PerfKitBenchmarker/perfkitbenchmarker/linux_virtual_machine.py", line 2255, in Install
    package.AptInstall(self)
  File "/home/cloud/PerfKitBenchmarker/perfkitbenchmarker/linux_packages/stress_ng.py", line 31, in AptInstall
    vm.InstallPackages(
  File "/home/cloud/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 289, in WrappedFunction
    time.sleep(sleep_time)
KeyboardInterrupt
2023-05-24 03:32:00,318 7a8804c4 MainThread sysbench(1/9) stress_ng(2/9) ERROR    Benchmark 2/9 stress_ng (UID: stress_ng0) failed. Execution will not continue.
2023-05-24 03:32:00,319 7a8804c4 MainThread sysbench(1/9) stress_ng(2/9) INFO     Benchmark run statuses:
----------------------------------------------------------------
Name               UID                 Status   Failed Substatus
----------------------------------------------------------------
sysbench           sysbench0           FAILED   UNCATEGORIZED   
stress_ng          stress_ng0          FAILED   UNCATEGORIZED   
nginx              nginx0              SKIPPED                  
iperf              iperf0              SKIPPED                  
fio                fio0                SKIPPED                  
apachebench        apachebench0        SKIPPED                  
netperf_aggregate  netperf_aggregate0  SKIPPED                  
netperf            netperf0            SKIPPED                  
ping               ping0               SKIPPED                  
----------------------------------------------------------------
Success rate: 0.00% (0/9)
2023-05-24 03:32:00,319 7a8804c4 MainThread sysbench(1/9) stress_ng(2/9) INFO     Complete logs can be found at: /tmp/perfkitbenchmarker/runs/7a8804c4/pkb.log
2023-05-24 03:32:00,319 7a8804c4 MainThread sysbench(1/9) stress_ng(2/9) INFO     Completion statuses can be found at: /tmp/perfkitbenchmarker/runs/7a8804c4/completion_statuses.json

**Comment by andyz422** [comment]
Fixed.
