### ISSUE TITLE
Running on VM (no relevant cloud)

### ISSUE THREAD

**Issue by vsoch** [GoogleCloudPlatform/PerfKitBenchmarker#4437]
I'm running on a local kubernetes cluster, with one pod as the launcher to run the initial command, and the other pod(s) to do benchmarking. I think I'm close, but it's trying to call gcloud. Here are my static VMs:

```json
[
        {
                "ip_address": "metricset-sample-w-0-0.ms.default.svc.cluster.local",
                "user_name": "root",
                "keyfile_path": "/root/.ssh/id_rsa",
                "os_type":"ubuntu2304"
        }
]
```

And the output:
```console
 ./pkb.py --benchmarks=iperf --static_vm_file=static_vms.json --ip_addresses=EXTERNAL --accept_licenses --ssh_control_path="/tmp/%h" --install_packages=false
2023-08-22 06:23:12,061 e703e24d MainThread INFO     Verbose logging to: /tmp/perfkitbenchmarker/runs/e703e24d/pkb.log
2023-08-22 06:23:12,062 e703e24d MainThread INFO     PerfKitBenchmarker version: v1.12.0-4093-g975dfdd7
2023-08-22 06:23:12,063 e703e24d MainThread INFO     Flag values:
--ssh_control_path=/tmp/%h
--ip_addresses=EXTERNAL
--accept_licenses
--benchmarks=iperf
--static_vm_file=static_vms.json
--noinstall_packages
2023-08-22 06:23:12,489 e703e24d MainThread INFO     Running: ssh-keygen -t rsa -N  -m PEM -q -f /tmp/perfkitbenchmarker/runs/e703e24d/perfkitbenchmarker_keyfile
2023-08-22 06:23:14,445 e703e24d MainThread INFO     Ran: {ssh-keygen -t rsa -N  -m PEM -q -f /tmp/perfkitbenchmarker/runs/e703e24d/perfkitbenchmarker_keyfile}
ReturnCode:0
STDOUT: 
STDERR: 
2023-08-22 06:23:14,446 e703e24d MainThread INFO     Setting --max_concurrent_threads=200.
2023-08-22 06:23:14,479 e703e24d MainThread WARNING  The key "flags" was not in the default config, but was in user overrides. This may indicate a typo.
2023-08-22 06:23:14,497 e703e24d MainThread INFO     
-------------------------------------------------------------------------------------
Starting benchmark 1/1 iperf (UID: iperf0) attempt 1 of 1
-------------------------------------------------------------------------------------
2023-08-22 06:23:14,498 e703e24d MainThread iperf(1/1) INFO     Provisioning resources for benchmark iperf
2023-08-22 06:23:14,499 e703e24d MainThread iperf(1/1) INFO     Running: gcloud config list --format=json
2023-08-22 06:23:14,500 e703e24d MainThread iperf(1/1) ERROR    Error during benchmark iperf
Traceback (most recent call last):
  File "/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 808, in RunBenchmark
    DoProvisionPhase(spec, detailed_timer)
  File "/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 427, in DoProvisionPhase
    spec.ConstructVirtualMachines()
  File "/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 569, in ConstructVirtualMachines
    vms = self.ConstructVirtualMachineGroup(group_name, group_spec)
  File "/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 504, in ConstructVirtualMachineGroup
    vm = self._CreateVirtualMachine(group_spec.vm_spec, os_type, cloud)
  File "/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 972, in _CreateVirtualMachine
    return vm_class(vm_spec)
  File "/PerfKitBenchmarker/perfkitbenchmarker/providers/gcp/gce_virtual_machine.py", line 1537, in __init__
    super(BaseLinuxGceVirtualMachine, self).__init__(vm_spec)
  File "/PerfKitBenchmarker/perfkitbenchmarker/providers/gcp/gce_virtual_machine.py", line 501, in __init__
    self.project = vm_spec.project or util.GetDefaultProject()
  File "/PerfKitBenchmarker/perfkitbenchmarker/providers/gcp/util.py", line 62, in GetDefaultProject
    stdout, _, _ = vm_util.IssueCommand(cmd)
  File "/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 417, in IssueCommand
    process = subprocess.Popen(cmd_to_use, env=env, shell=shell_value,
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'gcloud'
2023-08-22 06:23:14,503 e703e24d Thread-2 (_ExecuteBackgroundThreadTasks) iperf(1/1) INFO     Running on pkb-e703e24d-0 via ssh: cat /proc/cpuinfo | grep processor | wc -l
2023-08-22 06:23:14,537 e703e24d Thread-2 (_ExecuteBackgroundThreadTasks) iperf(1/1) INFO     Ran: {ssh -A -p 22 root@metricset-sample-w-0-0.ms.default.svc.cluster.local -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /root/.ssh/id_rsa -o ControlPath="/tmp/%h" -o ControlMaster=auto -o ControlPersist=30m cat /proc/cpuinfo | grep processor | wc -l}
ReturnCode:0
STDOUT: 8

STDERR: 
2023-08-22 06:23:14,569 e703e24d MainThread iperf(1/1) ERROR    Exception running benchmark
Traceback (most recent call last):
  File "/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 1028, in RunBenchmarkTask
    RunBenchmark(spec_for_run, collector)
  File "/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 808, in RunBenchmark
    DoProvisionPhase(spec, detailed_timer)
  File "/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 427, in DoProvisionPhase
    spec.ConstructVirtualMachines()
  File "/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 569, in ConstructVirtualMachines
    vms = self.ConstructVirtualMachineGroup(group_name, group_spec)
  File "/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 504, in ConstructVirtualMachineGroup
    vm = self._CreateVirtualMachine(group_spec.vm_spec, os_type, cloud)
  File "/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 972, in _CreateVirtualMachine
    return vm_class(vm_spec)
  File "/PerfKitBenchmarker/perfkitbenchmarker/providers/gcp/gce_virtual_machine.py", line 1537, in __init__
    super(BaseLinuxGceVirtualMachine, self).__init__(vm_spec)
  File "/PerfKitBenchmarker/perfkitbenchmarker/providers/gcp/gce_virtual_machine.py", line 501, in __init__
    self.project = vm_spec.project or util.GetDefaultProject()
  File "/PerfKitBenchmarker/perfkitbenchmarker/providers/gcp/util.py", line 62, in GetDefaultProject
    stdout, _, _ = vm_util.IssueCommand(cmd)
  File "/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 417, in IssueCommand
    process = subprocess.Popen(cmd_to_use, env=env, shell=shell_value,
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'gcloud'
2023-08-22 06:23:14,570 e703e24d MainThread iperf(1/1) ERROR    Benchmark 1/1 iperf (UID: iperf0) failed. Execution will continue.
2023-08-22 06:23:14,570 e703e24d MainThread iperf(1/1) INFO     Benchmark should not be retried. Finished 1 runs of 1
2023-08-22 06:23:14,571 e703e24d MainThread iperf(1/1) INFO     Benchmark run statuses:
---------------------------------------
Name   UID     Status  Failed Substatus
---------------------------------------
iperf  iperf0  FAILED  UNCATEGORIZED   
---------------------------------------
Success rate: 0.00% (0/1)
2023-08-22 06:23:14,571 e703e24d MainThread iperf(1/1) INFO     Complete logs can be found at: /tmp/perfkitbenchmarker/runs/e703e24d/pkb.log
2023-08-22 06:23:14,571 e703e24d MainThread iperf(1/1) INFO     Completion statuses can be found at: /tmp/perfkitbenchmarker/runs/e703e24d/completion_statuses.json
```

I see that I can set a --cloud https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/975dfdd75f93eaae36565c7cf604eecabcc177ec/perfkitbenchmarker/benchmark_spec.py#L88 from that list of VALID_CLOUDS but I don't want one - I'm running sans a specific provider (and client). If I set to Kubernetes it logically looks for kubectl:

```console
# ./pkb.py --benchmarks=iperf --static_vm_file=static_vms.json --ip_addresses=EXTERNAL --accept_licenses --ssh_control_path="/tmp/%h" --install_packages=false --cloud="Kubernetes"
2023-08-22 06:30:12,506 a4423932 MainThread INFO     Verbose logging to: /tmp/perfkitbenchmarker/runs/a4423932/pkb.log
2023-08-22 06:30:12,506 a4423932 MainThread INFO     PerfKitBenchmarker version: v1.12.0-4093-g975dfdd7
2023-08-22 06:30:12,508 a4423932 MainThread INFO     Flag values:
--ssh_control_path=/tmp/%h
--ip_addresses=EXTERNAL
--cloud=Kubernetes
--accept_licenses
--benchmarks=iperf
--static_vm_file=static_vms.json
--noinstall_packages
2023-08-22 06:30:12,932 a4423932 MainThread INFO     Running: ssh-keygen -t rsa -N  -m PEM -q -f /tmp/perfkitbenchmarker/runs/a4423932/perfkitbenchmarker_keyfile
2023-08-22 06:30:13,981 a4423932 MainThread INFO     Ran: {ssh-keygen -t rsa -N  -m PEM -q -f /tmp/perfkitbenchmarker/runs/a4423932/perfkitbenchmarker_keyfile}
ReturnCode:0
STDOUT: 
STDERR: 
2023-08-22 06:30:13,982 a4423932 MainThread INFO     Setting --max_concurrent_threads=200.
2023-08-22 06:30:14,006 a4423932 MainThread WARNING  The key "flags" was not in the default config, but was in user overrides. This may indicate a typo.
2023-08-22 06:30:14,053 a4423932 MainThread INFO     
-------------------------------------------------------------------------------------
Starting benchmark 1/1 iperf (UID: iperf0) attempt 1 of 1
-------------------------------------------------------------------------------------
2023-08-22 06:30:14,054 a4423932 MainThread iperf(1/1) INFO     Provisioning resources for benchmark iperf
2023-08-22 06:30:14,056 a4423932 Thread-3 (_ExecuteBackgroundThreadTasks) iperf(1/1) INFO     VM: metricset-sample-w-0-0.ms.default.svc.cluster.local (None)
2023-08-22 06:30:14,056 a4423932 Thread-2 (_ExecuteBackgroundThreadTasks) iperf(1/1) INFO     About to create a pod with the following configuration:
2023-08-22 06:30:14,056 a4423932 Thread-3 (_ExecuteBackgroundThreadTasks) iperf(1/1) INFO     Waiting for boot completion.
2023-08-22 06:30:14,056 a4423932 Thread-2 (_ExecuteBackgroundThreadTasks) iperf(1/1) INFO     {"kind": "Pod", "apiVersion": "v1", "metadata": {"name": "pkb-a4423932-1", "labels": {"pkb": "pkb-a4423932-1", "pkb_anti_affinity": ""}}, "spec": {"volumes": [], "containers": [{"image": "ubuntu:20.04", "name": "pkb-a4423932-1", "workingDir": "/root", "securityContext": {"privileged": true}, "volumeMounts": [], "command": ["tail", "-f", "/dev/null"]}], "dnsPolicy": "ClusterFirst", "tolerations": [{"key": "kubernetes.io/arch", "operator": "Exists", "effect": "NoSchedule"}], "nodeSelector": {"pkb_nodepool": "vm2"}, "affinity": {"podAntiAffinity": {"requiredDuringSchedulingIgnoredDuringExecution": [{"labelSelector": {"matchExpressions": [{"key": "pkb_anti_affinity", "operator": "In", "values": [""]}]}, "topologyKey": "kubernetes.io/hostname"}]}}}}
2023-08-22 06:30:14,057 a4423932 Thread-3 (_ExecuteBackgroundThreadTasks) iperf(1/1) INFO     Running on pkb-a4423932-0 via ssh: hostname
2023-08-22 06:30:14,057 a4423932 Thread-2 (_ExecuteBackgroundThreadTasks) iperf(1/1) INFO     Running: kubectl --kubeconfig=/tmp/perfkitbenchmarker/runs/a4423932/kubeconfig1 create -f /tmp/tmpcgfun46g
2023-08-22 06:30:14,061 a4423932 Thread-2 (_ExecuteBackgroundThreadTasks) iperf(1/1) INFO     Retrying exception running IssueRetryableCommand: [Errno 2] No such file or directory: 'kubectl'
2023-08-22 06:30:14,071 a4423932 Thread-3 (_ExecuteBackgroundThreadTasks) iperf(1/1) INFO     Ran: {ssh -A -p 22 root@metricset-sample-w-0-0.ms.default.svc.cluster.local -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /root/.ssh/id_rsa -o ControlPath="/tmp/%h" -o ControlMaster=auto -o ControlPersist=30m hostname}
ReturnCode:0
STDOUT: metricset-sample-w-0-0.ms.default.svc.cluster.local

STDERR: 
2023-08-22 06:30:33,462 a4423932 Thread-2 (_ExecuteBackgroundThreadTasks) iperf(1/1) INFO     Running: kubectl --kubeconfig=/tmp/perfkitbenchmarker/runs/a4423932/kubeconfig1 create -f /tmp/tmpcgfun46g
2023-08-22 06:30:33,463 a4423932 Thread-2 (_ExecuteBackgroundThreadTasks) iperf(1/1) INFO     Retrying exception running IssueRetryableCommand: [Errno 2] No such file or directory: 'kubectl'
```

And that would work if I installed it and exposed an in-cluster config, but I'm not wanting to do that. Is this use case not supported? I basically want to run benchmarks on VMs I have ssh access to without the extra expectation of cloud clients. Thanks!

**Comment by vsoch** [comment]
And when I try that, I had to add a role and role binding (not ideal) along with installing kubectl, but I still get:

```console
root@metricset-sample-l-0-0:/PerfKitBenchmarker# ./pkb.py --benchmarks=iperf --static_vm_file=static_vms.json --ip_addresses=EXTERNAL --accept_licenses --ssh_control_path="/tmp/%h" --install_packages=false --cloud="Kubernetes"
2023-08-22 17:20:07,024 7d089812 MainThread INFO     Verbose logging to: /tmp/perfkitbenchmarker/runs/7d089812/pkb.log
2023-08-22 17:20:07,024 7d089812 MainThread INFO     PerfKitBenchmarker version: v1.12.0-4093-g975dfdd7
2023-08-22 17:20:07,026 7d089812 MainThread INFO     Flag values:
--ssh_control_path=/tmp/%h
--ip_addresses=EXTERNAL
--cloud=Kubernetes
--accept_licenses
--benchmarks=iperf
--static_vm_file=static_vms.json
--noinstall_packages
2023-08-22 17:20:07,508 7d089812 MainThread INFO     Running: ssh-keygen -t rsa -N  -m PEM -q -f /tmp/perfkitbenchmarker/runs/7d089812/perfkitbenchmarker_keyfile
2023-08-22 17:20:09,821 7d089812 MainThread INFO     Ran: {ssh-keygen -t rsa -N  -m PEM -q -f /tmp/perfkitbenchmarker/runs/7d089812/perfkitbenchmarker_keyfile}
ReturnCode:0
STDOUT: 
STDERR: 
2023-08-22 17:20:09,822 7d089812 MainThread INFO     Setting --max_concurrent_threads=200.
2023-08-22 17:20:09,857 7d089812 MainThread WARNING  The key "flags" was not in the default config, but was in user overrides. This may indicate a typo.
2023-08-22 17:20:09,871 7d089812 MainThread INFO     
-------------------------------------------------------------------------------------
Starting benchmark 1/1 iperf (UID: iperf0) attempt 1 of 1
-------------------------------------------------------------------------------------
2023-08-22 17:20:09,872 7d089812 MainThread iperf(1/1) INFO     Provisioning resources for benchmark iperf
2023-08-22 17:20:09,874 7d089812 Thread-3 (_ExecuteBackgroundThreadTasks) iperf(1/1) INFO     VM: metricset-sample-w-0-0.ms.default.svc.cluster.local (None)
2023-08-22 17:20:09,874 7d089812 Thread-2 (_ExecuteBackgroundThreadTasks) iperf(1/1) INFO     About to create a pod with the following configuration:
2023-08-22 17:20:09,875 7d089812 Thread-3 (_ExecuteBackgroundThreadTasks) iperf(1/1) INFO     Waiting for boot completion.
2023-08-22 17:20:09,875 7d089812 Thread-2 (_ExecuteBackgroundThreadTasks) iperf(1/1) INFO     {"kind": "Pod", "apiVersion": "v1", "metadata": {"name": "pkb-7d089812-1", "labels": {"pkb": "pkb-7d089812-1", "pkb_anti_affinity": ""}}, "spec": {"volumes": [], "containers": [{"image": "ubuntu:20.04", "name": "pkb-7d089812-1", "workingDir": "/root", "securityContext": {"privileged": true}, "volumeMounts": [], "command": ["tail", "-f", "/dev/null"]}], "dnsPolicy": "ClusterFirst", "tolerations": [{"key": "kubernetes.io/arch", "operator": "Exists", "effect": "NoSchedule"}], "nodeSelector": {"pkb_nodepool": "vm2"}, "affinity": {"podAntiAffinity": {"requiredDuringSchedulingIgnoredDuringExecution": [{"labelSelector": {"matchExpressions": [{"key": "pkb_anti_affinity", "operator": "In", "values": [""]}]}, "topologyKey": "kubernetes.io/hostname"}]}}}}
2023-08-22 17:20:09,875 7d089812 Thread-3 (_ExecuteBackgroundThreadTasks) iperf(1/1) INFO     Running on pkb-7d089812-0 via ssh: hostname
2023-08-22 17:20:09,877 7d089812 Thread-2 (_ExecuteBackgroundThreadTasks) iperf(1/1) INFO     Running: kubectl --kubeconfig=/tmp/perfkitbenchmarker/runs/7d089812/kubeconfig1 create -f /tmp/tmph2jshq2h
2023-08-22 17:20:09,892 7d089812 Thread-3 (_ExecuteBackgroundThreadTasks) iperf(1/1) INFO     Ran: {ssh -A -p 22 root@metricset-sample-w-0-0.ms.default.svc.cluster.local -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /root/.ssh/id_rsa -o ControlPath="/tmp/%h" -o ControlMaster=auto -o ControlPersist=30m hostname}
ReturnCode:0
STDOUT: metricset-sample-w-0-0.ms.default.svc.cluster.local

STDERR: 
2023-08-22 17:20:09,950 7d089812 Thread-2 (_ExecuteBackgroundThreadTasks) iperf(1/1) INFO     Ran: {kubectl --kubeconfig=/tmp/perfkitbenchmarker/runs/7d089812/kubeconfig1 create -f /tmp/tmph2jshq2h}
ReturnCode:1
STDOUT: 
STDERR: error: no openapi getter
```

**Comment by pmkc** [comment]
If you are setting up pods with SSH, you do not want `--cloud=Kuberentes`. That tries to provision VMs via kubectl and is not designed to support static_vms. The default `--cloud=GCP` should work. Once you are using static VMs, the "Cloud" should not matter, but Kubernetes is special.

One other thing to try. Instead of using `--static_vm_file`, I would recommend using a YAML like that that both sets up your static VMs and tells the benchmark to use them using `--benchmark_config_file`.

If you see this example from our [README](https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/#advanced-how-to-run-benchmarks-without-cloud-provisioning-eg-local-workstation)

```
static_vms:
  - &vm1
    ip_address: <ip1>
    user_name: connormccoy
    ssh_private_key: /home/connormccoy/.ssh/google_compute_engine
    internal_ip: 10.240.223.37
    install_packages: false
  - &vm2
    ip_address: <ip2>
    user_name: connormccoy
    ssh_private_key: /home/connormccoy/.ssh/google_compute_engine
    internal_ip: 10.240.234.189
    ssh_port: 2222

iperf:
  vm_groups:
    vm_1:
      static_vms:
        - *vm2
    vm_2:
      static_vms:
        - *vm1
```

**Comment by vsoch** [comment]
Thanks @pmkc I will try this out! I have a lot on my queue at the moment, but will definitely get to it - but just a heads up I won't have feedback right away.

**Comment by dlott** [comment]
Closing due to inactivity.  Please feel free to reopen if you have more feedback.
