### ISSUE TITLE
Unpickle spec file failed

### ISSUE THREAD

**Issue by yuyantingzero** [GoogleCloudPlatform/PerfKitBenchmarker#468]
When running benchmark with prepare/run stage, I get following error:
yuyanting@yuyanting-linux:~/PerfKitBenchmarker$ ./pkb.py --benchmarks=unixbench --run_stage=run --run_uri=817e836c                                                                                                
2015-09-10 11:03:54,038 817e836c MainThread INFO     Verbose logging to: /tmp/perfkitbenchmarker/run_817e836c/pkb.log
2015-09-10 11:03:54,038 817e836c MainThread INFO     Flag values:
--run_stage=run
--run_uri=817e836c
--benchmarks=unixbench
2015-09-10 11:03:54,041 817e836c MainThread unixbench(1/1) ERROR    Unable to unpickle spec file for benchmark unixbench.
2015-09-10 11:03:54,041 817e836c MainThread unixbench(1/1) ERROR    Error during benchmark unixbench
Traceback (most recent call last):
  File "/usr/local/google/home/yuyanting/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 296, in RunBenchmark
    spec = benchmark_spec.BenchmarkSpec.GetSpecFromFile(benchmark_name)
  File "/usr/local/google/home/yuyanting/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 387, in GetSpecFromFile
    raise e
TypeError: allocate_lock() takes no arguments (1 given)
2015-09-10 11:03:54,043 817e836c MainThread unixbench(1/1) INFO     Complete logs can be found at: /tmp/perfkitbenchmarker/run_817e836c/pkb.log
Traceback (most recent call last):
  File "./pkb.py", line 21, in <module>
    sys.exit(Main())
  File "/usr/local/google/home/yuyanting/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 482, in Main
    return RunBenchmarks()
  File "/usr/local/google/home/yuyanting/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 425, in RunBenchmarks
    RunBenchmark(benchmark, collector, sequence_counter, total_benchmarks)
  File "/usr/local/google/home/yuyanting/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 296, in RunBenchmark
    spec = benchmark_spec.BenchmarkSpec.GetSpecFromFile(benchmark_name)
  File "/usr/local/google/home/yuyanting/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 387, in GetSpecFromFile
    raise e
TypeError: allocate_lock() takes no arguments (1 given)

**Comment by ehankland** [comment]
Fixed in https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/471
