### ISSUE TITLE
Cassandra stress advertises that it doesn't require disks

### ISSUE THREAD

**Issue by cmccoy** [GoogleCloudPlatform/PerfKitBenchmarker#490]
But it does:

https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/master/perfkitbenchmarker/benchmarks/cassandra_stress_benchmark.py#L97-L108

See #475.

**Comment by mateusz-blaszkowski** [comment]
I had a chance to debug the issue further. It's not so much about advertising if it requires scratch disk or not (it's P2). In Kubernetes (and all the Docker based clouds like Mesos+Marathon) you cannot attach a volume to already running instance. Cassandra_stress benchmark is a specific benchmark because it (as the only one) calls  CreateScratchDisk() method (see cassandra_stress_benchmark.py:114). And it does this _after_ instance creation what makes it impossible for Kubernetes to use this benchmark. And that's P0 or P1 IMO - taking into consideration that we plan to add support for other Docker based clouds. Maybe with the configs functionality we could somehow create disk_specs for some of the instances _before_ the instances are created. This way disks for Kubernetes would be automatically created in _CreateDependencies phase. 

I'm attaching PKB output from cassandra_stress benchmark:

```
2015-10-15 10:52:40,918 1cf4c0b0 Thread-91 cassandra_stress(1/1) INFO     Running: ssh -A -p 30505 root@10.102.17.41 -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /tmp/perfkitbenchmarker/run_1cf4c0b0/perfkitbenchmarker_keyfile cd /tmp/pkb/apache-cassandra/lib && curl -LJO https://maven.java.net/content/repositories/releases/net/java/dev/jna/jna/4.1.0/jna-4.1.0.jar
2015-10-15 10:52:53,063 1cf4c0b0 MainThread cassandra_stress(1/1) ERROR    Exception occurred while calling Configure(10.102.17.41, seed_vms=[<BaseVirtualMachine [ip=10.102.17.41, internal_ip=10.3.204.31]>]):
Traceback (most recent call last):
  File "/root/mateuszb/perfkit_ww42_4/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 227, in _ExecuteThreadCall
    queue.put(ThreadCallResult(call_id, target(*args, **kwargs), None))
  File "/root/mateuszb/perfkit_ww42_4/PerfKitBenchmarker/perfkitbenchmarker/packages/cassandra.py", line 95, in Configure
    'data_path': posixpath.join(vm.GetScratchDir(), 'cassandra'),
  File "/root/mateuszb/perfkit_ww42_4/PerfKitBenchmarker/perfkitbenchmarker/virtual_machine.py", line 154, in GetScratchDir
    disk_num, len(self.scratch_disks)))
Error: GetScratchDir(disk_num=0) is invalid, max disk_num is 0
```

As you can see, scratch_disks array is of size 0. In Kubernetes provider CreateScratchDisk() is not implemented (as it makes no sense to call this method after the instance is created). That's why scratch_disks is not populated.

Thanks,
Mateusz

**Comment by cmccoy** [comment]
Ah, I understand. I'll have a look at this today.

**Comment by cmccoy** [comment]
#549 should fix this. @mateusz-blaszkowski : let me know if you continue encountering issues.
