### ISSUE TITLE
object_storage_service_benchmark Unexpected test outcome from OneByteRW

### ISSUE THREAD

**Issue by pdeyhim** [GoogleCloudPlatform/PerfKitBenchmarker#5427]
Command: pkb.py --benchmarks object_storage_service --cloud=AWS --object_storage_region us-west-2 --benchmark_config_file=config

I've seen this error in the previous versions and I vaguely remember I had to change the regex logic. 

Traceback (most recent call last):
  File "/Users/parviz.deyhim/dev/junk/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 1352, in RunBenchmarkTask
    RunBenchmark(spec_for_run, collector)
  File "/Users/parviz.deyhim/dev/junk/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 1085, in RunBenchmark
    DoRunPhase(spec, collector, detailed_timer)
  File "/Users/parviz.deyhim/dev/junk/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 786, in DoRunPhase
    samples = spec.BenchmarkRun(spec)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parviz.deyhim/dev/junk/PerfKitBenchmarker/perfkitbenchmarker/linux_benchmarks/object_storage_service_benchmark.py", line 1959, in Run
    benchmark(
  File "/Users/parviz.deyhim/dev/junk/PerfKitBenchmarker/perfkitbenchmarker/linux_benchmarks/object_storage_service_benchmark.py", line 935, in OneByteRWBenchmark
    raise ValueError(
ValueError: Unexpected test outcome from OneByteRW api test: INFO:root:Storage provider is S3, bucket is pkb6499a05c, scenario is OneByteRW
INFO:botocore.credentials:Found credentials from IAM Role: test
INFO:root:Individual results of one byte upload:
INFO:root:0.074227
INFO:root:0.016868
INFO:root:0.015615
INFO:root:0.016691
INFO:root:0.018713
INFO:root:0.017808
INFO:root:0.017709
INFO:root:0.019638
.....

**Comment by pdeyhim** [comment]
search string ends up being: One byte MultistreamOperationType.upload 

not sure why enum is not getting converted
