### ISSUE TITLE
Unresolved dependency: requests.packages

### ISSUE THREAD

**Issue by mateusz-blaszkowski** [GoogleCloudPlatform/PerfKitBenchmarker#560]
After CloudStack provider merge, I have the following traceback right after running any benchmark:

```
Traceback (most recent call last):
  File "pkb.py", line 19, in <module>
    from perfkitbenchmarker.pkb import Main
  File "/root/mateuszb/perfkit_ww43_2/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 63, in <module>
    from perfkitbenchmarker import benchmarks
  File "/root/mateuszb/perfkit_ww43_2/PerfKitBenchmarker/perfkitbenchmarker/benchmarks/__init__.py", line 26, in <module>
    BENCHMARKS = _LoadBenchmarks()
  File "/root/mateuszb/perfkit_ww43_2/PerfKitBenchmarker/perfkitbenchmarker/benchmarks/__init__.py", line 24, in _LoadBenchmarks
    return list(import_util.LoadModulesForPath(__path__, __name__))
  File "/root/mateuszb/perfkit_ww43_2/PerfKitBenchmarker/perfkitbenchmarker/import_util.py", line 40, in LoadModulesForPath
    yield importlib.import_module(modname)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/root/mateuszb/perfkit_ww43_2/PerfKitBenchmarker/perfkitbenchmarker/benchmarks/mysql_service_benchmark.py", line 35, in <module>
    from perfkitbenchmarker import benchmark_spec as benchmark_spec_class
  File "/root/mateuszb/perfkit_ww43_2/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 36, in <module>
    from perfkitbenchmarker.cloudstack import cloudstack_network as cs_nw
  File "/root/mateuszb/perfkit_ww43_2/PerfKitBenchmarker/perfkitbenchmarker/cloudstack/cloudstack_network.py", line 18, in <module>
    from perfkitbenchmarker.cloudstack import util
  File "/root/mateuszb/perfkit_ww43_2/PerfKitBenchmarker/perfkitbenchmarker/cloudstack/util.py", line 21, in <module>
    from requests.packages import urllib3
ImportError: No module named packages
```

Adding `requests>=2.5.1` to `requirements.txt` solves the issue, but I'm not sure if that's the way you want to fix this.

**Comment by cmccoy** [comment]
@syed - could you take a look at this?

**Comment by syed** [comment]
This is because there are two versions of requests in Ubuntu. `pip` installs in `/usr/local/lib/python2.7/` whereas there is an OS owned `requests` in `/usr/lib/python2.7/`. You can fix this by 

```
sudo apt-get remove python-requests
```

**Comment by cmccoy** [comment]
I don't see a requests version specified in our [`requirements.txt`](https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/master/requirements.txt) or [`csapi`'s `setup.py`](https://github.com/swill/csapi/blob/master/setup.py#L29); without that a user with an incompatible version of `requests` will appear to meet all specified dependencies, which is wrong.  We should specify a version.

**Comment by cmccoy** [comment]
Alternatively, if `urllib3` is just imported to disable warnings, perhaps we could make that step more robust to different requests versions?

```{python}
try:
   from requests.packages import urllib3
   urllib3.disable_warnings()
except ImportError:
  pass
```

**Comment by syed** [comment]
I agree @cmccoy. I'll send a PR to fix this
