### ISSUE TITLE
Failed cloudsuite_web_serving

### ISSUE THREAD

**Issue by ehankland** [GoogleCloudPlatform/PerfKitBenchmarker#696]
One run of cloudsuite_web_serving ultimately failed with this:
```
RemoteCommandError: Got non-zero return code (1) executing cd /tmp/pkb/out1 && cd $(ls -Art | tail -n 1) && cat summary.xml
Full command: ssh -A -p 22 perfkit@130.211.138.42 -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /tmp/perfkitbenchmarker/run_21a0e34a/perfkitbenchmarker_keyfile cd /tmp/pkb/out1 && cd $(ls -Art | tail -n 1) && cat summary.xml
STDOUT: STDERR: Warning: Permanently added '130.211.138.42' (ECDSA) to the list of known hosts.^M
cat: summary.xml: No such file or directory
```
Before that, there were many messages that looked like this:
```
Dec 03, 2015 2:38:32 AM sun.rmi.transport.tcp.TCPTransport$AcceptLoop executeAcceptLoop
WARNING: RMI TCP Accept-0: accept loop for ServerSocket[addr=localhost/127.0.0.1,localport=41444] throws
java.net.SocketException: Too many open files
        at java.net.PlainSocketImpl.socketAccept(Native Method)
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:398)
        at java.net.ServerSocket.implAccept(ServerSocket.java:530)
        at java.net.ServerSocket.accept(ServerSocket.java:498)
        at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:399)
        at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:371)
        at java.lang.Thread.run(Thread.java:745)
```
And before that many of these:
```
Dec 03, 2015 2:20:36 AM com.sun.faban.driver.engine.AgentThread logError
WARNING: UIDriverAgent[1].291.doAddPerson: org/json/JSONException
Note: Error not counted in result.
Either transaction start or end time is not within steady state.
java.lang.NoClassDefFoundError: org/json/JSONException
        at org.apache.olio.workload.driver.UIDriver.preparePerson(UIDriver.java:892)
        at org.apache.olio.workload.driver.UIDriver.doAddPerson(UIDriver.java:560)
        at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.sun.faban.driver.engine.TimeThread.doRun(TimeThread.java:169)
        at com.sun.faban.driver.engine.AgentThread.run(AgentThread.java:202)
Caused by: java.lang.ClassNotFoundException: org.json.JSONException
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 7 more

```
I was running with these flags:
```
--machine_type=n1-standard-8
--zones=us-central1-c
--cloud=GCP
--benchmarks=cloudsuite_web_serving
```
Another run using the same flags passed, so this doesn't happen every time

**Comment by voellm** [comment]
@rmend016 
@Vukasin92 

Can one of you look into this?  Have you seen this issue before?

**Comment by peterfeiner** [comment]
@nooshin-mirzadeh, does this bug look familiar? It persists with the latest cloudsuite images.
