### ISSUE TITLE
cloudsuite_websearch failure

### ISSUE THREAD

**Issue by ehankland** [GoogleCloudPlatform/PerfKitBenchmarker#698]
I got this error:
```
Dec 03, 2015 1:18:20 AM com.sun.faban.driver.engine.TimeThread doRun
SEVERE: SearchDriverAgent[0].11: Error initializing driver object.
java.lang.NullPointerException
        at com.sun.org.apache.xml.internal.dtm.ref.dom2dtm.DOM2DTM.getLocalName(DOM2DTM.java:1035)
        at com.sun.org.apache.xpath.internal.patterns.NodeTest.execute(NodeTest.java:578)
        at com.sun.org.apache.xpath.internal.axes.PredicatedNodeTest.acceptNode(PredicatedNodeTest.java:472)
        at com.sun.org.apache.xpath.internal.axes.AxesWalker.nextNode(AxesWalker.java:374)
        at com.sun.org.apache.xpath.internal.axes.WalkingIterator.nextNode(WalkingIterator.java:197)
        at com.sun.org.apache.xpath.internal.axes.NodeSequence.nextNode(NodeSequence.java:344)
        at com.sun.org.apache.xpath.internal.axes.NodeSequence.item(NodeSequence.java:539)
        at com.sun.org.apache.xpath.internal.objects.XNodeSet.str(XNodeSet.java:281)
        at com.sun.org.apache.xpath.internal.jaxp.XPathImpl.getResultAsType(XPathImpl.java:309)
        at com.sun.org.apache.xpath.internal.jaxp.XPathImpl.evaluate(XPathImpl.java:274)
        at com.sun.org.apache.xpath.internal.jaxp.XPathImpl.evaluate(XPathImpl.java:363)
        at com.sun.faban.driver.engine.DriverContext.getXPathValue(DriverContext.java:412)
        at sample.searchdriver.SearchDriver.<init>(SearchDriver.java:83)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at java.lang.Class.newInstance(Class.java:383)
        at com.sun.faban.driver.engine.TimeThread.doRun(TimeThread.java:73)
        at com.sun.faban.driver.engine.AgentThread.run(AgentThread.java:202)

Dec 03, 2015 1:18:21 AM com.sun.faban.driver.engine.AgentImpl kill
WARNING: SearchDriverAgent[0]: Killing benchmark run
Dec 03, 2015 1:18:21 AM com.sun.faban.driver.engine.MasterImpl$2 run
SEVERE: Run aborted. Master terminating!

```
I ran with these flags:
```
--machine_type=n1-standard-8
--zones=us-central1-c
--cloud=GCP
--benchmarks=cloudsuite_websearch
```

**Comment by voellm** [comment]
@rmend016 
@Vukasin92

Can one of you look into this? Have you seen this issue before?

**Comment by Vukasin92** [comment]
Does it happen every time? I checked files here http://lsi-www.epfl.ch/parsa/search.tar.gz (if you haven't seen them, take a look, there is the implementation of faban driver), and it seems that faban driver failed to get context (and instead returned NULL) which raises an exception. But have no idea why it happened. I will see if someone who is currently at epfl can take a look also.
