### ISSUE TITLE
redis failure 

### ISSUE THREAD

**Issue by ctlaltlaltc** [GoogleCloudPlatform/PerfKitBenchmarker#701]
```
2015-12-08 21:50:58,994 d522d1f8 MainThread redis(7/13) redis_benchmark.py:171 ERROR    {0: (0.0, 0.0)}
2015-12-08 21:50:58,995 d522d1f8 MainThread redis(7/13) pkb.py:373 ERROR    Error during benchmark redis
Traceback (most recent call last):
  File "/root/cloud_tp/src/perfkitbenchmarker/perfkitbenchmarker/pkb.py", line 348, in RunBenchmark
    DoRunPhase(benchmark, benchmark_name, spec, collector, detailed_timer)
  File "/root/cloud_tp/src/perfkitbenchmarker/perfkitbenchmarker/pkb.py", line 249, in DoRunPhase
  File "/root/cloud_tp/src/perfkitbenchmarker/perfkitbenchmarker/linux_benchmarks/redis_benchmark.py", line 175, in Run
    latency += result[1] * result[0] / throughput
ZeroDivisionError: float division by zero   
```

**Comment by cmccoy** [comment]
It looks like no requests succeeded between the client and server. What provider were you using? If you were using static machines, was there connectivity between them?

I've opened #702 to make the error message a bit clearer.

**Comment by voellm** [comment]
Marking this a P2 because we are planning to deprecate this in favor of redis_ycsb.  We will keep this around but the fix is not as hit a pri.
