### ISSUE TITLE
Run Benchmarks Without Cloud Provisioning

### ISSUE THREAD

**Issue by kevinchze** [GoogleCloudPlatform/PerfKitBenchmarker#879]
I'm trying to benchmark the connection between different cloud providers and a local server but don't have sudo access and was wondering when is this limitation planned to be removed or if there's  currently anyway way to go around it?

**Comment by voellm** [comment]
The "sudo" requirement comes from the need to install software.  If you have all the needed packages you can always run with "--install_packages=false" and then things wont require sudo access.

flags.DEFINE_bool('install_packages', None,
                  'Override for determining whether packages should be '
                  'installed. If this is false, no packages will be installed '
                  'on any VMs. This option should probably only ever be used '
                  'if you have already created an image with all relevant '
                  'packages installed.')

If you have a specific benchmark you would like to run I can help you get the right command line and or config if needed.

You might also find this recent tech talk with example useful here - https://docs.google.com/presentation/d/146bK4EP59Dh2vQEjAeECSjp-IJD6eFVwPvXLSTtS9LY/edit

**Comment by kevinchze** [comment]
Hi @voellm ,

Thanks for the quick response! I'm running iperf to find out the network performance between the local server and the different Clouds. 

I can get the packages installed from my admin's part, but as I understand, I could run the whole thing using the following command:

./pkb.py --benchmarks=iperf --benchmark_config_file=iperf.yaml --install_packages=false

Would you be able to advise on the packages I'll need for this? Is it only the iperf package and it's dependencies and if so, which version of iperf (the link for the iperf BSD License directs to a deprecated version)?

Thanks again

**Comment by voellm** [comment]
Even easier...

Create a file called myserver.json like below - you need one entry per
machine needed for the benchmark otherwise the benchmark will pull
remaining machine from the default Cloud provider or whatever you specify
with --cloud=<...>.  iperf, netperf need 2 machines so I have two entries
below.

[
 {"ip_address": "173.203.60.1",
  "user_name": "USER1",
  "keyfile_path": "/tmp/static_rsa.pem",
  "zone": "MyZone",
  "install_packages": false},
 {"ip_address": "173.203.60.2",
  "user_name": "USER1",
  "keyfile_path": "/tmp/static_rsa.pem",
  "zone": "MyZone",
  "install_packages": false}
]

Be sure to update the ip_address, user and keyfile_path to point to your
ssh key.

Then run like this....

./pkb.py --benchmarks=iperf --static_vm_file=myserver.json
 --ip_addresses=EXTERNAL

You can also have an internal IP address in the file for VM to VM
benchmarks.  See this wiki for more...
https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/wiki/Can-I-run-PerfKitBenchmarker-on-my-local-machine-or-data-center%3F

The static machine file has an advantage over the full config option in
that it applies to any benchmark.

If you want to use a full config file you can see Eric's instructions in
this bug -
https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/873 and in
the Wiki here -
https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/wiki/PerfkitBenchmarker-Configurations

Please let me know if this resolves your issue.

**Comment by kevinchze** [comment]
Great! Everything seems to run fine until I get the error regarding running iperf on the local VM (getting "Got non-zero return code (1) executing pgrep -n iperf") which I assume is due to the fact iperf is not installed.

Can I ask again which version of iperf is used on Perfkit? Am I correct to assume it's iperf2 since it's using bidirectional testing (and since the BSD Link link at source directs to Sourceforge that asks the user to go to iperf3?)

Thanks!

**Comment by voellm** [comment]
iperf2

Do you have a more specific error?

**Comment by kevinchze** [comment]
Thanks. 

This is the error I get:

2016-03-11 01:47:04,259 f4129cce MainThread iperf(1/1) ERROR    Error during benchmark iperf
Traceback (most recent call last):
  File "/pathto/Project/PerfKitBenchmarker-1.2.0/perfkitbenchmarker/pkb.py", line 375, in RunBenchmark
    DoPreparePhase(benchmark, benchmark_name, spec, detailed_timer)
  File "/pathto/Project/PerfKitBenchmarker-1.2.0/perfkitbenchmarker/pkb.py", line 241, in DoPreparePhase
    benchmark.Prepare(spec)
  File "/pathto/Project/PerfKitBenchmarker-1.2.0/perfkitbenchmarker/linux_benchmarks/iperf_benchmark.py", line 79, in Prepare
    stdout, _ = vm.RemoteCommand('pgrep -n iperf')
  File "/pathto/Project/PerfKitBenchmarker-1.2.0/perfkitbenchmarker/linux_virtual_machine.py", line 313, in RemoteCommand
    suppress_warning, timeout)
  File "/pathto/PerfKitBenchmarker-1.2.0/perfkitbenchmarker/linux_virtual_machine.py", line 374, in RemoteHostCommand
    raise errors.VirtualMachine.RemoteCommandError(error_text)
RemoteCommandError: Got non-zero return code (1) executing pgrep -n iperf
Full command: ssh -A -p 22 1.1.1.1.1 -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /path/to/privatekey pgrep -n iperf

When running the netperf benchmark I essentially get the exact same error with netperf instead of iperf so that's why I'm assuming that the local server has no iperf installed.

Another question you probably know the answer to, what are the differences between netperf and iperf? I see in the examples that netperf is used for network benchmarking between cloud providers (cross-cloud) where as iperf seems to be used for everything else, any particular reason for this?

**Comment by voellm** [comment]
Are they in your default path?  Meaning does the account PKB logs into have
them?

Can you try a "where iperf" and the "pgrep -n iperf" and share the result?

Thanks.
