### ISSUE TITLE
aerospike-client-c patch fails

### ISSUE THREAD

**Issue by mlpesant** [GoogleCloudPlatform/PerfKitBenchmarker#974]
After fixing multiple issues to run aerospike (with PerfKitBenchmarker) on PPC64le, I'm running into this issue with a patch.  I am using the latest versions of PerfKit and Aerospike.  Can anybody help with this?  I haven't done much poking yet to see what's in this patch.  Thanks!

```
root@015d33095dc0:/tmp/pkb# cd aerospike-client-c/benchmarks/src/main && patch -p1 -f  < aerospike.patch
patching file latency.c
Hunk #1 FAILED at 31.
Hunk #2 succeeded at 59 with fuzz 2 (offset 1 line).
Hunk #3 succeeded at 140 (offset 1 line).
1 out of 3 hunks FAILED -- saving rejects to file latency.c.rej
patching file latency.h
Hunk #1 succeeded at 27 with fuzz 1.

```

**Comment by ehankland** [comment]
Hi - did you get a chance to try the patch file I suggested in https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/918 ? If its still failing with that one, let me know and I can try to help further.

**Comment by mlpesant** [comment]
@ehankland, thanks for your comment.  I didn't know anything about a patch file back in March so I paid no notice to that...  I tried replacing the contents of /home/ubuntu/PerfKitBenchmarker/perfkitbenchmarker/data/aerospike.patch   with what you had in #918 but I still get the same error :-(  How can I help you help me?  Thanks!

2016-04-27 17:52:58,313 c4898a6b Thread-22 aerospike(1/1) INFO     Ran ssh -A -p 22 ubuntu@9.40.200.241 -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /home/ubuntu/.ssh/id_rsa sudo docker exec 85570aaf4f924e635777be4862ece7717a504c0fea3f8c1644b0e167b8559b72 bash -c 'cd aerospike-client-c/benchmarks/src/main && patch -p1 -f  < aerospike.patch'. Got return code (1).
STDOUT: patching file latency.c
Hunk #1 FAILED at 31.
Hunk #2 FAILED at 58.
Hunk #3 FAILED at 137.
3 out of 3 hunks FAILED -- saving rejects to file latency.c.rej
patching file latency.h
Hunk #1 FAILED at 27.
1 out of 1 hunk FAILED -- saving rejects to file latency.h.rej

**Comment by ehankland** [comment]
Can you try out https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/978 (it works for me)? I'm not sure why the patch failed - its possible your text editor might have messed up the spaces in the patch file and patch didn't like it (or if you are no longer targeting version 4.0.4 that could also explain it).

**Comment by mlpesant** [comment]
I am still targeting version 4.0.4 and the patch in #978 worked.  Woohoo!!!!!  Is there something we need to do to make this working patch the default for new downloads?  
On a sad note, now that it gets passed that patch, it's failing with the following error...  Should I open a different defect for this or do you have any comments?  Thanks!

```
2016-04-27 21:57:08,266 7703cd81 MainThread aerospike(1/1) ERROR    Error during benchmark aerospike
Traceback (most recent call last):
  File "/home/ubuntu/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 376, in RunBenchmark
    detailed_timer)
  File "/home/ubuntu/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 260, in DoRunPhase
    samples = benchmark.Run(spec)
  File "/home/ubuntu/PerfKitBenchmarker/perfkitbenchmarker/linux_benchmarks/aerospike_benchmark.py", line 166, in Run
    (CLIENT_DIR, ','.join(s.internal_ip for s in servers)))
TypeError: sequence item 0: expected string, NoneType found
```

**Comment by ehankland** [comment]
I think the updated client has issues talking to the old version of the server (hence the other changes in that PR). I've tried running with all of the changes in that PR, and it worked for me (would you mind confirming whether this fixes the issue?). Assuming it works, I can get this merged, or you could pull in the changes to your own PR - it's up to you.

**Comment by ehankland** [comment]
Ah - I didn't look at the above error in detail... that doesn't look like the problem I mentioned. It might be a problem with pulling in the latest changes/merge conflicts - like I said, the PR I mentioned works for me.

**Comment by ehankland** [comment]
Are you running on static VMs? It looks like this error is caused because the VM doesn't have an internal ip - if that's the case, supplying the ip in the static vm file (or config file if that's what you are using) should fix it.

**Comment by mlpesant** [comment]
Sorry, was having issues with docker that I had to solve before getting back to this point.  I am running on static VMs with the latest release of PerfKitBenchmarker (v1.4.0-68-g8dd20c1), and pulling version 3.8.1 of aerospike-server  and 4.0.4 of aerospike-client-c instead of the older defaults.  If I run the default path in the latest version of PerfKitBenchmarker I get the following error:
```
2016-05-02 21:56:12,958 e1bf433c Thread-22 aerospike(1/1) INFO     Ran ssh -A -p 22 ubuntu@9.40.200.243 -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /home/ubuntu/.ssh/id_rsa sudo docker exec 9e46fb63f9f6bd51ed4cf3fc13173d2e63ebfdfa2852baa80311d8a45dc9d4fa bash -c 'cd aerospike-client-c/benchmarks/src/main && patch -p1 -f  < aerospike.patch'. Got return code (1).
STDOUT: patching file latency.c
Hunk #1 FAILED at 31.
Hunk #2 succeeded at 59 with fuzz 2 (offset 1 line).
Hunk #3 succeeded at 140 (offset 1 line).
1 out of 3 hunks FAILED -- saving rejects to file latency.c.rej
patching file latency.h
Hunk #1 succeeded at 27 with fuzz 1.
```
After using the patch I copied from #978, it gets further but fails with the following error
```
2016-05-02 22:06:24,763 6776c54c MainThread aerospike(1/1) ERROR    Error during benchmark aerospike
Traceback (most recent call last):
  File "/home/ubuntu/PerfKitBenchmarker.new/perfkitbenchmarker/pkb.py", line 472, in RunBenchmark
    detailed_timer)
  File "/home/ubuntu/PerfKitBenchmarker.new/perfkitbenchmarker/pkb.py", line 365, in DoRunPhase
    samples = benchmark.Run(spec)
  File "/home/ubuntu/PerfKitBenchmarker.new/perfkitbenchmarker/linux_benchmarks/aerospike_benchmark.py", line 166, in Run
    (CLIENT_DIR, ','.join(s.internal_ip for s in servers)))
TypeError: sequence item 0: expected string, NoneType found
```
I am running on static vms and this is the command I'm using
`./pkb.py --static_vm_file=tul121p1.json --benchmarks=aerospike --os_type=ubuntu_container --image=ppc64le/ubuntu`

These are the contents of tul121p1.json

[
  {
    "ip_address": "9.40.200.243",
    "user_name": "ubuntu",
    "keyfile_path": "/home/ubuntu/.ssh/id_rsa",
    "os_type": "ubuntu_container"
  },

  {
    "ip_address": "9.40.200.241",
    "user_name": "ubuntu",
    "keyfile_path": "/home/ubuntu/.ssh/id_rsa",
    "os_type": "ubuntu_container"
  },

  {
    "ip_address": "9.40.200.245",
    "user_name": "ubuntu",
    "keyfile_path": "/home/ubuntu/.ssh/id_rsa",
    "os_type": "ubuntu_container"
  },

  {
    "ip_address": "9.40.200.227",
    "user_name": "ubuntu",
    "keyfile_path": "/home/ubuntu/.ssh/id_rsa",
    "os_type": "ubuntu_container"
  },

  {
    "ip_address": "9.40.200.225",
    "user_name": "ubuntu",
    "keyfile_path": "/home/ubuntu/.ssh/id_rsa",
    "os_type": "ubuntu_container"
  }
]

I also tried removing the 2 extraneous servers from the file but got the exact same error.  What am I missing??

**Comment by ehankland** [comment]
For each of the static VMs, you've supplied the "ip_address" but not the "internal_ip" (i.e. a subnet address). You should be able to use your  9.40.200.* addresses as long as you don't have a firewall blocking the aerospike ports.

Assuming that is the case, your file would look like this:
```
[
{
"ip_address": "9.40.200.243",
"internal_ip": "9.40.200.243",
"user_name": "ubuntu",
"keyfile_path": "/home/ubuntu/.ssh/id_rsa",
"os_type": "ubuntu_container"
},

{
"ip_address": "9.40.200.241",
"internal_ip": "9.40.200.241",
"user_name": "ubuntu",
"keyfile_path": "/home/ubuntu/.ssh/id_rsa",
"os_type": "ubuntu_container"
}
]
```

**Comment by mlpesant** [comment]
@ehankland , thanks so much for your response.  Adding internal_ip to the json file definitely solved that problem.  I am now stuck further down the rabbit hole but I think I need to debug this one on my system and I'll open a separate issue if needed.  Thanks!

```
2016-05-03 13:58:17,233 41e53b55 MainThread aerospike(1/1) INFO     Ran ssh -A -p 22 ubuntu@9.40.200.243 -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /home/ubuntu/.ssh/id_rsa sudo docker exec 1051146a22f6faa137387bd0c60475e6676c71b254daebda431527d7c5792788 bash -c 'timeout 15 ./aerospike-client-c/benchmarks/target/benchmarks -z 8 -n test -w RU,90 -o B:1000 -k 1000000 --latency 5,1 -h 9.40.200.241;:'. Got return code (0).
STDOUT: hosts:          9.40.200.241
port:           3000
user:           (null)
namespace:      test
set:            testset
keys/records:   1000000
object spec:    byte[1000]
random values:  false
minimum number of transactions:  -1
workload:       read 90% write 10%
threads:        8
max throughput: unlimited
read timeout:   0 ms
write timeout:  0 ms
max retries:    1
debug:          false
latency:        5 columns, shift exponent 1
shared memory:  false
read replica:   master
read consistency level: one
write commit level: all
asynchronous mode:  off
2016-05-03 13:58:17 WARN Failed to connect to seed 9.40.200.241:3000. AEROSPIKE_ERR_TIMEOUT 
2016-05-03 13:58:17 ERROR Aerospike connect failed: -1 : Failed to seed cluster

STDERR: Warning: Permanently added '9.40.200.243' (ECDSA) to the list of known hosts.

2016-05-03 13:58:17,239 41e53b55 MainThread aerospike(1/1) ERROR    Error during benchmark aerospike
Traceback (most recent call last):
  File "/home/ubuntu/PerfKitBenchmarker.new/perfkitbenchmarker/pkb.py", line 472, in RunBenchmark
    detailed_timer)
  File "/home/ubuntu/PerfKitBenchmarker.new/perfkitbenchmarker/pkb.py", line 365, in DoRunPhase
    samples = benchmark.Run(spec)
  File "/home/ubuntu/PerfKitBenchmarker.new/perfkitbenchmarker/linux_benchmarks/aerospike_benchmark.py", line 179, in Run
    tps, latency = ParseOutput(stdout)
  File "/home/ubuntu/PerfKitBenchmarker.new/perfkitbenchmarker/linux_benchmarks/aerospike_benchmark.py", line 157, in ParseOutput
    r'Overall Average Latency \(ms\) ([0-9]+\.[0-9]+)', output)[-2:]
ValueError: need more than 0 values to unpack
```
