### ISSUE TITLE
Has a error when excuted ping test case in openstack provider.

### ISSUE THREAD

**Issue by wangxfbelieve** [GoogleCloudPlatform/PerfKitBenchmarker#988]
=================================================
command lines
=================================================
./pkb.py --cloud=OpenStack --benchmarks=ping --openstack_auth_url=http://192.168.247.15:5000/v2.0/ --openstack_password_file=~/.config/openstack-password.txt

=================================================
Error info
=================================================
Exception occurred while calling PrepareVm(<BaseVirtualMachine [ip=None, internal_ip=None]>):
Traceback (most recent call last):
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/background_tasks.py", line 234, in Run
    self.return_value = self.target(*self.args, **self.kwargs)
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 323, in PrepareVm
    vm.Create()
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/resource.py", line 130, in Create
    self._CreateResource()
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 239, in WrappedFunction
    return f(*args, **kwargs)
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/resource.py", line 101, in _CreateResource
    self._Create()
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/providers/openstack/os_virtual_machine.py", line 75, in _Create
    image = self.client.images.findall(name=self.image)[0]
IndexError: list index out of range

===================================
authentication info
===================================
#!/bin/sh
export LC_ALL=C
export OS_NO_CACHE='true'
export OS_TENANT_NAME='admin'
export OS_USERNAME='admin'
export OS_PASSWORD='admin'
export OS_AUTH_URL='http://192.168.247.15:5000/v2.0/'
export OS_AUTH_STRATEGY='keystone'
export OS_REGION_NAME='RegionOne'
export CINDER_ENDPOINT_TYPE='publicURL'
export GLANCE_ENDPOINT_TYPE='publicURL'
export KEYSTONE_ENDPOINT_TYPE='publicURL'
export NOVA_ENDPOINT_TYPE='publicURL'
export NEUTRON_ENDPOINT_TYPE='publicURL'

**Comment by wangxfbelieve** [comment]
=================================================
command lines
=================================================
./pkb.py --cloud=OpenStack --benchmarks=ping --openstack_auth_url=http://192.168.247.15:5000/v2.0/ --openstack_password_file=~/.config/openstack-password.txt

=================================================
Error info
=================================================
Exception occurred while calling PrepareVm(<BaseVirtualMachine [ip=None, internal_ip=None]>):
Traceback (most recent call last):
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/background_tasks.py", line 234, in Run
    self.return_value = self.target(*self.args, **self.kwargs)
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 323, in PrepareVm
    vm.Create()
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/resource.py", line 130, in Create
    self._CreateResource()
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 239, in WrappedFunction
    return f(*args, **kwargs)
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/resource.py", line 101, in _CreateResource
    self._Create()
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/providers/openstack/os_virtual_machine.py", line 75, in _Create
    image = self.client.images.findall(name=self.image)[0]
IndexError: list index out of range

===================================
authentication info
===================================
#!/bin/sh
export LC_ALL=C
export OS_NO_CACHE='true'
export OS_TENANT_NAME='admin'
export OS_USERNAME='admin'
export OS_PASSWORD='admin'
export OS_AUTH_URL='http://192.168.247.15:5000/v2.0/'
export OS_AUTH_STRATEGY='keystone'
export OS_REGION_NAME='RegionOne'
export CINDER_ENDPOINT_TYPE='publicURL'
export GLANCE_ENDPOINT_TYPE='publicURL'
export KEYSTONE_ENDPOINT_TYPE='publicURL'
export NOVA_ENDPOINT_TYPE='publicURL'
export NEUTRON_ENDPOINT_TYPE='publicURL'

**Comment by tedhtchang** [comment]
Try specify a image to deploy with --image
