### ISSUE TITLE
Unable to associate floating ip

### ISSUE THREAD

**Issue by wangxfbelieve** [GoogleCloudPlatform/PerfKitBenchmarker#992]
Exception occurred while calling PrepareVm(172.16.107.23):
Traceback (most recent call last):
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/background_tasks.py", line 234, in Run
    self.return_value = self.target(*self.args, **self.kwargs)
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 323, in PrepareVm
    vm.Create()
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/resource.py", line 131, in Create
    self._PostCreate()
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 245, in WrappedFunction
    raise e
BadRequest: Error. Unable to associate floating ip (HTTP 400) (Request-ID: req-5b6952e5-ac9d-44f9-8ca9-0f6d6d3da19c)

========
command
========
./pkb.py --cloud=OpenStack --benchmarks=ping --openstack_auth_url=http://192.168.247.15:5000/v2.0 --image=centos7 --openstack_network=private1 --openstack_image_username=root --machine_type=2C4G0G --openstack_boot_from_volume=true --openstack_volume_size=25 --openstack_floating_ip_pool=net04_ext

**Comment by hildrum** [comment]
@kivio, @meteorfox  any ideas?

**Comment by tedhtchang** [comment]
@wangxfbelieve 
First try these steps without perfkit.
1. deploy a VM
2. associate a floatingip to the VM
3. ping the floatingip from your perfkit host.

**Comment by wangxfbelieve** [comment]
My env is doesn/t not work about the floating IP. I am so sorry about the issue.I will be close the issue.
thx @tedhtchang .
